// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/chat/domain (interfaces: ChatService)
//
// Generated by this command:
//
//	mockgen -destination=mock/chat_service_mock.go -package=domainmock . ChatService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/chat/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// AcceptFriendRequest mocks base method.
func (m *MockChatService) AcceptFriendRequest(ctx context.Context, requestID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFriendRequest", ctx, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFriendRequest indicates an expected call of AcceptFriendRequest.
func (mr *MockChatServiceMockRecorder) AcceptFriendRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendRequest", reflect.TypeOf((*MockChatService)(nil).AcceptFriendRequest), ctx, requestID)
}

// CreateParty mocks base method.
func (m *MockChatService) CreateParty(ctx context.Context, name string, leaderID uint32, leaderName string) (domain.Party, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParty", ctx, name, leaderID, leaderName)
	ret0, _ := ret[0].(domain.Party)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateParty indicates an expected call of CreateParty.
func (mr *MockChatServiceMockRecorder) CreateParty(ctx, name, leaderID, leaderName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParty", reflect.TypeOf((*MockChatService)(nil).CreateParty), ctx, name, leaderID, leaderName)
}

// GetParty mocks base method.
func (m *MockChatService) GetParty(ctx context.Context, partyID string) (domain.Party, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParty", ctx, partyID)
	ret0, _ := ret[0].(domain.Party)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParty indicates an expected call of GetParty.
func (mr *MockChatServiceMockRecorder) GetParty(ctx, partyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParty", reflect.TypeOf((*MockChatService)(nil).GetParty), ctx, partyID)
}

// JoinParty mocks base method.
func (m *MockChatService) JoinParty(ctx context.Context, partyID string, charID uint32, charName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinParty", ctx, partyID, charID, charName)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinParty indicates an expected call of JoinParty.
func (mr *MockChatServiceMockRecorder) JoinParty(ctx, partyID, charID, charName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinParty", reflect.TypeOf((*MockChatService)(nil).JoinParty), ctx, partyID, charID, charName)
}

// LeaveParty mocks base method.
func (m *MockChatService) LeaveParty(ctx context.Context, partyID string, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveParty", ctx, partyID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveParty indicates an expected call of LeaveParty.
func (mr *MockChatServiceMockRecorder) LeaveParty(ctx, partyID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveParty", reflect.TypeOf((*MockChatService)(nil).LeaveParty), ctx, partyID, charID)
}

// ListFriends mocks base method.
func (m *MockChatService) ListFriends(ctx context.Context, accountID uint32) ([]domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFriends", ctx, accountID)
	ret0, _ := ret[0].([]domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFriends indicates an expected call of ListFriends.
func (mr *MockChatServiceMockRecorder) ListFriends(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFriends", reflect.TypeOf((*MockChatService)(nil).ListFriends), ctx, accountID)
}

// RejectFriendRequest mocks base method.
func (m *MockChatService) RejectFriendRequest(ctx context.Context, requestID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectFriendRequest", ctx, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectFriendRequest indicates an expected call of RejectFriendRequest.
func (mr *MockChatServiceMockRecorder) RejectFriendRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectFriendRequest", reflect.TypeOf((*MockChatService)(nil).RejectFriendRequest), ctx, requestID)
}

// RemoveFriend mocks base method.
func (m *MockChatService) RemoveFriend(ctx context.Context, accountID, friendAccountID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFriend", ctx, accountID, friendAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFriend indicates an expected call of RemoveFriend.
func (mr *MockChatServiceMockRecorder) RemoveFriend(ctx, accountID, friendAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriend", reflect.TypeOf((*MockChatService)(nil).RemoveFriend), ctx, accountID, friendAccountID)
}

// SendFriendRequest mocks base method.
func (m *MockChatService) SendFriendRequest(ctx context.Context, fromAccountID, toAccountID uint32, fromName, toName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", ctx, fromAccountID, toAccountID, fromName, toName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockChatServiceMockRecorder) SendFriendRequest(ctx, fromAccountID, toAccountID, fromName, toName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockChatService)(nil).SendFriendRequest), ctx, fromAccountID, toAccountID, fromName, toName)
}

// SendMapChat mocks base method.
func (m *MockChatService) SendMapChat(ctx context.Context, senderID uint32, mapName, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMapChat", ctx, senderID, mapName, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMapChat indicates an expected call of SendMapChat.
func (mr *MockChatServiceMockRecorder) SendMapChat(ctx, senderID, mapName, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMapChat", reflect.TypeOf((*MockChatService)(nil).SendMapChat), ctx, senderID, mapName, content)
}

// SendPartyChat mocks base method.
func (m *MockChatService) SendPartyChat(ctx context.Context, senderID uint32, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPartyChat", ctx, senderID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPartyChat indicates an expected call of SendPartyChat.
func (mr *MockChatServiceMockRecorder) SendPartyChat(ctx, senderID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPartyChat", reflect.TypeOf((*MockChatService)(nil).SendPartyChat), ctx, senderID, content)
}

// Whisper mocks base method.
func (m *MockChatService) Whisper(ctx context.Context, senderID, targetID uint32, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Whisper", ctx, senderID, targetID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Whisper indicates an expected call of Whisper.
func (mr *MockChatServiceMockRecorder) Whisper(ctx, senderID, targetID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Whisper", reflect.TypeOf((*MockChatService)(nil).Whisper), ctx, senderID, targetID, content)
}
