// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/chat/domain (interfaces: FriendRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/friend_repository_mock.go -package=domainmock . FriendRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/chat/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFriendRepository is a mock of FriendRepository interface.
type MockFriendRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFriendRepositoryMockRecorder
	isgomock struct{}
}

// MockFriendRepositoryMockRecorder is the mock recorder for MockFriendRepository.
type MockFriendRepositoryMockRecorder struct {
	mock *MockFriendRepository
}

// NewMockFriendRepository creates a new mock instance.
func NewMockFriendRepository(ctrl *gomock.Controller) *MockFriendRepository {
	mock := &MockFriendRepository{ctrl: ctrl}
	mock.recorder = &MockFriendRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendRepository) EXPECT() *MockFriendRepositoryMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockFriendRepository) AddFriend(ctx context.Context, friendship domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFriend", ctx, friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockFriendRepositoryMockRecorder) AddFriend(ctx, friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockFriendRepository)(nil).AddFriend), ctx, friendship)
}

// CreateFriendRequest mocks base method.
func (m *MockFriendRepository) CreateFriendRequest(ctx context.Context, req domain.FriendRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFriendRequest", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFriendRequest indicates an expected call of CreateFriendRequest.
func (mr *MockFriendRepositoryMockRecorder) CreateFriendRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFriendRequest", reflect.TypeOf((*MockFriendRepository)(nil).CreateFriendRequest), ctx, req)
}

// GetFriendRequest mocks base method.
func (m *MockFriendRepository) GetFriendRequest(ctx context.Context, requestID uint64) (domain.FriendRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendRequest", ctx, requestID)
	ret0, _ := ret[0].(domain.FriendRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriendRequest indicates an expected call of GetFriendRequest.
func (mr *MockFriendRepositoryMockRecorder) GetFriendRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendRequest", reflect.TypeOf((*MockFriendRepository)(nil).GetFriendRequest), ctx, requestID)
}

// GetPendingFriendRequests mocks base method.
func (m *MockFriendRepository) GetPendingFriendRequests(ctx context.Context, accountID uint32) ([]domain.FriendRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingFriendRequests", ctx, accountID)
	ret0, _ := ret[0].([]domain.FriendRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingFriendRequests indicates an expected call of GetPendingFriendRequests.
func (mr *MockFriendRepositoryMockRecorder) GetPendingFriendRequests(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingFriendRequests", reflect.TypeOf((*MockFriendRepository)(nil).GetPendingFriendRequests), ctx, accountID)
}

// HasPendingRequest mocks base method.
func (m *MockFriendRepository) HasPendingRequest(ctx context.Context, fromAccountID, toAccountID uint32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPendingRequest", ctx, fromAccountID, toAccountID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPendingRequest indicates an expected call of HasPendingRequest.
func (mr *MockFriendRepositoryMockRecorder) HasPendingRequest(ctx, fromAccountID, toAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPendingRequest", reflect.TypeOf((*MockFriendRepository)(nil).HasPendingRequest), ctx, fromAccountID, toAccountID)
}

// IsFriend mocks base method.
func (m *MockFriendRepository) IsFriend(ctx context.Context, accountID, friendAccountID uint32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFriend", ctx, accountID, friendAccountID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFriend indicates an expected call of IsFriend.
func (mr *MockFriendRepositoryMockRecorder) IsFriend(ctx, accountID, friendAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFriend", reflect.TypeOf((*MockFriendRepository)(nil).IsFriend), ctx, accountID, friendAccountID)
}

// ListFriends mocks base method.
func (m *MockFriendRepository) ListFriends(ctx context.Context, accountID uint32) ([]domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFriends", ctx, accountID)
	ret0, _ := ret[0].([]domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFriends indicates an expected call of ListFriends.
func (mr *MockFriendRepositoryMockRecorder) ListFriends(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFriends", reflect.TypeOf((*MockFriendRepository)(nil).ListFriends), ctx, accountID)
}

// RemoveFriend mocks base method.
func (m *MockFriendRepository) RemoveFriend(ctx context.Context, accountID, friendAccountID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFriend", ctx, accountID, friendAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFriend indicates an expected call of RemoveFriend.
func (mr *MockFriendRepositoryMockRecorder) RemoveFriend(ctx, accountID, friendAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriend", reflect.TypeOf((*MockFriendRepository)(nil).RemoveFriend), ctx, accountID, friendAccountID)
}

// UpdateFriendRequest mocks base method.
func (m *MockFriendRepository) UpdateFriendRequest(ctx context.Context, req domain.FriendRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFriendRequest", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFriendRequest indicates an expected call of UpdateFriendRequest.
func (mr *MockFriendRepositoryMockRecorder) UpdateFriendRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFriendRequest", reflect.TypeOf((*MockFriendRepository)(nil).UpdateFriendRequest), ctx, req)
}
