// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/chat/domain (interfaces: PartyRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/party_repository_mock.go -package=domainmock . PartyRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/chat/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPartyRepository is a mock of PartyRepository interface.
type MockPartyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartyRepositoryMockRecorder
	isgomock struct{}
}

// MockPartyRepositoryMockRecorder is the mock recorder for MockPartyRepository.
type MockPartyRepositoryMockRecorder struct {
	mock *MockPartyRepository
}

// NewMockPartyRepository creates a new mock instance.
func NewMockPartyRepository(ctrl *gomock.Controller) *MockPartyRepository {
	mock := &MockPartyRepository{ctrl: ctrl}
	mock.recorder = &MockPartyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartyRepository) EXPECT() *MockPartyRepositoryMockRecorder {
	return m.recorder
}

// CreateParty mocks base method.
func (m *MockPartyRepository) CreateParty(ctx context.Context, party domain.Party) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParty", ctx, party)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateParty indicates an expected call of CreateParty.
func (mr *MockPartyRepositoryMockRecorder) CreateParty(ctx, party any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParty", reflect.TypeOf((*MockPartyRepository)(nil).CreateParty), ctx, party)
}

// DeleteParty mocks base method.
func (m *MockPartyRepository) DeleteParty(ctx context.Context, partyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParty", ctx, partyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParty indicates an expected call of DeleteParty.
func (mr *MockPartyRepositoryMockRecorder) DeleteParty(ctx, partyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParty", reflect.TypeOf((*MockPartyRepository)(nil).DeleteParty), ctx, partyID)
}

// GetParty mocks base method.
func (m *MockPartyRepository) GetParty(ctx context.Context, partyID string) (domain.Party, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParty", ctx, partyID)
	ret0, _ := ret[0].(domain.Party)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParty indicates an expected call of GetParty.
func (mr *MockPartyRepositoryMockRecorder) GetParty(ctx, partyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParty", reflect.TypeOf((*MockPartyRepository)(nil).GetParty), ctx, partyID)
}

// GetPartyByMember mocks base method.
func (m *MockPartyRepository) GetPartyByMember(ctx context.Context, charID uint32) (domain.Party, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartyByMember", ctx, charID)
	ret0, _ := ret[0].(domain.Party)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPartyByMember indicates an expected call of GetPartyByMember.
func (mr *MockPartyRepositoryMockRecorder) GetPartyByMember(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartyByMember", reflect.TypeOf((*MockPartyRepository)(nil).GetPartyByMember), ctx, charID)
}

// UpdateParty mocks base method.
func (m *MockPartyRepository) UpdateParty(ctx context.Context, party domain.Party) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParty", ctx, party)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParty indicates an expected call of UpdateParty.
func (mr *MockPartyRepositoryMockRecorder) UpdateParty(ctx, party any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParty", reflect.TypeOf((*MockPartyRepository)(nil).UpdateParty), ctx, party)
}
