// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/identity/domain (interfaces: IdentityService)
//
// Generated by this command:
//
//	mockgen -destination=mock/identity_service_mock.go -package=domainmock . IdentityService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityService is a mock of IdentityService interface.
type MockIdentityService struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceMockRecorder
	isgomock struct{}
}

// MockIdentityServiceMockRecorder is the mock recorder for MockIdentityService.
type MockIdentityServiceMockRecorder struct {
	mock *MockIdentityService
}

// NewMockIdentityService creates a new mock instance.
func NewMockIdentityService(ctrl *gomock.Controller) *MockIdentityService {
	mock := &MockIdentityService{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityService) EXPECT() *MockIdentityServiceMockRecorder {
	return m.recorder
}

// ListCharacters mocks base method.
func (m *MockIdentityService) ListCharacters(ctx context.Context, accountID uint32) ([]domain.CharacterSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCharacters", ctx, accountID)
	ret0, _ := ret[0].([]domain.CharacterSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCharacters indicates an expected call of ListCharacters.
func (mr *MockIdentityServiceMockRecorder) ListCharacters(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCharacters", reflect.TypeOf((*MockIdentityService)(nil).ListCharacters), ctx, accountID)
}

// Login mocks base method.
func (m *MockIdentityService) Login(ctx context.Context, req domain.LoginRequest) (*domain.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*domain.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIdentityServiceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIdentityService)(nil).Login), ctx, req)
}
