// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/transit/domain (interfaces: TransitMessenger)
//
// Generated by this command:
//
//	mockgen -destination=mock/transit_messenger_mock.go -package=domainmock . TransitMessenger
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/transit/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransitMessenger is a mock of TransitMessenger interface.
type MockTransitMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockTransitMessengerMockRecorder
	isgomock struct{}
}

// MockTransitMessengerMockRecorder is the mock recorder for MockTransitMessenger.
type MockTransitMessengerMockRecorder struct {
	mock *MockTransitMessenger
}

// NewMockTransitMessenger creates a new mock instance.
func NewMockTransitMessenger(ctrl *gomock.Controller) *MockTransitMessenger {
	mock := &MockTransitMessenger{ctrl: ctrl}
	mock.recorder = &MockTransitMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransitMessenger) EXPECT() *MockTransitMessengerMockRecorder {
	return m.recorder
}

// PublishRequest mocks base method.
func (m *MockTransitMessenger) PublishRequest(ctx context.Context, subject string, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRequest", ctx, subject, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishRequest indicates an expected call of PublishRequest.
func (mr *MockTransitMessengerMockRecorder) PublishRequest(ctx, subject, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRequest", reflect.TypeOf((*MockTransitMessenger)(nil).PublishRequest), ctx, subject, data)
}

// Subscribe mocks base method.
func (m *MockTransitMessenger) Subscribe(subject string, handler func(context.Context, []byte) ([]byte, error)) (domain.UnsubscribeFunc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", subject, handler)
	ret0, _ := ret[0].(domain.UnsubscribeFunc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockTransitMessengerMockRecorder) Subscribe(subject, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockTransitMessenger)(nil).Subscribe), subject, handler)
}
