// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/transit/domain (interfaces: TransitService)
//
// Generated by this command:
//
//	mockgen -destination=mock/transit_service_mock.go -package=domainmock . TransitService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/transit/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransitService is a mock of TransitService interface.
type MockTransitService struct {
	ctrl     *gomock.Controller
	recorder *MockTransitServiceMockRecorder
	isgomock struct{}
}

// MockTransitServiceMockRecorder is the mock recorder for MockTransitService.
type MockTransitServiceMockRecorder struct {
	mock *MockTransitService
}

// NewMockTransitService creates a new mock instance.
func NewMockTransitService(ctrl *gomock.Controller) *MockTransitService {
	mock := &MockTransitService{ctrl: ctrl}
	mock.recorder = &MockTransitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransitService) EXPECT() *MockTransitServiceMockRecorder {
	return m.recorder
}

// HandleTransitRequest mocks base method.
func (m *MockTransitService) HandleTransitRequest(ctx context.Context, req domain.TransitRequest) (*domain.TransitAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTransitRequest", ctx, req)
	ret0, _ := ret[0].(*domain.TransitAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTransitRequest indicates an expected call of HandleTransitRequest.
func (mr *MockTransitServiceMockRecorder) HandleTransitRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTransitRequest", reflect.TypeOf((*MockTransitService)(nil).HandleTransitRequest), ctx, req)
}

// InitiateTransit mocks base method.
func (m *MockTransitService) InitiateTransit(ctx context.Context, req domain.TransitRequest) (*domain.TransitAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateTransit", ctx, req)
	ret0, _ := ret[0].(*domain.TransitAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateTransit indicates an expected call of InitiateTransit.
func (mr *MockTransitServiceMockRecorder) InitiateTransit(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateTransit", reflect.TypeOf((*MockTransitService)(nil).InitiateTransit), ctx, req)
}

// SubscribeTransit mocks base method.
func (m *MockTransitService) SubscribeTransit(ctx context.Context, zoneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeTransit", ctx, zoneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeTransit indicates an expected call of SubscribeTransit.
func (mr *MockTransitServiceMockRecorder) SubscribeTransit(ctx, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTransit", reflect.TypeOf((*MockTransitService)(nil).SubscribeTransit), ctx, zoneID)
}
