// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/transit/domain (interfaces: TransitConfigSource)
//
// Generated by this command:
//
//	mockgen -destination=mock/transit_config_source_mock.go -package=domainmock . TransitConfigSource
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/transit/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransitConfigSource is a mock of TransitConfigSource interface.
type MockTransitConfigSource struct {
	ctrl     *gomock.Controller
	recorder *MockTransitConfigSourceMockRecorder
	isgomock struct{}
}

// MockTransitConfigSourceMockRecorder is the mock recorder for MockTransitConfigSource.
type MockTransitConfigSourceMockRecorder struct {
	mock *MockTransitConfigSource
}

// NewMockTransitConfigSource creates a new mock instance.
func NewMockTransitConfigSource(ctrl *gomock.Controller) *MockTransitConfigSource {
	mock := &MockTransitConfigSource{ctrl: ctrl}
	mock.recorder = &MockTransitConfigSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransitConfigSource) EXPECT() *MockTransitConfigSourceMockRecorder {
	return m.recorder
}

// EndpointFor mocks base method.
func (m *MockTransitConfigSource) EndpointFor(zoneID string) (domain.TransitEndpoint, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointFor", zoneID)
	ret0, _ := ret[0].(domain.TransitEndpoint)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// EndpointFor indicates an expected call of EndpointFor.
func (mr *MockTransitConfigSourceMockRecorder) EndpointFor(zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointFor", reflect.TypeOf((*MockTransitConfigSource)(nil).EndpointFor), zoneID)
}
