// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/identity/domain (interfaces: AccountRepository)
//
// Generated by this command:
//
//	mockgen -destination=../repository/mock/account_repository_mock.go -package=mocks . AccountRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// LoadByID mocks base method.
func (m *MockAccountRepository) LoadByID(ctx context.Context, accountID uint32) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByID", ctx, accountID)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByID indicates an expected call of LoadByID.
func (mr *MockAccountRepositoryMockRecorder) LoadByID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByID", reflect.TypeOf((*MockAccountRepository)(nil).LoadByID), ctx, accountID)
}

// LoadByUserID mocks base method.
func (m *MockAccountRepository) LoadByUserID(ctx context.Context, userID string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByUserID indicates an expected call of LoadByUserID.
func (mr *MockAccountRepositoryMockRecorder) LoadByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByUserID", reflect.TypeOf((*MockAccountRepository)(nil).LoadByUserID), ctx, userID)
}

// UpdateLoginInfo mocks base method.
func (m *MockAccountRepository) UpdateLoginInfo(ctx context.Context, accountID uint32, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoginInfo", ctx, accountID, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoginInfo indicates an expected call of UpdateLoginInfo.
func (mr *MockAccountRepositoryMockRecorder) UpdateLoginInfo(ctx, accountID, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoginInfo", reflect.TypeOf((*MockAccountRepository)(nil).UpdateLoginInfo), ctx, accountID, ip)
}
