// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/identity/domain (interfaces: CharacterRepository)
//
// Generated by this command:
//
//	mockgen -destination=../repository/mock/character_repository_mock.go -package=mocks . CharacterRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterRepository is a mock of CharacterRepository interface.
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterRepositoryMockRecorder is the mock recorder for MockCharacterRepository.
type MockCharacterRepositoryMockRecorder struct {
	mock *MockCharacterRepository
}

// NewMockCharacterRepository creates a new mock instance.
func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepository) EXPECT() *MockCharacterRepositoryMockRecorder {
	return m.recorder
}

// AllocateStat mocks base method.
func (m *MockCharacterRepository) AllocateStat(ctx context.Context, accountID, charID uint32, statColumn string, currentVal, amount uint8, cost uint32) (uint32, uint32, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateStat", ctx, accountID, charID, statColumn, currentVal, amount, cost)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// AllocateStat indicates an expected call of AllocateStat.
func (mr *MockCharacterRepositoryMockRecorder) AllocateStat(ctx, accountID, charID, statColumn, currentVal, amount, cost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateStat", reflect.TypeOf((*MockCharacterRepository)(nil).AllocateStat), ctx, accountID, charID, statColumn, currentVal, amount, cost)
}

// ApplyLevelUp mocks base method.
func (m *MockCharacterRepository) ApplyLevelUp(ctx context.Context, accountID, charID, fromLevel, toLevel, grantedStatusPoints uint32) (uint32, uint32, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyLevelUp", ctx, accountID, charID, fromLevel, toLevel, grantedStatusPoints)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ApplyLevelUp indicates an expected call of ApplyLevelUp.
func (mr *MockCharacterRepositoryMockRecorder) ApplyLevelUp(ctx, accountID, charID, fromLevel, toLevel, grantedStatusPoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyLevelUp", reflect.TypeOf((*MockCharacterRepository)(nil).ApplyLevelUp), ctx, accountID, charID, fromLevel, toLevel, grantedStatusPoints)
}

// GetByID mocks base method.
func (m *MockCharacterRepository) GetByID(ctx context.Context, accountID, charID uint32) (*domain.CharacterSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, accountID, charID)
	ret0, _ := ret[0].(*domain.CharacterSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCharacterRepositoryMockRecorder) GetByID(ctx, accountID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCharacterRepository)(nil).GetByID), ctx, accountID, charID)
}

// ListByAccount mocks base method.
func (m *MockCharacterRepository) ListByAccount(ctx context.Context, accountID uint32, maxSlots int) ([]domain.CharacterSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID, maxSlots)
	ret0, _ := ret[0].([]domain.CharacterSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockCharacterRepositoryMockRecorder) ListByAccount(ctx, accountID, maxSlots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockCharacterRepository)(nil).ListByAccount), ctx, accountID, maxSlots)
}
