// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/identity/domain (interfaces: WarehouseLock)
//
// Generated by this command:
//
//	mockgen -destination=../repository/mock/warehouse_lock_mock.go -package=mocks . WarehouseLock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockWarehouseLock is a mock of WarehouseLock interface.
type MockWarehouseLock struct {
	ctrl     *gomock.Controller
	recorder *MockWarehouseLockMockRecorder
	isgomock struct{}
}

// MockWarehouseLockMockRecorder is the mock recorder for MockWarehouseLock.
type MockWarehouseLockMockRecorder struct {
	mock *MockWarehouseLock
}

// NewMockWarehouseLock creates a new mock instance.
func NewMockWarehouseLock(ctrl *gomock.Controller) *MockWarehouseLock {
	mock := &MockWarehouseLock{ctrl: ctrl}
	mock.recorder = &MockWarehouseLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarehouseLock) EXPECT() *MockWarehouseLockMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockWarehouseLock) Acquire(ctx context.Context, accountID uint32, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, accountID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockWarehouseLockMockRecorder) Acquire(ctx, accountID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockWarehouseLock)(nil).Acquire), ctx, accountID, ttl)
}

// Release mocks base method.
func (m *MockWarehouseLock) Release(ctx context.Context, accountID uint32, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, accountID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockWarehouseLockMockRecorder) Release(ctx, accountID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockWarehouseLock)(nil).Release), ctx, accountID, token)
}
