// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/trade/domain (interfaces: TradeService)
//
// Generated by this command:
//
//	mockgen -destination=mock/trade_service_mock.go -package=domainmock . TradeService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/trade/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTradeService is a mock of TradeService interface.
type MockTradeService struct {
	ctrl     *gomock.Controller
	recorder *MockTradeServiceMockRecorder
	isgomock struct{}
}

// MockTradeServiceMockRecorder is the mock recorder for MockTradeService.
type MockTradeServiceMockRecorder struct {
	mock *MockTradeService
}

// NewMockTradeService creates a new mock instance.
func NewMockTradeService(ctrl *gomock.Controller) *MockTradeService {
	mock := &MockTradeService{ctrl: ctrl}
	mock.recorder = &MockTradeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTradeService) EXPECT() *MockTradeServiceMockRecorder {
	return m.recorder
}

// AcceptTrade mocks base method.
func (m *MockTradeService) AcceptTrade(ctx context.Context, tradeID string, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptTrade", ctx, tradeID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptTrade indicates an expected call of AcceptTrade.
func (mr *MockTradeServiceMockRecorder) AcceptTrade(ctx, tradeID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptTrade", reflect.TypeOf((*MockTradeService)(nil).AcceptTrade), ctx, tradeID, charID)
}

// AddTradeItem mocks base method.
func (m *MockTradeService) AddTradeItem(ctx context.Context, tradeID string, charID, itemID uint32, amount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTradeItem", ctx, tradeID, charID, itemID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTradeItem indicates an expected call of AddTradeItem.
func (mr *MockTradeServiceMockRecorder) AddTradeItem(ctx, tradeID, charID, itemID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTradeItem", reflect.TypeOf((*MockTradeService)(nil).AddTradeItem), ctx, tradeID, charID, itemID, amount)
}

// AddTradeZeny mocks base method.
func (m *MockTradeService) AddTradeZeny(ctx context.Context, tradeID string, charID, zeny uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTradeZeny", ctx, tradeID, charID, zeny)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTradeZeny indicates an expected call of AddTradeZeny.
func (mr *MockTradeServiceMockRecorder) AddTradeZeny(ctx, tradeID, charID, zeny any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTradeZeny", reflect.TypeOf((*MockTradeService)(nil).AddTradeZeny), ctx, tradeID, charID, zeny)
}

// CancelTrade mocks base method.
func (m *MockTradeService) CancelTrade(ctx context.Context, tradeID string, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTrade", ctx, tradeID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTrade indicates an expected call of CancelTrade.
func (mr *MockTradeServiceMockRecorder) CancelTrade(ctx, tradeID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTrade", reflect.TypeOf((*MockTradeService)(nil).CancelTrade), ctx, tradeID, charID)
}

// CompleteTrade mocks base method.
func (m *MockTradeService) CompleteTrade(ctx context.Context, tradeID string, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTrade", ctx, tradeID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTrade indicates an expected call of CompleteTrade.
func (mr *MockTradeServiceMockRecorder) CompleteTrade(ctx, tradeID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTrade", reflect.TypeOf((*MockTradeService)(nil).CompleteTrade), ctx, tradeID, charID)
}

// ConfirmTrade mocks base method.
func (m *MockTradeService) ConfirmTrade(ctx context.Context, tradeID string, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmTrade", ctx, tradeID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmTrade indicates an expected call of ConfirmTrade.
func (mr *MockTradeServiceMockRecorder) ConfirmTrade(ctx, tradeID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmTrade", reflect.TypeOf((*MockTradeService)(nil).ConfirmTrade), ctx, tradeID, charID)
}

// RequestTrade mocks base method.
func (m *MockTradeService) RequestTrade(ctx context.Context, charID, targetCharID uint32) (domain.Trade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestTrade", ctx, charID, targetCharID)
	ret0, _ := ret[0].(domain.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestTrade indicates an expected call of RequestTrade.
func (mr *MockTradeServiceMockRecorder) RequestTrade(ctx, charID, targetCharID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestTrade", reflect.TypeOf((*MockTradeService)(nil).RequestTrade), ctx, charID, targetCharID)
}
