// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/trade/domain (interfaces: TradeRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/trade_repository_mock.go -package=domainmock . TradeRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/trade/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTradeRepository is a mock of TradeRepository interface.
type MockTradeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTradeRepositoryMockRecorder
	isgomock struct{}
}

// MockTradeRepositoryMockRecorder is the mock recorder for MockTradeRepository.
type MockTradeRepositoryMockRecorder struct {
	mock *MockTradeRepository
}

// NewMockTradeRepository creates a new mock instance.
func NewMockTradeRepository(ctrl *gomock.Controller) *MockTradeRepository {
	mock := &MockTradeRepository{ctrl: ctrl}
	mock.recorder = &MockTradeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTradeRepository) EXPECT() *MockTradeRepositoryMockRecorder {
	return m.recorder
}

// CreateTrade mocks base method.
func (m *MockTradeRepository) CreateTrade(ctx context.Context, trade domain.Trade) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrade", ctx, trade)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrade indicates an expected call of CreateTrade.
func (mr *MockTradeRepositoryMockRecorder) CreateTrade(ctx, trade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrade", reflect.TypeOf((*MockTradeRepository)(nil).CreateTrade), ctx, trade)
}

// DeleteTrade mocks base method.
func (m *MockTradeRepository) DeleteTrade(ctx context.Context, tradeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrade", ctx, tradeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrade indicates an expected call of DeleteTrade.
func (mr *MockTradeRepositoryMockRecorder) DeleteTrade(ctx, tradeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrade", reflect.TypeOf((*MockTradeRepository)(nil).DeleteTrade), ctx, tradeID)
}

// ExecuteTradeTransfer mocks base method.
func (m *MockTradeRepository) ExecuteTradeTransfer(ctx context.Context, trade domain.Trade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTradeTransfer", ctx, trade)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteTradeTransfer indicates an expected call of ExecuteTradeTransfer.
func (mr *MockTradeRepositoryMockRecorder) ExecuteTradeTransfer(ctx, trade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTradeTransfer", reflect.TypeOf((*MockTradeRepository)(nil).ExecuteTradeTransfer), ctx, trade)
}

// GetTrade mocks base method.
func (m *MockTradeRepository) GetTrade(ctx context.Context, tradeID string) (domain.Trade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrade", ctx, tradeID)
	ret0, _ := ret[0].(domain.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrade indicates an expected call of GetTrade.
func (mr *MockTradeRepositoryMockRecorder) GetTrade(ctx, tradeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrade", reflect.TypeOf((*MockTradeRepository)(nil).GetTrade), ctx, tradeID)
}

// UpdateTrade mocks base method.
func (m *MockTradeRepository) UpdateTrade(ctx context.Context, trade domain.Trade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrade", ctx, trade)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrade indicates an expected call of UpdateTrade.
func (mr *MockTradeRepositoryMockRecorder) UpdateTrade(ctx, trade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrade", reflect.TypeOf((*MockTradeRepository)(nil).UpdateTrade), ctx, trade)
}
