-- Wave 2: rAthena `char` table (sql-files/main.sql, Thai Classic).
-- Read/write-compatible with rAthena. NOTE reserved-word columns: `int` and
-- `rename` are MariaDB reserved — always back-quote in raw SQL / GORM must not
-- list them unquoted. int stores the INT stat; rename is the rename counter.
CREATE TABLE IF NOT EXISTS `char` (
  `char_id` int unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int unsigned NOT NULL DEFAULT 0,
  `char_num` tinyint NOT NULL DEFAULT 0,
  `name` varchar(30) NOT NULL DEFAULT '',
  `class` smallint unsigned NOT NULL DEFAULT 0,
  `base_level` smallint unsigned NOT NULL DEFAULT 1,
  `job_level` smallint unsigned NOT NULL DEFAULT 1,
  `base_exp` bigint unsigned NOT NULL DEFAULT 0,
  `job_exp` bigint unsigned NOT NULL DEFAULT 0,
  `zeny` int unsigned NOT NULL DEFAULT 0,
  `str` smallint unsigned NOT NULL DEFAULT 0,
  `agi` smallint unsigned NOT NULL DEFAULT 0,
  `vit` smallint unsigned NOT NULL DEFAULT 0,
  `int` smallint unsigned NOT NULL DEFAULT 0,
  `dex` smallint unsigned NOT NULL DEFAULT 0,
  `luk` smallint unsigned NOT NULL DEFAULT 0,
  `max_hp` int unsigned NOT NULL DEFAULT 0,
  `hp` int unsigned NOT NULL DEFAULT 0,
  `max_sp` int unsigned NOT NULL DEFAULT 0,
  `sp` int unsigned NOT NULL DEFAULT 0,
  `status_point` int unsigned NOT NULL DEFAULT 0,
  `skill_point` int unsigned NOT NULL DEFAULT 0,
  `option` int unsigned NOT NULL DEFAULT 0,
  `sex` tinyint NOT NULL DEFAULT 0,
  `hair` tinyint unsigned NOT NULL DEFAULT 0,
  `hair_color` smallint unsigned NOT NULL DEFAULT 0,
  `clothes_color` smallint unsigned NOT NULL DEFAULT 0,
  `body` smallint NOT NULL DEFAULT 0,
  `weapon` smallint unsigned NOT NULL DEFAULT 0,
  `shield` smallint unsigned NOT NULL DEFAULT 0,
  `head_top` smallint unsigned NOT NULL DEFAULT 0,
  `head_mid` smallint unsigned NOT NULL DEFAULT 0,
  `head_bottom` smallint unsigned NOT NULL DEFAULT 0,
  `last_map` varchar(11) NOT NULL DEFAULT '',
  `last_x` smallint unsigned NOT NULL DEFAULT 53,
  `last_y` smallint unsigned NOT NULL DEFAULT 111,
  `save_map` varchar(11) NOT NULL DEFAULT '',
  `save_x` smallint unsigned NOT NULL DEFAULT 53,
  `save_y` smallint unsigned NOT NULL DEFAULT 111,
  `partner_id` int unsigned NOT NULL DEFAULT 0,
  `online` tinyint NOT NULL DEFAULT 0,
  `father` int unsigned NOT NULL DEFAULT 0,
  `mother` int unsigned NOT NULL DEFAULT 0,
  `child` int unsigned NOT NULL DEFAULT 0,
  `fame` int unsigned NOT NULL DEFAULT 0,
  `rename` smallint unsigned NOT NULL DEFAULT 0,
  `delete_date` int unsigned NOT NULL DEFAULT 0,
  `moves` int unsigned NOT NULL DEFAULT 0,
  `unban` int unsigned NOT NULL DEFAULT 0,
  `hotkey` tinyint unsigned NOT NULL DEFAULT 0,
  `clan_id` int unsigned NOT NULL DEFAULT 0,
  `title_id` int unsigned NOT NULL DEFAULT 0,
  `last_login` datetime DEFAULT NULL,
  PRIMARY KEY (`char_id`),
  UNIQUE KEY `name` (`name`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB;
