// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/inventory/domain (interfaces: InventoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/inventory_repository_mock.go -package=domainmock . InventoryRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/inventory/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockInventoryRepository) Add(ctx context.Context, charID uint32, item domain.InventoryItem) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, charID, item)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockInventoryRepositoryMockRecorder) Add(ctx, charID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockInventoryRepository)(nil).Add), ctx, charID, item)
}

// ConsumeOne mocks base method.
func (m *MockInventoryRepository) ConsumeOne(ctx context.Context, id uint32) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeOne", ctx, id)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeOne indicates an expected call of ConsumeOne.
func (mr *MockInventoryRepositoryMockRecorder) ConsumeOne(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeOne", reflect.TypeOf((*MockInventoryRepository)(nil).ConsumeOne), ctx, id)
}

// ListByChar mocks base method.
func (m *MockInventoryRepository) ListByChar(ctx context.Context, charID uint32) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByChar", ctx, charID)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByChar indicates an expected call of ListByChar.
func (mr *MockInventoryRepositoryMockRecorder) ListByChar(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByChar", reflect.TypeOf((*MockInventoryRepository)(nil).ListByChar), ctx, charID)
}

// Remove mocks base method.
func (m *MockInventoryRepository) Remove(ctx context.Context, id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockInventoryRepositoryMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockInventoryRepository)(nil).Remove), ctx, id)
}

// SetEquip mocks base method.
func (m *MockInventoryRepository) SetEquip(ctx context.Context, id, equipMask uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEquip", ctx, id, equipMask)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEquip indicates an expected call of SetEquip.
func (mr *MockInventoryRepositoryMockRecorder) SetEquip(ctx, id, equipMask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEquip", reflect.TypeOf((*MockInventoryRepository)(nil).SetEquip), ctx, id, equipMask)
}

// UpdateAmount mocks base method.
func (m *MockInventoryRepository) UpdateAmount(ctx context.Context, id, amount uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAmount", ctx, id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAmount indicates an expected call of UpdateAmount.
func (mr *MockInventoryRepositoryMockRecorder) UpdateAmount(ctx, id, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAmount", reflect.TypeOf((*MockInventoryRepository)(nil).UpdateAmount), ctx, id, amount)
}
