// Command import-conf converts an rAthena conf/ tree into a goAthena
// config.yaml overlay. It is a one-shot import-time translator; runtime
// configuration is always YAML loaded by internal/config (decision D-007).
//
// Usage:
//
//	import-conf [--src <rathena-conf-dir>] [--out <output.yaml>] [--root <rathena-root>]
//
// Defaults: --src third_party/rathena/conf, --out config.rathena.yaml,
// --root inferred from --src (the parent directory that contains a
// "conf" subdirectory).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/bouroo/goAthena/internal/config"
	"github.com/bouroo/goAthena/pkg/ro/athenaconf"
)

const (
	defaultSrc = "third_party/rathena/conf"
	defaultOut = "config.rathena.yaml"
)

// Run returns the process exit code. Kept separate from main so tests
// can drive it without spawning a subprocess.
func Run(args []string) int {
	src, out, root, err := parseFlags(args)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		printUsage()
		return 1
	}

	parser := athenaconf.NewParser(root)
	merged, manifest, err := parser.ParseDir(src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "import-conf: parse failed: %v\n", err)
		return 1
	}

	// ApplyToConfig populates manifest.Unmapped so the emitted overlay
	// can list every key that did not land on a typed Config field.
	cfg := &config.Config{}
	if applyErr := athenaconf.ApplyToConfig(cfg, merged, manifest); applyErr != nil {
		fmt.Fprintf(os.Stderr, "import-conf: apply: %v\n", applyErr)
		return 1
	}

	doc := buildYAMLDoc(merged, manifest, cfg)
	if err := writeYAML(out, doc); err != nil {
		fmt.Fprintf(os.Stderr, "import-conf: write %s: %v\n", out, err)
		return 1
	}

	fmt.Printf("import-conf: wrote %s (keys=%d unmapped=%d sources=%d)\n",
		out, len(merged.Keys), len(manifest.Unmapped), len(manifest.Sources))
	return 0
}

func main() {
	os.Exit(Run(os.Args[1:]))
}

func parseFlags(args []string) (src, out, root string, err error) {
	src = defaultSrc
	out = defaultOut

	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch arg {
		case "--src":
			i++
			if i >= len(args) {
				return "", "", "", fmt.Errorf("flag %s requires a value", arg)
			}
			src = args[i]
		case "--out":
			i++
			if i >= len(args) {
				return "", "", "", fmt.Errorf("flag %s requires a value", arg)
			}
			out = args[i]
		case "--root":
			i++
			if i >= len(args) {
				return "", "", "", fmt.Errorf("flag %s requires a value", arg)
			}
			root = args[i]
		case "-h", "--help":
			printUsage()
			os.Exit(0)
		default:
			return "", "", "", fmt.Errorf("unknown flag: %s", arg)
		}
	}

	if root == "" {
		root = athenaconf.DefaultRootDir(src)
	}
	return src, out, root, nil
}

// yamlDoc is the on-disk shape emitted by import-conf. Top-level keys
// mirror config.Config; rathena_unmapped holds every key not yet wired
// to a typed Config field so operators can see what was dropped.
type yamlDoc struct {
	Identity struct {
		UseMD5Passwords bool `yaml:"use_md5_passwords"`
		MaxChars        int  `yaml:"max_chars"`
	} `yaml:"identity"`
	RathenaUnmapped map[string]string `yaml:"rathena_unmapped"`
}

func buildYAMLDoc(f *athenaconf.File, manifest *athenaconf.Manifest, cfg *config.Config) yamlDoc {
	var doc yamlDoc
	doc.RathenaUnmapped = map[string]string{}
	doc.Identity.UseMD5Passwords = cfg.Identity.UseMD5Passwords
	doc.Identity.MaxChars = cfg.Identity.MaxChars

	for _, k := range manifest.Unmapped {
		if v, ok := f.Keys[k]; ok {
			doc.RathenaUnmapped[k] = v.AsString()
		}
	}
	return doc
}

func writeYAML(out string, doc yamlDoc) error {
	if dir := filepath.Dir(out); dir != "" && dir != "." {
		//nolint:gosec // output dir is operator-supplied by design
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}
	body, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshal yaml: %w", err)
	}
	header := strings.Join([]string{
		"# Generated by import-conf from rAthena conf/. Do not edit by hand.",
		"# Merge into config.yaml with `yq` or by hand; unmapped keys are",
		"# preserved under rathena_unmapped: for visibility (decision D-008).",
		"",
	}, "\n")
	//nolint:gosec // output path is operator-supplied by design
	if err := os.WriteFile(out, []byte(header+string(body)), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	return nil
}

func printUsage() {
	fmt.Fprintln(os.Stderr, "usage: import-conf [--src <dir>] [--out <file>] [--root <rAthena-root>]")
	fmt.Fprintln(os.Stderr, "  --src  source conf dir (default: third_party/rathena/conf)")
	fmt.Fprintln(os.Stderr, "  --out  output yaml file (default: config.rathena.yaml)")
	fmt.Fprintln(os.Stderr, "  --root rAthena checkout root for resolving import: paths")
}
