//go:build unit

package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestRun_FlagDefaults(t *testing.T) {
	// Parse args with none provided; expect defaults to populate src/out/root.
	src, out, root, err := parseFlags(nil)
	require.NoError(t, err)
	assert.Equal(t, defaultSrc, src)
	assert.Equal(t, defaultOut, out)
	assert.NotEmpty(t, root, "root should default to something")
}

func TestRun_CustomFlags(t *testing.T) {
	src, out, root, err := parseFlags([]string{
		"--src", "/tmp/src",
		"--out", "/tmp/out.yaml",
		"--root", "/tmp/root",
	})
	require.NoError(t, err)
	assert.Equal(t, "/tmp/src", src)
	assert.Equal(t, "/tmp/out.yaml", out)
	assert.Equal(t, "/tmp/root", root)
}

func TestRun_UnknownFlag(t *testing.T) {
	_, _, _, err := parseFlags([]string{"--bogus"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unknown")
}

func TestRun_MissingFlagValue(t *testing.T) {
	_, _, _, err := parseFlags([]string{"--src"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "requires a value")
}

func TestRun_WritesYAMLOutput(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.Mkdir(filepath.Join(dir, "conf"), 0o700))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "conf", "login_athena.conf"),
		[]byte("use_MD5_passwords: yes\nchars_per_account: 9\nsome_unknown: 42\n"), 0o600))

	out := filepath.Join(dir, "out.yaml")
	exit := Run([]string{
		"--src", filepath.Join(dir, "conf"),
		"--out", out,
		"--root", dir,
	})
	assert.Equal(t, 0, exit)

	body, err := os.ReadFile(out)
	require.NoError(t, err)
	text := string(body)
	assert.True(t, strings.HasPrefix(text, "# Generated by import-conf"),
		"output should start with header, got: %q", text[:min(80, len(text))])
	assert.Contains(t, text, "use_md5_passwords: true")
	assert.Contains(t, text, "max_chars: 9")
	assert.Contains(t, text, `some_unknown: "42"`)

	// Round-trip parse to verify the YAML is well-formed.
	var doc yamlDoc
	require.NoError(t, yaml.Unmarshal(body, &doc))
	assert.True(t, doc.Identity.UseMD5Passwords)
	assert.Equal(t, 9, doc.Identity.MaxChars)
	assert.Equal(t, "42", doc.RathenaUnmapped["some_unknown"])
}

func TestRun_BadSrc(t *testing.T) {
	exit := Run([]string{
		"--src", "/no/such/path",
		"--out", filepath.Join(t.TempDir(), "out.yaml"),
	})
	assert.NotEqual(t, 0, exit)
}

func TestRun_HelpFlag(t *testing.T) {
	// Both -h and --help must return exit code 0 via errHelp without
	// calling os.Exit (which would terminate the test process).
	assert.Equal(t, 0, Run([]string{"-h"}))
	assert.Equal(t, 0, Run([]string{"--help"}))
}

func TestParseFlags_HelpReturnsErrHelp(t *testing.T) {
	_, _, _, err := parseFlags([]string{"-h"})
	assert.True(t, errors.Is(err, errHelp), "expected errHelp, got %v", err)
	_, _, _, err = parseFlags([]string{"--help"})
	assert.True(t, errors.Is(err, errHelp), "expected errHelp, got %v", err)
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
