// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/vending/domain (interfaces: VendingRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/vending_repository_mock.go -package=domainmock . VendingRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/vending/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVendingRepository is a mock of VendingRepository interface.
type MockVendingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVendingRepositoryMockRecorder
	isgomock struct{}
}

// MockVendingRepositoryMockRecorder is the mock recorder for MockVendingRepository.
type MockVendingRepositoryMockRecorder struct {
	mock *MockVendingRepository
}

// NewMockVendingRepository creates a new mock instance.
func NewMockVendingRepository(ctrl *gomock.Controller) *MockVendingRepository {
	mock := &MockVendingRepository{ctrl: ctrl}
	mock.recorder = &MockVendingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendingRepository) EXPECT() *MockVendingRepositoryMockRecorder {
	return m.recorder
}

// CreateShop mocks base method.
func (m *MockVendingRepository) CreateShop(ctx context.Context, shop domain.VendingShop) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShop", ctx, shop)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShop indicates an expected call of CreateShop.
func (mr *MockVendingRepositoryMockRecorder) CreateShop(ctx, shop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShop", reflect.TypeOf((*MockVendingRepository)(nil).CreateShop), ctx, shop)
}

// DeleteShop mocks base method.
func (m *MockVendingRepository) DeleteShop(ctx context.Context, shopID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShop", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShop indicates an expected call of DeleteShop.
func (mr *MockVendingRepositoryMockRecorder) DeleteShop(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShop", reflect.TypeOf((*MockVendingRepository)(nil).DeleteShop), ctx, shopID)
}

// GetShop mocks base method.
func (m *MockVendingRepository) GetShop(ctx context.Context, shopID string) (domain.VendingShop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShop", ctx, shopID)
	ret0, _ := ret[0].(domain.VendingShop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShop indicates an expected call of GetShop.
func (mr *MockVendingRepositoryMockRecorder) GetShop(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShop", reflect.TypeOf((*MockVendingRepository)(nil).GetShop), ctx, shopID)
}

// GetShopByOwner mocks base method.
func (m *MockVendingRepository) GetShopByOwner(ctx context.Context, ownerID uint32) (domain.VendingShop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopByOwner", ctx, ownerID)
	ret0, _ := ret[0].(domain.VendingShop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByOwner indicates an expected call of GetShopByOwner.
func (mr *MockVendingRepositoryMockRecorder) GetShopByOwner(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByOwner", reflect.TypeOf((*MockVendingRepository)(nil).GetShopByOwner), ctx, ownerID)
}

// ListShopsOnMap mocks base method.
func (m *MockVendingRepository) ListShopsOnMap(ctx context.Context, mapName string) ([]domain.VendingShop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopsOnMap", ctx, mapName)
	ret0, _ := ret[0].([]domain.VendingShop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShopsOnMap indicates an expected call of ListShopsOnMap.
func (mr *MockVendingRepositoryMockRecorder) ListShopsOnMap(ctx, mapName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopsOnMap", reflect.TypeOf((*MockVendingRepository)(nil).ListShopsOnMap), ctx, mapName)
}

// UpdateShop mocks base method.
func (m *MockVendingRepository) UpdateShop(ctx context.Context, shop domain.VendingShop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShop", ctx, shop)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShop indicates an expected call of UpdateShop.
func (mr *MockVendingRepositoryMockRecorder) UpdateShop(ctx, shop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShop", reflect.TypeOf((*MockVendingRepository)(nil).UpdateShop), ctx, shop)
}
