-- Wave 2: rAthena `char` table (sql-files/main.sql, Thai Classic).
-- PostgreSQL version. `"int"` and `"rename"` double-quoted (reserved words in
-- PG). No unsigned types (PG has none). tinyint→smallint, mediumint→integer.
CREATE TABLE IF NOT EXISTS "char" (
  "char_id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL DEFAULT 0,
  "char_num" smallint NOT NULL DEFAULT 0,
  "name" varchar(30) NOT NULL DEFAULT '',
  "class" smallint NOT NULL DEFAULT 0,
  "base_level" smallint NOT NULL DEFAULT 1,
  "job_level" smallint NOT NULL DEFAULT 1,
  "base_exp" bigint NOT NULL DEFAULT 0,
  "job_exp" bigint NOT NULL DEFAULT 0,
  "zeny" integer NOT NULL DEFAULT 0,
  "str" smallint NOT NULL DEFAULT 0,
  "agi" smallint NOT NULL DEFAULT 0,
  "vit" smallint NOT NULL DEFAULT 0,
  "int" smallint NOT NULL DEFAULT 0,
  "dex" smallint NOT NULL DEFAULT 0,
  "luk" smallint NOT NULL DEFAULT 0,
  "max_hp" integer NOT NULL DEFAULT 0,
  "hp" integer NOT NULL DEFAULT 0,
  "max_sp" integer NOT NULL DEFAULT 0,
  "sp" integer NOT NULL DEFAULT 0,
  "status_point" integer NOT NULL DEFAULT 0,
  "skill_point" integer NOT NULL DEFAULT 0,
  "option" integer NOT NULL DEFAULT 0,
  "sex" smallint NOT NULL DEFAULT 0,
  "hair" smallint NOT NULL DEFAULT 0,
  "hair_color" smallint NOT NULL DEFAULT 0,
  "clothes_color" smallint NOT NULL DEFAULT 0,
  "body" smallint NOT NULL DEFAULT 0,
  "weapon" smallint NOT NULL DEFAULT 0,
  "shield" smallint NOT NULL DEFAULT 0,
  "head_top" smallint NOT NULL DEFAULT 0,
  "head_mid" smallint NOT NULL DEFAULT 0,
  "head_bottom" smallint NOT NULL DEFAULT 0,
  "last_map" varchar(11) NOT NULL DEFAULT '',
  "last_x" smallint NOT NULL DEFAULT 53,
  "last_y" smallint NOT NULL DEFAULT 111,
  "save_map" varchar(11) NOT NULL DEFAULT '',
  "save_x" smallint NOT NULL DEFAULT 53,
  "save_y" smallint NOT NULL DEFAULT 111,
  "partner_id" integer NOT NULL DEFAULT 0,
  "online" smallint NOT NULL DEFAULT 0,
  "father" integer NOT NULL DEFAULT 0,
  "mother" integer NOT NULL DEFAULT 0,
  "child" integer NOT NULL DEFAULT 0,
  "fame" integer NOT NULL DEFAULT 0,
  "rename" smallint NOT NULL DEFAULT 0,
  "delete_date" integer NOT NULL DEFAULT 0,
  "moves" integer NOT NULL DEFAULT 0,
  "unban" integer NOT NULL DEFAULT 0,
  "hotkey" smallint NOT NULL DEFAULT 0,
  "clan_id" integer NOT NULL DEFAULT 0,
  "title_id" integer NOT NULL DEFAULT 0,
  "last_login" timestamp DEFAULT NULL,
  UNIQUE ("name")
);
CREATE INDEX IF NOT EXISTS "char_account_id_idx" ON "char" ("account_id");
