apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goathena
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-rate-limit@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.goathena.local
      secretName: goathena-tls
  rules:
    - host: api.goathena.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity
                port:
                  number: 8080
