// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/zone/domain (interfaces: ZoneService)
//
// Generated by this command:
//
//	mockgen -destination=mock/zone_service_mock.go -package=domainmock . ZoneService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/zone/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockZoneService is a mock of ZoneService interface.
type MockZoneService struct {
	ctrl     *gomock.Controller
	recorder *MockZoneServiceMockRecorder
	isgomock struct{}
}

// MockZoneServiceMockRecorder is the mock recorder for MockZoneService.
type MockZoneServiceMockRecorder struct {
	mock *MockZoneService
}

// NewMockZoneService creates a new mock instance.
func NewMockZoneService(ctrl *gomock.Controller) *MockZoneService {
	mock := &MockZoneService{ctrl: ctrl}
	mock.recorder = &MockZoneServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZoneService) EXPECT() *MockZoneServiceMockRecorder {
	return m.recorder
}

// AddEntity mocks base method.
func (m *MockZoneService) AddEntity(ctx context.Context, e *domain.Entity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEntity", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntity indicates an expected call of AddEntity.
func (mr *MockZoneServiceMockRecorder) AddEntity(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntity", reflect.TypeOf((*MockZoneService)(nil).AddEntity), ctx, e)
}

// DamageEntity mocks base method.
func (m *MockZoneService) DamageEntity(ctx context.Context, entityID domain.EntityID, damage int32, attackerID domain.EntityID, skillID, skillLevel uint32) (*domain.DamageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DamageEntity", ctx, entityID, damage, attackerID, skillID, skillLevel)
	ret0, _ := ret[0].(*domain.DamageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DamageEntity indicates an expected call of DamageEntity.
func (mr *MockZoneServiceMockRecorder) DamageEntity(ctx, entityID, damage, attackerID, skillID, skillLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DamageEntity", reflect.TypeOf((*MockZoneService)(nil).DamageEntity), ctx, entityID, damage, attackerID, skillID, skillLevel)
}

// EntityCount mocks base method.
func (m *MockZoneService) EntityCount(ctx context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntityCount", ctx)
	ret0, _ := ret[0].(int)
	return ret0
}

// EntityCount indicates an expected call of EntityCount.
func (mr *MockZoneServiceMockRecorder) EntityCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntityCount", reflect.TypeOf((*MockZoneService)(nil).EntityCount), ctx)
}

// GetEntity mocks base method.
func (m *MockZoneService) GetEntity(ctx context.Context, id domain.EntityID) (*domain.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntity", ctx, id)
	ret0, _ := ret[0].(*domain.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntity indicates an expected call of GetEntity.
func (mr *MockZoneServiceMockRecorder) GetEntity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntity", reflect.TypeOf((*MockZoneService)(nil).GetEntity), ctx, id)
}

// GetVisible mocks base method.
func (m *MockZoneService) GetVisible(ctx context.Context, id domain.EntityID) ([]*domain.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisible", ctx, id)
	ret0, _ := ret[0].([]*domain.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisible indicates an expected call of GetVisible.
func (mr *MockZoneServiceMockRecorder) GetVisible(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisible", reflect.TypeOf((*MockZoneService)(nil).GetVisible), ctx, id)
}

// KillEntity mocks base method.
func (m *MockZoneService) KillEntity(ctx context.Context, entityID domain.EntityID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillEntity", ctx, entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillEntity indicates an expected call of KillEntity.
func (mr *MockZoneServiceMockRecorder) KillEntity(ctx, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillEntity", reflect.TypeOf((*MockZoneService)(nil).KillEntity), ctx, entityID)
}

// MoveEntity mocks base method.
func (m *MockZoneService) MoveEntity(ctx context.Context, id domain.EntityID, x, y int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveEntity", ctx, id, x, y)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveEntity indicates an expected call of MoveEntity.
func (mr *MockZoneServiceMockRecorder) MoveEntity(ctx, id, x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveEntity", reflect.TypeOf((*MockZoneService)(nil).MoveEntity), ctx, id, x, y)
}

// PickupItem mocks base method.
func (m *MockZoneService) PickupItem(ctx context.Context, groundItemID, playerID domain.EntityID) (*domain.PickupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickupItem", ctx, groundItemID, playerID)
	ret0, _ := ret[0].(*domain.PickupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickupItem indicates an expected call of PickupItem.
func (mr *MockZoneServiceMockRecorder) PickupItem(ctx, groundItemID, playerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickupItem", reflect.TypeOf((*MockZoneService)(nil).PickupItem), ctx, groundItemID, playerID)
}

// RemoveEntity mocks base method.
func (m *MockZoneService) RemoveEntity(ctx context.Context, id domain.EntityID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEntity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEntity indicates an expected call of RemoveEntity.
func (mr *MockZoneServiceMockRecorder) RemoveEntity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEntity", reflect.TypeOf((*MockZoneService)(nil).RemoveEntity), ctx, id)
}
