// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: zone/v1/event.proto

package zonev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ZoneEvent represents an event occurring within a zone (map).
// These events are broadcast via NATS.
type ZoneEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ZoneEvent_Moved
	//	*ZoneEvent_Spawned
	//	*ZoneEvent_Vanished
	//	*ZoneEvent_Damaged
	//	*ZoneEvent_Killed
	//	*ZoneEvent_Dropped
	//	*ZoneEvent_PickedUp
	Event         isZoneEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneEvent) Reset() {
	*x = ZoneEvent{}
	mi := &file_zone_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneEvent) ProtoMessage() {}

func (x *ZoneEvent) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneEvent.ProtoReflect.Descriptor instead.
func (*ZoneEvent) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneEvent) GetEvent() isZoneEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ZoneEvent) GetMoved() *EntityMoved {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_Moved); ok {
			return x.Moved
		}
	}
	return nil
}

func (x *ZoneEvent) GetSpawned() *EntitySpawned {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_Spawned); ok {
			return x.Spawned
		}
	}
	return nil
}

func (x *ZoneEvent) GetVanished() *EntityVanished {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_Vanished); ok {
			return x.Vanished
		}
	}
	return nil
}

func (x *ZoneEvent) GetDamaged() *EntityDamaged {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_Damaged); ok {
			return x.Damaged
		}
	}
	return nil
}

func (x *ZoneEvent) GetKilled() *EntityKilled {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_Killed); ok {
			return x.Killed
		}
	}
	return nil
}

func (x *ZoneEvent) GetDropped() *ItemDropped {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_Dropped); ok {
			return x.Dropped
		}
	}
	return nil
}

func (x *ZoneEvent) GetPickedUp() *ItemPickedUp {
	if x != nil {
		if x, ok := x.Event.(*ZoneEvent_PickedUp); ok {
			return x.PickedUp
		}
	}
	return nil
}

type isZoneEvent_Event interface {
	isZoneEvent_Event()
}

type ZoneEvent_Moved struct {
	Moved *EntityMoved `protobuf:"bytes,1,opt,name=moved,proto3,oneof"`
}

type ZoneEvent_Spawned struct {
	Spawned *EntitySpawned `protobuf:"bytes,2,opt,name=spawned,proto3,oneof"`
}

type ZoneEvent_Vanished struct {
	Vanished *EntityVanished `protobuf:"bytes,3,opt,name=vanished,proto3,oneof"`
}

type ZoneEvent_Damaged struct {
	Damaged *EntityDamaged `protobuf:"bytes,4,opt,name=damaged,proto3,oneof"` // HP changed (not necessarily death)
}

type ZoneEvent_Killed struct {
	Killed *EntityKilled `protobuf:"bytes,5,opt,name=killed,proto3,oneof"` // Entity died (HP <= 0)
}

type ZoneEvent_Dropped struct {
	Dropped *ItemDropped `protobuf:"bytes,6,opt,name=dropped,proto3,oneof"` // Ground item appeared
}

type ZoneEvent_PickedUp struct {
	PickedUp *ItemPickedUp `protobuf:"bytes,7,opt,name=picked_up,json=pickedUp,proto3,oneof"` // Ground item collected
}

func (*ZoneEvent_Moved) isZoneEvent_Event() {}

func (*ZoneEvent_Spawned) isZoneEvent_Event() {}

func (*ZoneEvent_Vanished) isZoneEvent_Event() {}

func (*ZoneEvent_Damaged) isZoneEvent_Event() {}

func (*ZoneEvent_Killed) isZoneEvent_Event() {}

func (*ZoneEvent_Dropped) isZoneEvent_Event() {}

func (*ZoneEvent_PickedUp) isZoneEvent_Event() {}

// EntityMoved indicates an entity has started moving to a new cell.
type EntityMoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DestX         uint32                 `protobuf:"varint,2,opt,name=dest_x,json=destX,proto3" json:"dest_x,omitempty"`
	DestY         uint32                 `protobuf:"varint,3,opt,name=dest_y,json=destY,proto3" json:"dest_y,omitempty"`
	SrcX          uint32                 `protobuf:"varint,4,opt,name=src_x,json=srcX,proto3" json:"src_x,omitempty"`
	SrcY          uint32                 `protobuf:"varint,5,opt,name=src_y,json=srcY,proto3" json:"src_y,omitempty"`
	MoveStartTime uint64                 `protobuf:"varint,6,opt,name=move_start_time,json=moveStartTime,proto3" json:"move_start_time,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMoved) Reset() {
	*x = EntityMoved{}
	mi := &file_zone_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMoved) ProtoMessage() {}

func (x *EntityMoved) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMoved.ProtoReflect.Descriptor instead.
func (*EntityMoved) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EntityMoved) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityMoved) GetDestX() uint32 {
	if x != nil {
		return x.DestX
	}
	return 0
}

func (x *EntityMoved) GetDestY() uint32 {
	if x != nil {
		return x.DestY
	}
	return 0
}

func (x *EntityMoved) GetSrcX() uint32 {
	if x != nil {
		return x.SrcX
	}
	return 0
}

func (x *EntityMoved) GetSrcY() uint32 {
	if x != nil {
		return x.SrcY
	}
	return 0
}

func (x *EntityMoved) GetMoveStartTime() uint64 {
	if x != nil {
		return x.MoveStartTime
	}
	return 0
}

// EntitySpawned indicates an entity appeared in the map.
type EntitySpawned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    uint32                 `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // Matches domain.EntityType
	X             uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySpawned) Reset() {
	*x = EntitySpawned{}
	mi := &file_zone_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySpawned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySpawned) ProtoMessage() {}

func (x *EntitySpawned) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySpawned.ProtoReflect.Descriptor instead.
func (*EntitySpawned) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *EntitySpawned) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntitySpawned) GetEntityType() uint32 {
	if x != nil {
		return x.EntityType
	}
	return 0
}

func (x *EntitySpawned) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntitySpawned) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntitySpawned) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// EntityVanished indicates an entity disappeared from the map.
type EntityVanished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 0=out of sight, 1=logged out, 2=teleported, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityVanished) Reset() {
	*x = EntityVanished{}
	mi := &file_zone_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityVanished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityVanished) ProtoMessage() {}

func (x *EntityVanished) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityVanished.ProtoReflect.Descriptor instead.
func (*EntityVanished) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *EntityVanished) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityVanished) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// EntityDamaged indicates an entity's HP changed (not necessarily death).
type EntityDamaged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Damage        int32                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	NewHp         int32                  `protobuf:"varint,3,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDamaged) Reset() {
	*x = EntityDamaged{}
	mi := &file_zone_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDamaged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDamaged) ProtoMessage() {}

func (x *EntityDamaged) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDamaged.ProtoReflect.Descriptor instead.
func (*EntityDamaged) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *EntityDamaged) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityDamaged) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *EntityDamaged) GetNewHp() int32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

func (x *EntityDamaged) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

// EntityKilled indicates an entity died (HP <= 0).
type EntityKilled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DamageDealt   int32                  `protobuf:"varint,2,opt,name=damage_dealt,json=damageDealt,proto3" json:"damage_dealt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityKilled) Reset() {
	*x = EntityKilled{}
	mi := &file_zone_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityKilled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityKilled) ProtoMessage() {}

func (x *EntityKilled) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityKilled.ProtoReflect.Descriptor instead.
func (*EntityKilled) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *EntityKilled) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityKilled) GetDamageDealt() int32 {
	if x != nil {
		return x.DamageDealt
	}
	return 0
}

// ItemDropped indicates a ground item appeared on the map.
type ItemDropped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundItemId  uint32                 `protobuf:"varint,1,opt,name=ground_item_id,json=groundItemId,proto3" json:"ground_item_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // numeric item ID
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`               // stack amount
	X             uint32                 `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	MapName       string                 `protobuf:"bytes,6,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDropped) Reset() {
	*x = ItemDropped{}
	mi := &file_zone_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDropped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDropped) ProtoMessage() {}

func (x *ItemDropped) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDropped.ProtoReflect.Descriptor instead.
func (*ItemDropped) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *ItemDropped) GetGroundItemId() uint32 {
	if x != nil {
		return x.GroundItemId
	}
	return 0
}

func (x *ItemDropped) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemDropped) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ItemDropped) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemDropped) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ItemDropped) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

// ItemPickedUp indicates a ground item was collected by a player.
type ItemPickedUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundItemId  uint32                 `protobuf:"varint,1,opt,name=ground_item_id,json=groundItemId,proto3" json:"ground_item_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // entity ID of player who picked it up
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemPickedUp) Reset() {
	*x = ItemPickedUp{}
	mi := &file_zone_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemPickedUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPickedUp) ProtoMessage() {}

func (x *ItemPickedUp) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPickedUp.ProtoReflect.Descriptor instead.
func (*ItemPickedUp) Descriptor() ([]byte, []int) {
	return file_zone_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *ItemPickedUp) GetGroundItemId() uint32 {
	if x != nil {
		return x.GroundItemId
	}
	return 0
}

func (x *ItemPickedUp) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemPickedUp) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ItemPickedUp) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_zone_v1_event_proto protoreflect.FileDescriptor

const file_zone_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x13zone/v1/event.proto\x12\azone.v1\"\xfa\x02\n" +
	"\tZoneEvent\x12,\n" +
	"\x05moved\x18\x01 \x01(\v2\x14.zone.v1.EntityMovedH\x00R\x05moved\x122\n" +
	"\aspawned\x18\x02 \x01(\v2\x16.zone.v1.EntitySpawnedH\x00R\aspawned\x125\n" +
	"\bvanished\x18\x03 \x01(\v2\x17.zone.v1.EntityVanishedH\x00R\bvanished\x122\n" +
	"\adamaged\x18\x04 \x01(\v2\x16.zone.v1.EntityDamagedH\x00R\adamaged\x12/\n" +
	"\x06killed\x18\x05 \x01(\v2\x15.zone.v1.EntityKilledH\x00R\x06killed\x120\n" +
	"\adropped\x18\x06 \x01(\v2\x14.zone.v1.ItemDroppedH\x00R\adropped\x124\n" +
	"\tpicked_up\x18\a \x01(\v2\x15.zone.v1.ItemPickedUpH\x00R\bpickedUpB\a\n" +
	"\x05event\"\xaa\x01\n" +
	"\vEntityMoved\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x15\n" +
	"\x06dest_x\x18\x02 \x01(\rR\x05destX\x12\x15\n" +
	"\x06dest_y\x18\x03 \x01(\rR\x05destY\x12\x13\n" +
	"\x05src_x\x18\x04 \x01(\rR\x04srcX\x12\x13\n" +
	"\x05src_y\x18\x05 \x01(\rR\x04srcY\x12&\n" +
	"\x0fmove_start_time\x18\x06 \x01(\x04R\rmoveStartTime\"}\n" +
	"\rEntitySpawned\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\rR\n" +
	"entityType\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"A\n" +
	"\x0eEntityVanished\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\"r\n" +
	"\rEntityDamaged\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x05R\x06damage\x12\x15\n" +
	"\x06new_hp\x18\x03 \x01(\x05R\x05newHp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\"N\n" +
	"\fEntityKilled\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12!\n" +
	"\fdamage_dealt\x18\x02 \x01(\x05R\vdamageDealt\"\x9b\x01\n" +
	"\vItemDropped\x12$\n" +
	"\x0eground_item_id\x18\x01 \x01(\rR\fgroundItemId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\f\n" +
	"\x01x\x18\x04 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\rR\x01y\x12\x19\n" +
	"\bmap_name\x18\x06 \x01(\tR\amapName\"\x82\x01\n" +
	"\fItemPickedUp\x12$\n" +
	"\x0eground_item_id\x18\x01 \x01(\rR\fgroundItemId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\rR\bplayerIdB2Z0github.com/bouroo/goAthena/api/pb/zone/v1;zonev1b\x06proto3"

var (
	file_zone_v1_event_proto_rawDescOnce sync.Once
	file_zone_v1_event_proto_rawDescData []byte
)

func file_zone_v1_event_proto_rawDescGZIP() []byte {
	file_zone_v1_event_proto_rawDescOnce.Do(func() {
		file_zone_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zone_v1_event_proto_rawDesc), len(file_zone_v1_event_proto_rawDesc)))
	})
	return file_zone_v1_event_proto_rawDescData
}

var file_zone_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zone_v1_event_proto_goTypes = []any{
	(*ZoneEvent)(nil),      // 0: zone.v1.ZoneEvent
	(*EntityMoved)(nil),    // 1: zone.v1.EntityMoved
	(*EntitySpawned)(nil),  // 2: zone.v1.EntitySpawned
	(*EntityVanished)(nil), // 3: zone.v1.EntityVanished
	(*EntityDamaged)(nil),  // 4: zone.v1.EntityDamaged
	(*EntityKilled)(nil),   // 5: zone.v1.EntityKilled
	(*ItemDropped)(nil),    // 6: zone.v1.ItemDropped
	(*ItemPickedUp)(nil),   // 7: zone.v1.ItemPickedUp
}
var file_zone_v1_event_proto_depIdxs = []int32{
	1, // 0: zone.v1.ZoneEvent.moved:type_name -> zone.v1.EntityMoved
	2, // 1: zone.v1.ZoneEvent.spawned:type_name -> zone.v1.EntitySpawned
	3, // 2: zone.v1.ZoneEvent.vanished:type_name -> zone.v1.EntityVanished
	4, // 3: zone.v1.ZoneEvent.damaged:type_name -> zone.v1.EntityDamaged
	5, // 4: zone.v1.ZoneEvent.killed:type_name -> zone.v1.EntityKilled
	6, // 5: zone.v1.ZoneEvent.dropped:type_name -> zone.v1.ItemDropped
	7, // 6: zone.v1.ZoneEvent.picked_up:type_name -> zone.v1.ItemPickedUp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_zone_v1_event_proto_init() }
func file_zone_v1_event_proto_init() {
	if File_zone_v1_event_proto != nil {
		return
	}
	file_zone_v1_event_proto_msgTypes[0].OneofWrappers = []any{
		(*ZoneEvent_Moved)(nil),
		(*ZoneEvent_Spawned)(nil),
		(*ZoneEvent_Vanished)(nil),
		(*ZoneEvent_Damaged)(nil),
		(*ZoneEvent_Killed)(nil),
		(*ZoneEvent_Dropped)(nil),
		(*ZoneEvent_PickedUp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zone_v1_event_proto_rawDesc), len(file_zone_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zone_v1_event_proto_goTypes,
		DependencyIndexes: file_zone_v1_event_proto_depIdxs,
		MessageInfos:      file_zone_v1_event_proto_msgTypes,
	}.Build()
	File_zone_v1_event_proto = out.File
	file_zone_v1_event_proto_goTypes = nil
	file_zone_v1_event_proto_depIdxs = nil
}
