// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: zone/v1/zone.proto

package zonev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnterZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	LoginId1      uint64                 `protobuf:"fixed64,3,opt,name=login_id1,json=loginId1,proto3" json:"login_id1,omitempty"` // from identity.Authenticate
	ClientTick    uint32                 `protobuf:"varint,4,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	Sex           string                 `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Packetver     uint32                 `protobuf:"varint,6,opt,name=packetver,proto3" json:"packetver,omitempty"`
	ClientIp      string                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterZoneRequest) Reset() {
	*x = EnterZoneRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterZoneRequest) ProtoMessage() {}

func (x *EnterZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterZoneRequest.ProtoReflect.Descriptor instead.
func (*EnterZoneRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{0}
}

func (x *EnterZoneRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *EnterZoneRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *EnterZoneRequest) GetLoginId1() uint64 {
	if x != nil {
		return x.LoginId1
	}
	return 0
}

func (x *EnterZoneRequest) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *EnterZoneRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *EnterZoneRequest) GetPacketver() uint32 {
	if x != nil {
		return x.Packetver
	}
	return 0
}

func (x *EnterZoneRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type EnterZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MapName       string                 `protobuf:"bytes,2,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MapX          uint32                 `protobuf:"varint,3,opt,name=map_x,json=mapX,proto3" json:"map_x,omitempty"`
	MapY          uint32                 `protobuf:"varint,4,opt,name=map_y,json=mapY,proto3" json:"map_y,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // human-readable error when success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterZoneResponse) Reset() {
	*x = EnterZoneResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterZoneResponse) ProtoMessage() {}

func (x *EnterZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterZoneResponse.ProtoReflect.Descriptor instead.
func (*EnterZoneResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{1}
}

func (x *EnterZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnterZoneResponse) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *EnterZoneResponse) GetMapX() uint32 {
	if x != nil {
		return x.MapX
	}
	return 0
}

func (x *EnterZoneResponse) GetMapY() uint32 {
	if x != nil {
		return x.MapY
	}
	return 0
}

func (x *EnterZoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MoveEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DestX         uint32                 `protobuf:"varint,2,opt,name=dest_x,json=destX,proto3" json:"dest_x,omitempty"` // destination cell X
	DestY         uint32                 `protobuf:"varint,3,opt,name=dest_y,json=destY,proto3" json:"dest_y,omitempty"` // destination cell Y
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveEntityRequest) Reset() {
	*x = MoveEntityRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntityRequest) ProtoMessage() {}

func (x *MoveEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntityRequest.ProtoReflect.Descriptor instead.
func (*MoveEntityRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{2}
}

func (x *MoveEntityRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *MoveEntityRequest) GetDestX() uint32 {
	if x != nil {
		return x.DestX
	}
	return 0
}

func (x *MoveEntityRequest) GetDestY() uint32 {
	if x != nil {
		return x.DestY
	}
	return 0
}

type MoveEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SrcX          uint32                 `protobuf:"varint,2,opt,name=src_x,json=srcX,proto3" json:"src_x,omitempty"` // cell the move started from
	SrcY          uint32                 `protobuf:"varint,3,opt,name=src_y,json=srcY,proto3" json:"src_y,omitempty"`
	DestX         uint32                 `protobuf:"varint,4,opt,name=dest_x,json=destX,proto3" json:"dest_x,omitempty"` // cell the path targets (echoed back)
	DestY         uint32                 `protobuf:"varint,5,opt,name=dest_y,json=destY,proto3" json:"dest_y,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // human-readable error when success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveEntityResponse) Reset() {
	*x = MoveEntityResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntityResponse) ProtoMessage() {}

func (x *MoveEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntityResponse.ProtoReflect.Descriptor instead.
func (*MoveEntityResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{3}
}

func (x *MoveEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveEntityResponse) GetSrcX() uint32 {
	if x != nil {
		return x.SrcX
	}
	return 0
}

func (x *MoveEntityResponse) GetSrcY() uint32 {
	if x != nil {
		return x.SrcY
	}
	return 0
}

func (x *MoveEntityResponse) GetDestX() uint32 {
	if x != nil {
		return x.DestX
	}
	return 0
}

func (x *MoveEntityResponse) GetDestY() uint32 {
	if x != nil {
		return x.DestY
	}
	return 0
}

func (x *MoveEntityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AttackEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // target entity ID
	Damage        uint32                 `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`                           // damage to apply (optional; defaults to 1)
	AttackerId    uint32                 `protobuf:"varint,3,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"` // source entity ID (player/GM)
	SkillId       uint32                 `protobuf:"varint,4,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`          // skill ID used (0 for auto-attack)
	SkillLevel    uint32                 `protobuf:"varint,5,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"` // skill level (0 if skill_id == 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEntityRequest) Reset() {
	*x = AttackEntityRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEntityRequest) ProtoMessage() {}

func (x *AttackEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEntityRequest.ProtoReflect.Descriptor instead.
func (*AttackEntityRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{4}
}

func (x *AttackEntityRequest) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *AttackEntityRequest) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *AttackEntityRequest) GetAttackerId() uint32 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *AttackEntityRequest) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *AttackEntityRequest) GetSkillLevel() uint32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

type AttackEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TargetDied    bool                   `protobuf:"varint,2,opt,name=target_died,json=targetDied,proto3" json:"target_died,omitempty"`          // true if entity HP <= 0
	DamageApplied int32                  `protobuf:"varint,3,opt,name=damage_applied,json=damageApplied,proto3" json:"damage_applied,omitempty"` // damage actually applied
	CurrentHp     int32                  `protobuf:"varint,4,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`             // target's HP after damage
	MaxHp         int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`                         // target's MaxHP (unchanged)
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                       // human-readable error if success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEntityResponse) Reset() {
	*x = AttackEntityResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEntityResponse) ProtoMessage() {}

func (x *AttackEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEntityResponse.ProtoReflect.Descriptor instead.
func (*AttackEntityResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{5}
}

func (x *AttackEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttackEntityResponse) GetTargetDied() bool {
	if x != nil {
		return x.TargetDied
	}
	return false
}

func (x *AttackEntityResponse) GetDamageApplied() int32 {
	if x != nil {
		return x.DamageApplied
	}
	return 0
}

func (x *AttackEntityResponse) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *AttackEntityResponse) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *AttackEntityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PickupItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundItemId  uint32                 `protobuf:"varint,1,opt,name=ground_item_id,json=groundItemId,proto3" json:"ground_item_id,omitempty"` // ground item ID
	PlayerId      uint32                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`               // requesting player entity ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupItemRequest) Reset() {
	*x = PickupItemRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupItemRequest) ProtoMessage() {}

func (x *PickupItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupItemRequest.ProtoReflect.Descriptor instead.
func (*PickupItemRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{6}
}

func (x *PickupItemRequest) GetGroundItemId() uint32 {
	if x != nil {
		return x.GroundItemId
	}
	return 0
}

func (x *PickupItemRequest) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PickupItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // numeric item ID
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`               // item amount (typically 1)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                  // human-readable error if success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupItemResponse) Reset() {
	*x = PickupItemResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupItemResponse) ProtoMessage() {}

func (x *PickupItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupItemResponse.ProtoReflect.Descriptor instead.
func (*PickupItemResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{7}
}

func (x *PickupItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PickupItemResponse) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PickupItemResponse) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PickupItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_zone_v1_zone_proto protoreflect.FileDescriptor

const file_zone_v1_zone_proto_rawDesc = "" +
	"\n" +
	"\x12zone/v1/zone.proto\x12\azone.v1\"\xd5\x01\n" +
	"\x10EnterZoneRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x1b\n" +
	"\tlogin_id1\x18\x03 \x01(\x06R\bloginId1\x12\x1f\n" +
	"\vclient_tick\x18\x04 \x01(\rR\n" +
	"clientTick\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\tR\x03sex\x12\x1c\n" +
	"\tpacketver\x18\x06 \x01(\rR\tpacketver\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\"\x88\x01\n" +
	"\x11EnterZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bmap_name\x18\x02 \x01(\tR\amapName\x12\x13\n" +
	"\x05map_x\x18\x03 \x01(\rR\x04mapX\x12\x13\n" +
	"\x05map_y\x18\x04 \x01(\rR\x04mapY\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"`\n" +
	"\x11MoveEntityRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x15\n" +
	"\x06dest_x\x18\x02 \x01(\rR\x05destX\x12\x15\n" +
	"\x06dest_y\x18\x03 \x01(\rR\x05destY\"\x9c\x01\n" +
	"\x12MoveEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05src_x\x18\x02 \x01(\rR\x04srcX\x12\x13\n" +
	"\x05src_y\x18\x03 \x01(\rR\x04srcY\x12\x15\n" +
	"\x06dest_x\x18\x04 \x01(\rR\x05destX\x12\x15\n" +
	"\x06dest_y\x18\x05 \x01(\rR\x05destY\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x13AttackEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\rR\x06damage\x12\x1f\n" +
	"\vattacker_id\x18\x03 \x01(\rR\n" +
	"attackerId\x12\x19\n" +
	"\bskill_id\x18\x04 \x01(\rR\askillId\x12\x1f\n" +
	"\vskill_level\x18\x05 \x01(\rR\n" +
	"skillLevel\"\xc4\x01\n" +
	"\x14AttackEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtarget_died\x18\x02 \x01(\bR\n" +
	"targetDied\x12%\n" +
	"\x0edamage_applied\x18\x03 \x01(\x05R\rdamageApplied\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x04 \x01(\x05R\tcurrentHp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"V\n" +
	"\x11PickupItemRequest\x12$\n" +
	"\x0eground_item_id\x18\x01 \x01(\rR\fgroundItemId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\rR\bplayerId\"u\n" +
	"\x12PickupItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xac\x02\n" +
	"\vZoneService\x12B\n" +
	"\tEnterZone\x12\x19.zone.v1.EnterZoneRequest\x1a\x1a.zone.v1.EnterZoneResponse\x12E\n" +
	"\n" +
	"MoveEntity\x12\x1a.zone.v1.MoveEntityRequest\x1a\x1b.zone.v1.MoveEntityResponse\x12K\n" +
	"\fAttackEntity\x12\x1c.zone.v1.AttackEntityRequest\x1a\x1d.zone.v1.AttackEntityResponse\x12E\n" +
	"\n" +
	"PickupItem\x12\x1a.zone.v1.PickupItemRequest\x1a\x1b.zone.v1.PickupItemResponseB2Z0github.com/bouroo/goAthena/api/pb/zone/v1;zonev1b\x06proto3"

var (
	file_zone_v1_zone_proto_rawDescOnce sync.Once
	file_zone_v1_zone_proto_rawDescData []byte
)

func file_zone_v1_zone_proto_rawDescGZIP() []byte {
	file_zone_v1_zone_proto_rawDescOnce.Do(func() {
		file_zone_v1_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zone_v1_zone_proto_rawDesc), len(file_zone_v1_zone_proto_rawDesc)))
	})
	return file_zone_v1_zone_proto_rawDescData
}

var file_zone_v1_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zone_v1_zone_proto_goTypes = []any{
	(*EnterZoneRequest)(nil),     // 0: zone.v1.EnterZoneRequest
	(*EnterZoneResponse)(nil),    // 1: zone.v1.EnterZoneResponse
	(*MoveEntityRequest)(nil),    // 2: zone.v1.MoveEntityRequest
	(*MoveEntityResponse)(nil),   // 3: zone.v1.MoveEntityResponse
	(*AttackEntityRequest)(nil),  // 4: zone.v1.AttackEntityRequest
	(*AttackEntityResponse)(nil), // 5: zone.v1.AttackEntityResponse
	(*PickupItemRequest)(nil),    // 6: zone.v1.PickupItemRequest
	(*PickupItemResponse)(nil),   // 7: zone.v1.PickupItemResponse
}
var file_zone_v1_zone_proto_depIdxs = []int32{
	0, // 0: zone.v1.ZoneService.EnterZone:input_type -> zone.v1.EnterZoneRequest
	2, // 1: zone.v1.ZoneService.MoveEntity:input_type -> zone.v1.MoveEntityRequest
	4, // 2: zone.v1.ZoneService.AttackEntity:input_type -> zone.v1.AttackEntityRequest
	6, // 3: zone.v1.ZoneService.PickupItem:input_type -> zone.v1.PickupItemRequest
	1, // 4: zone.v1.ZoneService.EnterZone:output_type -> zone.v1.EnterZoneResponse
	3, // 5: zone.v1.ZoneService.MoveEntity:output_type -> zone.v1.MoveEntityResponse
	5, // 6: zone.v1.ZoneService.AttackEntity:output_type -> zone.v1.AttackEntityResponse
	7, // 7: zone.v1.ZoneService.PickupItem:output_type -> zone.v1.PickupItemResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zone_v1_zone_proto_init() }
func file_zone_v1_zone_proto_init() {
	if File_zone_v1_zone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zone_v1_zone_proto_rawDesc), len(file_zone_v1_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zone_v1_zone_proto_goTypes,
		DependencyIndexes: file_zone_v1_zone_proto_depIdxs,
		MessageInfos:      file_zone_v1_zone_proto_msgTypes,
	}.Build()
	File_zone_v1_zone_proto = out.File
	file_zone_v1_zone_proto_goTypes = nil
	file_zone_v1_zone_proto_depIdxs = nil
}
