// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: zone/v1/zone.proto

package zonev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZoneService_EnterZone_FullMethodName     = "/zone.v1.ZoneService/EnterZone"
	ZoneService_MoveEntity_FullMethodName    = "/zone.v1.ZoneService/MoveEntity"
	ZoneService_AttackEntity_FullMethodName  = "/zone.v1.ZoneService/AttackEntity"
	ZoneService_PickupItem_FullMethodName    = "/zone.v1.ZoneService/PickupItem"
	ZoneService_RequestTrade_FullMethodName  = "/zone.v1.ZoneService/RequestTrade"
	ZoneService_AddTradeItem_FullMethodName  = "/zone.v1.ZoneService/AddTradeItem"
	ZoneService_AddTradeZeny_FullMethodName  = "/zone.v1.ZoneService/AddTradeZeny"
	ZoneService_ConfirmTrade_FullMethodName  = "/zone.v1.ZoneService/ConfirmTrade"
	ZoneService_CompleteTrade_FullMethodName = "/zone.v1.ZoneService/CompleteTrade"
	ZoneService_CancelTrade_FullMethodName   = "/zone.v1.ZoneService/CancelTrade"
)

// ZoneServiceClient is the client API for ZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ZoneService manages map instances, entity state, and cross-zone transit.
// The gateway forwards decoded map-server packets here.
//
// Map entry reference: rathena/src/map/clif.cpp clif_parse_WantToConnection
type ZoneServiceClient interface {
	// EnterZone processes a client's map-server entry (CZ_ENTER 0x0072 /
	// WantToConnection). Validates the session and assigns the player to a
	// map instance.
	EnterZone(ctx context.Context, in *EnterZoneRequest, opts ...grpc.CallOption) (*EnterZoneResponse, error)
	// MoveEntity processes a client's move-to-cell request (CZ_REQUEST_MOVE
	// 0x0085 / WalkToXY). Computes an A* path on the entity and returns
	// the source position (cell the move started from) plus the
	// destination (cell the path targets). The gateway uses src+dest to
	// encode the broadcast packet ZC_NOTIFY_PLAYERMOVE 0x0087.
	MoveEntity(ctx context.Context, in *MoveEntityRequest, opts ...grpc.CallOption) (*MoveEntityResponse, error)
	// AttackEntity processes a client's attack action (CZ_ACTION_REQUEST
	// 0x0092 / ActionRequest). The zone validates the target entity, computes
	// damage, updates HP, and may kill the entity. The gateway uses the response
	// to encode ZC_NOTIFY_ACT and ZC_NOTIFY_EFFECT packets.
	AttackEntity(ctx context.Context, in *AttackEntityRequest, opts ...grpc.CallOption) (*AttackEntityResponse, error)
	// PickupItem processes a client's ground-item pickup request (CZ_ITEM_PICKUP
	// 0x0092 / ItemPickup). Validates the item exists, is in range, and is
	// pickable. Returns success or error.
	PickupItem(ctx context.Context, in *PickupItemRequest, opts ...grpc.CallOption) (*PickupItemResponse, error)
	// RequestTrade initiates a trade request from one player to another.
	RequestTrade(ctx context.Context, in *RequestTradeRequest, opts ...grpc.CallOption) (*RequestTradeResponse, error)
	// AddTradeItem adds an item to the trade window.
	AddTradeItem(ctx context.Context, in *AddTradeItemRequest, opts ...grpc.CallOption) (*AddTradeItemResponse, error)
	// AddTradeZeny adds zeny to the trade window.
	AddTradeZeny(ctx context.Context, in *AddTradeZenyRequest, opts ...grpc.CallOption) (*AddTradeZenyResponse, error)
	// ConfirmTrade locks the current trade offer (ready state).
	ConfirmTrade(ctx context.Context, in *ConfirmTradeRequest, opts ...grpc.CallOption) (*ConfirmTradeResponse, error)
	// CompleteTrade executes the atomic item/zeny transfer (both parties confirmed).
	CompleteTrade(ctx context.Context, in *CompleteTradeRequest, opts ...grpc.CallOption) (*CompleteTradeResponse, error)
	// CancelTrade aborts the current trade session.
	CancelTrade(ctx context.Context, in *CancelTradeRequest, opts ...grpc.CallOption) (*CancelTradeResponse, error)
}

type zoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneServiceClient(cc grpc.ClientConnInterface) ZoneServiceClient {
	return &zoneServiceClient{cc}
}

func (c *zoneServiceClient) EnterZone(ctx context.Context, in *EnterZoneRequest, opts ...grpc.CallOption) (*EnterZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterZoneResponse)
	err := c.cc.Invoke(ctx, ZoneService_EnterZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) MoveEntity(ctx context.Context, in *MoveEntityRequest, opts ...grpc.CallOption) (*MoveEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveEntityResponse)
	err := c.cc.Invoke(ctx, ZoneService_MoveEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AttackEntity(ctx context.Context, in *AttackEntityRequest, opts ...grpc.CallOption) (*AttackEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttackEntityResponse)
	err := c.cc.Invoke(ctx, ZoneService_AttackEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) PickupItem(ctx context.Context, in *PickupItemRequest, opts ...grpc.CallOption) (*PickupItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickupItemResponse)
	err := c.cc.Invoke(ctx, ZoneService_PickupItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) RequestTrade(ctx context.Context, in *RequestTradeRequest, opts ...grpc.CallOption) (*RequestTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestTradeResponse)
	err := c.cc.Invoke(ctx, ZoneService_RequestTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AddTradeItem(ctx context.Context, in *AddTradeItemRequest, opts ...grpc.CallOption) (*AddTradeItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTradeItemResponse)
	err := c.cc.Invoke(ctx, ZoneService_AddTradeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AddTradeZeny(ctx context.Context, in *AddTradeZenyRequest, opts ...grpc.CallOption) (*AddTradeZenyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTradeZenyResponse)
	err := c.cc.Invoke(ctx, ZoneService_AddTradeZeny_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ConfirmTrade(ctx context.Context, in *ConfirmTradeRequest, opts ...grpc.CallOption) (*ConfirmTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmTradeResponse)
	err := c.cc.Invoke(ctx, ZoneService_ConfirmTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) CompleteTrade(ctx context.Context, in *CompleteTradeRequest, opts ...grpc.CallOption) (*CompleteTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTradeResponse)
	err := c.cc.Invoke(ctx, ZoneService_CompleteTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) CancelTrade(ctx context.Context, in *CancelTradeRequest, opts ...grpc.CallOption) (*CancelTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTradeResponse)
	err := c.cc.Invoke(ctx, ZoneService_CancelTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneServiceServer is the server API for ZoneService service.
// All implementations must embed UnimplementedZoneServiceServer
// for forward compatibility.
//
// ZoneService manages map instances, entity state, and cross-zone transit.
// The gateway forwards decoded map-server packets here.
//
// Map entry reference: rathena/src/map/clif.cpp clif_parse_WantToConnection
type ZoneServiceServer interface {
	// EnterZone processes a client's map-server entry (CZ_ENTER 0x0072 /
	// WantToConnection). Validates the session and assigns the player to a
	// map instance.
	EnterZone(context.Context, *EnterZoneRequest) (*EnterZoneResponse, error)
	// MoveEntity processes a client's move-to-cell request (CZ_REQUEST_MOVE
	// 0x0085 / WalkToXY). Computes an A* path on the entity and returns
	// the source position (cell the move started from) plus the
	// destination (cell the path targets). The gateway uses src+dest to
	// encode the broadcast packet ZC_NOTIFY_PLAYERMOVE 0x0087.
	MoveEntity(context.Context, *MoveEntityRequest) (*MoveEntityResponse, error)
	// AttackEntity processes a client's attack action (CZ_ACTION_REQUEST
	// 0x0092 / ActionRequest). The zone validates the target entity, computes
	// damage, updates HP, and may kill the entity. The gateway uses the response
	// to encode ZC_NOTIFY_ACT and ZC_NOTIFY_EFFECT packets.
	AttackEntity(context.Context, *AttackEntityRequest) (*AttackEntityResponse, error)
	// PickupItem processes a client's ground-item pickup request (CZ_ITEM_PICKUP
	// 0x0092 / ItemPickup). Validates the item exists, is in range, and is
	// pickable. Returns success or error.
	PickupItem(context.Context, *PickupItemRequest) (*PickupItemResponse, error)
	// RequestTrade initiates a trade request from one player to another.
	RequestTrade(context.Context, *RequestTradeRequest) (*RequestTradeResponse, error)
	// AddTradeItem adds an item to the trade window.
	AddTradeItem(context.Context, *AddTradeItemRequest) (*AddTradeItemResponse, error)
	// AddTradeZeny adds zeny to the trade window.
	AddTradeZeny(context.Context, *AddTradeZenyRequest) (*AddTradeZenyResponse, error)
	// ConfirmTrade locks the current trade offer (ready state).
	ConfirmTrade(context.Context, *ConfirmTradeRequest) (*ConfirmTradeResponse, error)
	// CompleteTrade executes the atomic item/zeny transfer (both parties confirmed).
	CompleteTrade(context.Context, *CompleteTradeRequest) (*CompleteTradeResponse, error)
	// CancelTrade aborts the current trade session.
	CancelTrade(context.Context, *CancelTradeRequest) (*CancelTradeResponse, error)
	mustEmbedUnimplementedZoneServiceServer()
}

// UnimplementedZoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZoneServiceServer struct{}

func (UnimplementedZoneServiceServer) EnterZone(context.Context, *EnterZoneRequest) (*EnterZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnterZone not implemented")
}
func (UnimplementedZoneServiceServer) MoveEntity(context.Context, *MoveEntityRequest) (*MoveEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveEntity not implemented")
}
func (UnimplementedZoneServiceServer) AttackEntity(context.Context, *AttackEntityRequest) (*AttackEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttackEntity not implemented")
}
func (UnimplementedZoneServiceServer) PickupItem(context.Context, *PickupItemRequest) (*PickupItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PickupItem not implemented")
}
func (UnimplementedZoneServiceServer) RequestTrade(context.Context, *RequestTradeRequest) (*RequestTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTrade not implemented")
}
func (UnimplementedZoneServiceServer) AddTradeItem(context.Context, *AddTradeItemRequest) (*AddTradeItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTradeItem not implemented")
}
func (UnimplementedZoneServiceServer) AddTradeZeny(context.Context, *AddTradeZenyRequest) (*AddTradeZenyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTradeZeny not implemented")
}
func (UnimplementedZoneServiceServer) ConfirmTrade(context.Context, *ConfirmTradeRequest) (*ConfirmTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmTrade not implemented")
}
func (UnimplementedZoneServiceServer) CompleteTrade(context.Context, *CompleteTradeRequest) (*CompleteTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTrade not implemented")
}
func (UnimplementedZoneServiceServer) CancelTrade(context.Context, *CancelTradeRequest) (*CancelTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTrade not implemented")
}
func (UnimplementedZoneServiceServer) mustEmbedUnimplementedZoneServiceServer() {}
func (UnimplementedZoneServiceServer) testEmbeddedByValue()                     {}

// UnsafeZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneServiceServer will
// result in compilation errors.
type UnsafeZoneServiceServer interface {
	mustEmbedUnimplementedZoneServiceServer()
}

func RegisterZoneServiceServer(s grpc.ServiceRegistrar, srv ZoneServiceServer) {
	// If the following call panics, it indicates UnimplementedZoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZoneService_ServiceDesc, srv)
}

func _ZoneService_EnterZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).EnterZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_EnterZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).EnterZone(ctx, req.(*EnterZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_MoveEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).MoveEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_MoveEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).MoveEntity(ctx, req.(*MoveEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AttackEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttackEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AttackEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AttackEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AttackEntity(ctx, req.(*AttackEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_PickupItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickupItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).PickupItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_PickupItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).PickupItem(ctx, req.(*PickupItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_RequestTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).RequestTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_RequestTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).RequestTrade(ctx, req.(*RequestTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AddTradeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTradeItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AddTradeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AddTradeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AddTradeItem(ctx, req.(*AddTradeItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AddTradeZeny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTradeZenyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AddTradeZeny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AddTradeZeny_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AddTradeZeny(ctx, req.(*AddTradeZenyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ConfirmTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ConfirmTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_ConfirmTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ConfirmTrade(ctx, req.(*ConfirmTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_CompleteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).CompleteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_CompleteTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).CompleteTrade(ctx, req.(*CompleteTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_CancelTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).CancelTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_CancelTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).CancelTrade(ctx, req.(*CancelTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZoneService_ServiceDesc is the grpc.ServiceDesc for ZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zone.v1.ZoneService",
	HandlerType: (*ZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnterZone",
			Handler:    _ZoneService_EnterZone_Handler,
		},
		{
			MethodName: "MoveEntity",
			Handler:    _ZoneService_MoveEntity_Handler,
		},
		{
			MethodName: "AttackEntity",
			Handler:    _ZoneService_AttackEntity_Handler,
		},
		{
			MethodName: "PickupItem",
			Handler:    _ZoneService_PickupItem_Handler,
		},
		{
			MethodName: "RequestTrade",
			Handler:    _ZoneService_RequestTrade_Handler,
		},
		{
			MethodName: "AddTradeItem",
			Handler:    _ZoneService_AddTradeItem_Handler,
		},
		{
			MethodName: "AddTradeZeny",
			Handler:    _ZoneService_AddTradeZeny_Handler,
		},
		{
			MethodName: "ConfirmTrade",
			Handler:    _ZoneService_ConfirmTrade_Handler,
		},
		{
			MethodName: "CompleteTrade",
			Handler:    _ZoneService_CompleteTrade_Handler,
		},
		{
			MethodName: "CancelTrade",
			Handler:    _ZoneService_CancelTrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zone/v1/zone.proto",
}
