// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: zone/v1/zone.proto

package zonev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnterZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	LoginId1      uint64                 `protobuf:"fixed64,3,opt,name=login_id1,json=loginId1,proto3" json:"login_id1,omitempty"` // from identity.Authenticate
	ClientTick    uint32                 `protobuf:"varint,4,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	Sex           string                 `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Packetver     uint32                 `protobuf:"varint,6,opt,name=packetver,proto3" json:"packetver,omitempty"`
	ClientIp      string                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterZoneRequest) Reset() {
	*x = EnterZoneRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterZoneRequest) ProtoMessage() {}

func (x *EnterZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterZoneRequest.ProtoReflect.Descriptor instead.
func (*EnterZoneRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{0}
}

func (x *EnterZoneRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *EnterZoneRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *EnterZoneRequest) GetLoginId1() uint64 {
	if x != nil {
		return x.LoginId1
	}
	return 0
}

func (x *EnterZoneRequest) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *EnterZoneRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *EnterZoneRequest) GetPacketver() uint32 {
	if x != nil {
		return x.Packetver
	}
	return 0
}

func (x *EnterZoneRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type EnterZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MapName       string                 `protobuf:"bytes,2,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MapX          uint32                 `protobuf:"varint,3,opt,name=map_x,json=mapX,proto3" json:"map_x,omitempty"`
	MapY          uint32                 `protobuf:"varint,4,opt,name=map_y,json=mapY,proto3" json:"map_y,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // human-readable error when success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterZoneResponse) Reset() {
	*x = EnterZoneResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterZoneResponse) ProtoMessage() {}

func (x *EnterZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterZoneResponse.ProtoReflect.Descriptor instead.
func (*EnterZoneResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{1}
}

func (x *EnterZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnterZoneResponse) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *EnterZoneResponse) GetMapX() uint32 {
	if x != nil {
		return x.MapX
	}
	return 0
}

func (x *EnterZoneResponse) GetMapY() uint32 {
	if x != nil {
		return x.MapY
	}
	return 0
}

func (x *EnterZoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MoveEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DestX         uint32                 `protobuf:"varint,2,opt,name=dest_x,json=destX,proto3" json:"dest_x,omitempty"` // destination cell X
	DestY         uint32                 `protobuf:"varint,3,opt,name=dest_y,json=destY,proto3" json:"dest_y,omitempty"` // destination cell Y
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveEntityRequest) Reset() {
	*x = MoveEntityRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntityRequest) ProtoMessage() {}

func (x *MoveEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntityRequest.ProtoReflect.Descriptor instead.
func (*MoveEntityRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{2}
}

func (x *MoveEntityRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *MoveEntityRequest) GetDestX() uint32 {
	if x != nil {
		return x.DestX
	}
	return 0
}

func (x *MoveEntityRequest) GetDestY() uint32 {
	if x != nil {
		return x.DestY
	}
	return 0
}

type MoveEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SrcX          uint32                 `protobuf:"varint,2,opt,name=src_x,json=srcX,proto3" json:"src_x,omitempty"` // cell the move started from
	SrcY          uint32                 `protobuf:"varint,3,opt,name=src_y,json=srcY,proto3" json:"src_y,omitempty"`
	DestX         uint32                 `protobuf:"varint,4,opt,name=dest_x,json=destX,proto3" json:"dest_x,omitempty"` // cell the path targets (echoed back)
	DestY         uint32                 `protobuf:"varint,5,opt,name=dest_y,json=destY,proto3" json:"dest_y,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // human-readable error when success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveEntityResponse) Reset() {
	*x = MoveEntityResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntityResponse) ProtoMessage() {}

func (x *MoveEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntityResponse.ProtoReflect.Descriptor instead.
func (*MoveEntityResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{3}
}

func (x *MoveEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveEntityResponse) GetSrcX() uint32 {
	if x != nil {
		return x.SrcX
	}
	return 0
}

func (x *MoveEntityResponse) GetSrcY() uint32 {
	if x != nil {
		return x.SrcY
	}
	return 0
}

func (x *MoveEntityResponse) GetDestX() uint32 {
	if x != nil {
		return x.DestX
	}
	return 0
}

func (x *MoveEntityResponse) GetDestY() uint32 {
	if x != nil {
		return x.DestY
	}
	return 0
}

func (x *MoveEntityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AttackEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // target entity ID
	Damage        uint32                 `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`                           // damage to apply (optional; defaults to 1)
	AttackerId    uint32                 `protobuf:"varint,3,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"` // source entity ID (player/GM)
	SkillId       uint32                 `protobuf:"varint,4,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`          // skill ID used (0 for auto-attack)
	SkillLevel    uint32                 `protobuf:"varint,5,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"` // skill level (0 if skill_id == 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEntityRequest) Reset() {
	*x = AttackEntityRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEntityRequest) ProtoMessage() {}

func (x *AttackEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEntityRequest.ProtoReflect.Descriptor instead.
func (*AttackEntityRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{4}
}

func (x *AttackEntityRequest) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *AttackEntityRequest) GetDamage() uint32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *AttackEntityRequest) GetAttackerId() uint32 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *AttackEntityRequest) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *AttackEntityRequest) GetSkillLevel() uint32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

type AttackEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TargetDied    bool                   `protobuf:"varint,2,opt,name=target_died,json=targetDied,proto3" json:"target_died,omitempty"`          // true if entity HP <= 0
	DamageApplied int32                  `protobuf:"varint,3,opt,name=damage_applied,json=damageApplied,proto3" json:"damage_applied,omitempty"` // damage actually applied
	CurrentHp     int32                  `protobuf:"varint,4,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`             // target's HP after damage
	MaxHp         int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`                         // target's MaxHP (unchanged)
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                       // human-readable error if success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEntityResponse) Reset() {
	*x = AttackEntityResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEntityResponse) ProtoMessage() {}

func (x *AttackEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEntityResponse.ProtoReflect.Descriptor instead.
func (*AttackEntityResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{5}
}

func (x *AttackEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttackEntityResponse) GetTargetDied() bool {
	if x != nil {
		return x.TargetDied
	}
	return false
}

func (x *AttackEntityResponse) GetDamageApplied() int32 {
	if x != nil {
		return x.DamageApplied
	}
	return 0
}

func (x *AttackEntityResponse) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *AttackEntityResponse) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *AttackEntityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PickupItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundItemId  uint32                 `protobuf:"varint,1,opt,name=ground_item_id,json=groundItemId,proto3" json:"ground_item_id,omitempty"` // ground item ID
	PlayerId      uint32                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`               // requesting player entity ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupItemRequest) Reset() {
	*x = PickupItemRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupItemRequest) ProtoMessage() {}

func (x *PickupItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupItemRequest.ProtoReflect.Descriptor instead.
func (*PickupItemRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{6}
}

func (x *PickupItemRequest) GetGroundItemId() uint32 {
	if x != nil {
		return x.GroundItemId
	}
	return 0
}

func (x *PickupItemRequest) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PickupItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // numeric item ID
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`               // item amount (typically 1)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                  // human-readable error if success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupItemResponse) Reset() {
	*x = PickupItemResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupItemResponse) ProtoMessage() {}

func (x *PickupItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupItemResponse.ProtoReflect.Descriptor instead.
func (*PickupItemResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{7}
}

func (x *PickupItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PickupItemResponse) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PickupItemResponse) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PickupItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RequestTradeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterCharId uint32                 `protobuf:"varint,1,opt,name=requester_char_id,json=requesterCharId,proto3" json:"requester_char_id,omitempty"`
	TargetCharId    uint32                 `protobuf:"varint,2,opt,name=target_char_id,json=targetCharId,proto3" json:"target_char_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestTradeRequest) Reset() {
	*x = RequestTradeRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTradeRequest) ProtoMessage() {}

func (x *RequestTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTradeRequest.ProtoReflect.Descriptor instead.
func (*RequestTradeRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{8}
}

func (x *RequestTradeRequest) GetRequesterCharId() uint32 {
	if x != nil {
		return x.RequesterCharId
	}
	return 0
}

func (x *RequestTradeRequest) GetTargetCharId() uint32 {
	if x != nil {
		return x.TargetCharId
	}
	return 0
}

type RequestTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TradeId       string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // Assigned trade session ID
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                    // Human-readable error if success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTradeResponse) Reset() {
	*x = RequestTradeResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTradeResponse) ProtoMessage() {}

func (x *RequestTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTradeResponse.ProtoReflect.Descriptor instead.
func (*RequestTradeResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{9}
}

func (x *RequestTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestTradeResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *RequestTradeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddTradeItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	InventoryId   uint32                 `protobuf:"varint,3,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTradeItemRequest) Reset() {
	*x = AddTradeItemRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTradeItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTradeItemRequest) ProtoMessage() {}

func (x *AddTradeItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTradeItemRequest.ProtoReflect.Descriptor instead.
func (*AddTradeItemRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{10}
}

func (x *AddTradeItemRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *AddTradeItemRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *AddTradeItemRequest) GetInventoryId() uint32 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *AddTradeItemRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddTradeItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTradeItemResponse) Reset() {
	*x = AddTradeItemResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTradeItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTradeItemResponse) ProtoMessage() {}

func (x *AddTradeItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTradeItemResponse.ProtoReflect.Descriptor instead.
func (*AddTradeItemResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{11}
}

func (x *AddTradeItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTradeItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddTradeZenyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Zeny          uint32                 `protobuf:"varint,3,opt,name=zeny,proto3" json:"zeny,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTradeZenyRequest) Reset() {
	*x = AddTradeZenyRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTradeZenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTradeZenyRequest) ProtoMessage() {}

func (x *AddTradeZenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTradeZenyRequest.ProtoReflect.Descriptor instead.
func (*AddTradeZenyRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{12}
}

func (x *AddTradeZenyRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *AddTradeZenyRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *AddTradeZenyRequest) GetZeny() uint32 {
	if x != nil {
		return x.Zeny
	}
	return 0
}

type AddTradeZenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTradeZenyResponse) Reset() {
	*x = AddTradeZenyResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTradeZenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTradeZenyResponse) ProtoMessage() {}

func (x *AddTradeZenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTradeZenyResponse.ProtoReflect.Descriptor instead.
func (*AddTradeZenyResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{13}
}

func (x *AddTradeZenyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTradeZenyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfirmTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTradeRequest) Reset() {
	*x = ConfirmTradeRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTradeRequest) ProtoMessage() {}

func (x *ConfirmTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTradeRequest.ProtoReflect.Descriptor instead.
func (*ConfirmTradeRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{14}
}

func (x *ConfirmTradeRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *ConfirmTradeRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

type ConfirmTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTradeResponse) Reset() {
	*x = ConfirmTradeResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTradeResponse) ProtoMessage() {}

func (x *ConfirmTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTradeResponse.ProtoReflect.Descriptor instead.
func (*ConfirmTradeResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{15}
}

func (x *ConfirmTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmTradeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTradeRequest) Reset() {
	*x = CompleteTradeRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTradeRequest) ProtoMessage() {}

func (x *CompleteTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTradeRequest.ProtoReflect.Descriptor instead.
func (*CompleteTradeRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteTradeRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *CompleteTradeRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

type CompleteTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTradeResponse) Reset() {
	*x = CompleteTradeResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTradeResponse) ProtoMessage() {}

func (x *CompleteTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTradeResponse.ProtoReflect.Descriptor instead.
func (*CompleteTradeResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{17}
}

func (x *CompleteTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteTradeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTradeRequest) Reset() {
	*x = CancelTradeRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeRequest) ProtoMessage() {}

func (x *CancelTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeRequest.ProtoReflect.Descriptor instead.
func (*CancelTradeRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{18}
}

func (x *CancelTradeRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *CancelTradeRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

type CancelTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTradeResponse) Reset() {
	*x = CancelTradeResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeResponse) ProtoMessage() {}

func (x *CancelTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeResponse.ProtoReflect.Descriptor instead.
func (*CancelTradeResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{19}
}

func (x *CancelTradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTradeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OpenStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"` // Character whose storage to open
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStorageRequest) Reset() {
	*x = OpenStorageRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStorageRequest) ProtoMessage() {}

func (x *OpenStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStorageRequest.ProtoReflect.Descriptor instead.
func (*OpenStorageRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{20}
}

func (x *OpenStorageRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

type OpenStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Items         []*StorageItem         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"` // List of items in storage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStorageResponse) Reset() {
	*x = OpenStorageResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStorageResponse) ProtoMessage() {}

func (x *OpenStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStorageResponse.ProtoReflect.Descriptor instead.
func (*OpenStorageResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{21}
}

func (x *OpenStorageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenStorageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OpenStorageResponse) GetItems() []*StorageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DepositItemRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharId          uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	InventoryItemId uint64                 `protobuf:"varint,2,opt,name=inventory_item_id,json=inventoryItemId,proto3" json:"inventory_item_id,omitempty"` // Item ID from character inventory
	Amount          int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                            // Amount to deposit (must be > 0)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepositItemRequest) Reset() {
	*x = DepositItemRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositItemRequest) ProtoMessage() {}

func (x *DepositItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositItemRequest.ProtoReflect.Descriptor instead.
func (*DepositItemRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{22}
}

func (x *DepositItemRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *DepositItemRequest) GetInventoryItemId() uint64 {
	if x != nil {
		return x.InventoryItemId
	}
	return 0
}

func (x *DepositItemRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DepositItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StorageItemId uint64                 `protobuf:"varint,3,opt,name=storage_item_id,json=storageItemId,proto3" json:"storage_item_id,omitempty"` // ID of the created/updated storage item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositItemResponse) Reset() {
	*x = DepositItemResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositItemResponse) ProtoMessage() {}

func (x *DepositItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositItemResponse.ProtoReflect.Descriptor instead.
func (*DepositItemResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{23}
}

func (x *DepositItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DepositItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DepositItemResponse) GetStorageItemId() uint64 {
	if x != nil {
		return x.StorageItemId
	}
	return 0
}

type WithdrawItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	StorageItemId uint64                 `protobuf:"varint,2,opt,name=storage_item_id,json=storageItemId,proto3" json:"storage_item_id,omitempty"` // Item ID in storage
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                      // Amount to withdraw (must be > 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawItemRequest) Reset() {
	*x = WithdrawItemRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawItemRequest) ProtoMessage() {}

func (x *WithdrawItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawItemRequest.ProtoReflect.Descriptor instead.
func (*WithdrawItemRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{24}
}

func (x *WithdrawItemRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *WithdrawItemRequest) GetStorageItemId() uint64 {
	if x != nil {
		return x.StorageItemId
	}
	return 0
}

func (x *WithdrawItemRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawItemResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	InventoryItemId uint64                 `protobuf:"varint,3,opt,name=inventory_item_id,json=inventoryItemId,proto3" json:"inventory_item_id,omitempty"` // ID of the created/updated inventory item
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WithdrawItemResponse) Reset() {
	*x = WithdrawItemResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawItemResponse) ProtoMessage() {}

func (x *WithdrawItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawItemResponse.ProtoReflect.Descriptor instead.
func (*WithdrawItemResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{25}
}

func (x *WithdrawItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WithdrawItemResponse) GetInventoryItemId() uint64 {
	if x != nil {
		return x.InventoryItemId
	}
	return 0
}

type CloseStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStorageRequest) Reset() {
	*x = CloseStorageRequest{}
	mi := &file_zone_v1_zone_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStorageRequest) ProtoMessage() {}

func (x *CloseStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStorageRequest.ProtoReflect.Descriptor instead.
func (*CloseStorageRequest) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{26}
}

func (x *CloseStorageRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

type CloseStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStorageResponse) Reset() {
	*x = CloseStorageResponse{}
	mi := &file_zone_v1_zone_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStorageResponse) ProtoMessage() {}

func (x *CloseStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStorageResponse.ProtoReflect.Descriptor instead.
func (*CloseStorageResponse) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{27}
}

func (x *CloseStorageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseStorageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StorageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	NameId        uint32                 `protobuf:"varint,3,opt,name=name_id,json=nameId,proto3" json:"name_id,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Identify      uint32                 `protobuf:"varint,5,opt,name=identify,proto3" json:"identify,omitempty"`
	Refine        uint32                 `protobuf:"varint,6,opt,name=refine,proto3" json:"refine,omitempty"`
	Attribute     uint32                 `protobuf:"varint,7,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Card0         uint64                 `protobuf:"varint,8,opt,name=card0,proto3" json:"card0,omitempty"`
	Card1         uint64                 `protobuf:"varint,9,opt,name=card1,proto3" json:"card1,omitempty"`
	Card2         uint64                 `protobuf:"varint,10,opt,name=card2,proto3" json:"card2,omitempty"`
	Card3         uint64                 `protobuf:"varint,11,opt,name=card3,proto3" json:"card3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageItem) Reset() {
	*x = StorageItem{}
	mi := &file_zone_v1_zone_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageItem) ProtoMessage() {}

func (x *StorageItem) ProtoReflect() protoreflect.Message {
	mi := &file_zone_v1_zone_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageItem.ProtoReflect.Descriptor instead.
func (*StorageItem) Descriptor() ([]byte, []int) {
	return file_zone_v1_zone_proto_rawDescGZIP(), []int{28}
}

func (x *StorageItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageItem) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *StorageItem) GetNameId() uint32 {
	if x != nil {
		return x.NameId
	}
	return 0
}

func (x *StorageItem) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StorageItem) GetIdentify() uint32 {
	if x != nil {
		return x.Identify
	}
	return 0
}

func (x *StorageItem) GetRefine() uint32 {
	if x != nil {
		return x.Refine
	}
	return 0
}

func (x *StorageItem) GetAttribute() uint32 {
	if x != nil {
		return x.Attribute
	}
	return 0
}

func (x *StorageItem) GetCard0() uint64 {
	if x != nil {
		return x.Card0
	}
	return 0
}

func (x *StorageItem) GetCard1() uint64 {
	if x != nil {
		return x.Card1
	}
	return 0
}

func (x *StorageItem) GetCard2() uint64 {
	if x != nil {
		return x.Card2
	}
	return 0
}

func (x *StorageItem) GetCard3() uint64 {
	if x != nil {
		return x.Card3
	}
	return 0
}

var File_zone_v1_zone_proto protoreflect.FileDescriptor

const file_zone_v1_zone_proto_rawDesc = "" +
	"\n" +
	"\x12zone/v1/zone.proto\x12\azone.v1\"\xd5\x01\n" +
	"\x10EnterZoneRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x1b\n" +
	"\tlogin_id1\x18\x03 \x01(\x06R\bloginId1\x12\x1f\n" +
	"\vclient_tick\x18\x04 \x01(\rR\n" +
	"clientTick\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\tR\x03sex\x12\x1c\n" +
	"\tpacketver\x18\x06 \x01(\rR\tpacketver\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\"\x88\x01\n" +
	"\x11EnterZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bmap_name\x18\x02 \x01(\tR\amapName\x12\x13\n" +
	"\x05map_x\x18\x03 \x01(\rR\x04mapX\x12\x13\n" +
	"\x05map_y\x18\x04 \x01(\rR\x04mapY\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"`\n" +
	"\x11MoveEntityRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x15\n" +
	"\x06dest_x\x18\x02 \x01(\rR\x05destX\x12\x15\n" +
	"\x06dest_y\x18\x03 \x01(\rR\x05destY\"\x9c\x01\n" +
	"\x12MoveEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05src_x\x18\x02 \x01(\rR\x04srcX\x12\x13\n" +
	"\x05src_y\x18\x03 \x01(\rR\x04srcY\x12\x15\n" +
	"\x06dest_x\x18\x04 \x01(\rR\x05destX\x12\x15\n" +
	"\x06dest_y\x18\x05 \x01(\rR\x05destY\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x13AttackEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\rR\x06damage\x12\x1f\n" +
	"\vattacker_id\x18\x03 \x01(\rR\n" +
	"attackerId\x12\x19\n" +
	"\bskill_id\x18\x04 \x01(\rR\askillId\x12\x1f\n" +
	"\vskill_level\x18\x05 \x01(\rR\n" +
	"skillLevel\"\xc4\x01\n" +
	"\x14AttackEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtarget_died\x18\x02 \x01(\bR\n" +
	"targetDied\x12%\n" +
	"\x0edamage_applied\x18\x03 \x01(\x05R\rdamageApplied\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x04 \x01(\x05R\tcurrentHp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"V\n" +
	"\x11PickupItemRequest\x12$\n" +
	"\x0eground_item_id\x18\x01 \x01(\rR\fgroundItemId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\rR\bplayerId\"u\n" +
	"\x12PickupItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"g\n" +
	"\x13RequestTradeRequest\x12*\n" +
	"\x11requester_char_id\x18\x01 \x01(\rR\x0frequesterCharId\x12$\n" +
	"\x0etarget_char_id\x18\x02 \x01(\rR\ftargetCharId\"a\n" +
	"\x14RequestTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x84\x01\n" +
	"\x13AddTradeItemRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12!\n" +
	"\finventory_id\x18\x03 \x01(\rR\vinventoryId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\"F\n" +
	"\x14AddTradeItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"]\n" +
	"\x13AddTradeZenyRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x12\n" +
	"\x04zeny\x18\x03 \x01(\rR\x04zeny\"F\n" +
	"\x14AddTradeZenyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\x13ConfirmTradeRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\"F\n" +
	"\x14ConfirmTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"J\n" +
	"\x14CompleteTradeRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\"G\n" +
	"\x15CompleteTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"H\n" +
	"\x12CancelTradeRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\"E\n" +
	"\x13CancelTradeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x12OpenStorageRequest\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\"\x80\x01\n" +
	"\x13OpenStorageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.zone.v1.StorageItemR\x05items\"q\n" +
	"\x12DepositItemRequest\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\x12*\n" +
	"\x11inventory_item_id\x18\x02 \x01(\x04R\x0finventoryItemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"|\n" +
	"\x13DepositItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12&\n" +
	"\x0fstorage_item_id\x18\x03 \x01(\x04R\rstorageItemId\"n\n" +
	"\x13WithdrawItemRequest\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\x12&\n" +
	"\x0fstorage_item_id\x18\x02 \x01(\x04R\rstorageItemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"\x81\x01\n" +
	"\x14WithdrawItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11inventory_item_id\x18\x03 \x01(\x04R\x0finventoryItemId\".\n" +
	"\x13CloseStorageRequest\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\"U\n" +
	"\x14CloseStorageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x91\x02\n" +
	"\vStorageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x17\n" +
	"\aname_id\x18\x03 \x01(\rR\x06nameId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x1a\n" +
	"\bidentify\x18\x05 \x01(\rR\bidentify\x12\x16\n" +
	"\x06refine\x18\x06 \x01(\rR\x06refine\x12\x1c\n" +
	"\tattribute\x18\a \x01(\rR\tattribute\x12\x14\n" +
	"\x05card0\x18\b \x01(\x04R\x05card0\x12\x14\n" +
	"\x05card1\x18\t \x01(\x04R\x05card1\x12\x14\n" +
	"\x05card2\x18\n" +
	" \x01(\x04R\x05card2\x12\x14\n" +
	"\x05card3\x18\v \x01(\x04R\x05card32\xa8\b\n" +
	"\vZoneService\x12B\n" +
	"\tEnterZone\x12\x19.zone.v1.EnterZoneRequest\x1a\x1a.zone.v1.EnterZoneResponse\x12E\n" +
	"\n" +
	"MoveEntity\x12\x1a.zone.v1.MoveEntityRequest\x1a\x1b.zone.v1.MoveEntityResponse\x12K\n" +
	"\fAttackEntity\x12\x1c.zone.v1.AttackEntityRequest\x1a\x1d.zone.v1.AttackEntityResponse\x12E\n" +
	"\n" +
	"PickupItem\x12\x1a.zone.v1.PickupItemRequest\x1a\x1b.zone.v1.PickupItemResponse\x12K\n" +
	"\fRequestTrade\x12\x1c.zone.v1.RequestTradeRequest\x1a\x1d.zone.v1.RequestTradeResponse\x12K\n" +
	"\fAddTradeItem\x12\x1c.zone.v1.AddTradeItemRequest\x1a\x1d.zone.v1.AddTradeItemResponse\x12K\n" +
	"\fAddTradeZeny\x12\x1c.zone.v1.AddTradeZenyRequest\x1a\x1d.zone.v1.AddTradeZenyResponse\x12K\n" +
	"\fConfirmTrade\x12\x1c.zone.v1.ConfirmTradeRequest\x1a\x1d.zone.v1.ConfirmTradeResponse\x12N\n" +
	"\rCompleteTrade\x12\x1d.zone.v1.CompleteTradeRequest\x1a\x1e.zone.v1.CompleteTradeResponse\x12H\n" +
	"\vCancelTrade\x12\x1b.zone.v1.CancelTradeRequest\x1a\x1c.zone.v1.CancelTradeResponse\x12H\n" +
	"\vOpenStorage\x12\x1b.zone.v1.OpenStorageRequest\x1a\x1c.zone.v1.OpenStorageResponse\x12H\n" +
	"\vDepositItem\x12\x1b.zone.v1.DepositItemRequest\x1a\x1c.zone.v1.DepositItemResponse\x12K\n" +
	"\fWithdrawItem\x12\x1c.zone.v1.WithdrawItemRequest\x1a\x1d.zone.v1.WithdrawItemResponse\x12K\n" +
	"\fCloseStorage\x12\x1c.zone.v1.CloseStorageRequest\x1a\x1d.zone.v1.CloseStorageResponseB2Z0github.com/bouroo/goAthena/api/pb/zone/v1;zonev1b\x06proto3"

var (
	file_zone_v1_zone_proto_rawDescOnce sync.Once
	file_zone_v1_zone_proto_rawDescData []byte
)

func file_zone_v1_zone_proto_rawDescGZIP() []byte {
	file_zone_v1_zone_proto_rawDescOnce.Do(func() {
		file_zone_v1_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zone_v1_zone_proto_rawDesc), len(file_zone_v1_zone_proto_rawDesc)))
	})
	return file_zone_v1_zone_proto_rawDescData
}

var file_zone_v1_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_zone_v1_zone_proto_goTypes = []any{
	(*EnterZoneRequest)(nil),      // 0: zone.v1.EnterZoneRequest
	(*EnterZoneResponse)(nil),     // 1: zone.v1.EnterZoneResponse
	(*MoveEntityRequest)(nil),     // 2: zone.v1.MoveEntityRequest
	(*MoveEntityResponse)(nil),    // 3: zone.v1.MoveEntityResponse
	(*AttackEntityRequest)(nil),   // 4: zone.v1.AttackEntityRequest
	(*AttackEntityResponse)(nil),  // 5: zone.v1.AttackEntityResponse
	(*PickupItemRequest)(nil),     // 6: zone.v1.PickupItemRequest
	(*PickupItemResponse)(nil),    // 7: zone.v1.PickupItemResponse
	(*RequestTradeRequest)(nil),   // 8: zone.v1.RequestTradeRequest
	(*RequestTradeResponse)(nil),  // 9: zone.v1.RequestTradeResponse
	(*AddTradeItemRequest)(nil),   // 10: zone.v1.AddTradeItemRequest
	(*AddTradeItemResponse)(nil),  // 11: zone.v1.AddTradeItemResponse
	(*AddTradeZenyRequest)(nil),   // 12: zone.v1.AddTradeZenyRequest
	(*AddTradeZenyResponse)(nil),  // 13: zone.v1.AddTradeZenyResponse
	(*ConfirmTradeRequest)(nil),   // 14: zone.v1.ConfirmTradeRequest
	(*ConfirmTradeResponse)(nil),  // 15: zone.v1.ConfirmTradeResponse
	(*CompleteTradeRequest)(nil),  // 16: zone.v1.CompleteTradeRequest
	(*CompleteTradeResponse)(nil), // 17: zone.v1.CompleteTradeResponse
	(*CancelTradeRequest)(nil),    // 18: zone.v1.CancelTradeRequest
	(*CancelTradeResponse)(nil),   // 19: zone.v1.CancelTradeResponse
	(*OpenStorageRequest)(nil),    // 20: zone.v1.OpenStorageRequest
	(*OpenStorageResponse)(nil),   // 21: zone.v1.OpenStorageResponse
	(*DepositItemRequest)(nil),    // 22: zone.v1.DepositItemRequest
	(*DepositItemResponse)(nil),   // 23: zone.v1.DepositItemResponse
	(*WithdrawItemRequest)(nil),   // 24: zone.v1.WithdrawItemRequest
	(*WithdrawItemResponse)(nil),  // 25: zone.v1.WithdrawItemResponse
	(*CloseStorageRequest)(nil),   // 26: zone.v1.CloseStorageRequest
	(*CloseStorageResponse)(nil),  // 27: zone.v1.CloseStorageResponse
	(*StorageItem)(nil),           // 28: zone.v1.StorageItem
}
var file_zone_v1_zone_proto_depIdxs = []int32{
	28, // 0: zone.v1.OpenStorageResponse.items:type_name -> zone.v1.StorageItem
	0,  // 1: zone.v1.ZoneService.EnterZone:input_type -> zone.v1.EnterZoneRequest
	2,  // 2: zone.v1.ZoneService.MoveEntity:input_type -> zone.v1.MoveEntityRequest
	4,  // 3: zone.v1.ZoneService.AttackEntity:input_type -> zone.v1.AttackEntityRequest
	6,  // 4: zone.v1.ZoneService.PickupItem:input_type -> zone.v1.PickupItemRequest
	8,  // 5: zone.v1.ZoneService.RequestTrade:input_type -> zone.v1.RequestTradeRequest
	10, // 6: zone.v1.ZoneService.AddTradeItem:input_type -> zone.v1.AddTradeItemRequest
	12, // 7: zone.v1.ZoneService.AddTradeZeny:input_type -> zone.v1.AddTradeZenyRequest
	14, // 8: zone.v1.ZoneService.ConfirmTrade:input_type -> zone.v1.ConfirmTradeRequest
	16, // 9: zone.v1.ZoneService.CompleteTrade:input_type -> zone.v1.CompleteTradeRequest
	18, // 10: zone.v1.ZoneService.CancelTrade:input_type -> zone.v1.CancelTradeRequest
	20, // 11: zone.v1.ZoneService.OpenStorage:input_type -> zone.v1.OpenStorageRequest
	22, // 12: zone.v1.ZoneService.DepositItem:input_type -> zone.v1.DepositItemRequest
	24, // 13: zone.v1.ZoneService.WithdrawItem:input_type -> zone.v1.WithdrawItemRequest
	26, // 14: zone.v1.ZoneService.CloseStorage:input_type -> zone.v1.CloseStorageRequest
	1,  // 15: zone.v1.ZoneService.EnterZone:output_type -> zone.v1.EnterZoneResponse
	3,  // 16: zone.v1.ZoneService.MoveEntity:output_type -> zone.v1.MoveEntityResponse
	5,  // 17: zone.v1.ZoneService.AttackEntity:output_type -> zone.v1.AttackEntityResponse
	7,  // 18: zone.v1.ZoneService.PickupItem:output_type -> zone.v1.PickupItemResponse
	9,  // 19: zone.v1.ZoneService.RequestTrade:output_type -> zone.v1.RequestTradeResponse
	11, // 20: zone.v1.ZoneService.AddTradeItem:output_type -> zone.v1.AddTradeItemResponse
	13, // 21: zone.v1.ZoneService.AddTradeZeny:output_type -> zone.v1.AddTradeZenyResponse
	15, // 22: zone.v1.ZoneService.ConfirmTrade:output_type -> zone.v1.ConfirmTradeResponse
	17, // 23: zone.v1.ZoneService.CompleteTrade:output_type -> zone.v1.CompleteTradeResponse
	19, // 24: zone.v1.ZoneService.CancelTrade:output_type -> zone.v1.CancelTradeResponse
	21, // 25: zone.v1.ZoneService.OpenStorage:output_type -> zone.v1.OpenStorageResponse
	23, // 26: zone.v1.ZoneService.DepositItem:output_type -> zone.v1.DepositItemResponse
	25, // 27: zone.v1.ZoneService.WithdrawItem:output_type -> zone.v1.WithdrawItemResponse
	27, // 28: zone.v1.ZoneService.CloseStorage:output_type -> zone.v1.CloseStorageResponse
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_zone_v1_zone_proto_init() }
func file_zone_v1_zone_proto_init() {
	if File_zone_v1_zone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zone_v1_zone_proto_rawDesc), len(file_zone_v1_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zone_v1_zone_proto_goTypes,
		DependencyIndexes: file_zone_v1_zone_proto_depIdxs,
		MessageInfos:      file_zone_v1_zone_proto_msgTypes,
	}.Build()
	File_zone_v1_zone_proto = out.File
	file_zone_v1_zone_proto_goTypes = nil
	file_zone_v1_zone_proto_depIdxs = nil
}
