// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: identity/v1/identity.proto

package identityv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_Authenticate_FullMethodName     = "/identity.v1.IdentityService/Authenticate"
	IdentityService_GetCharacterList_FullMethodName = "/identity.v1.IdentityService/GetCharacterList"
	IdentityService_GetCharacter_FullMethodName     = "/identity.v1.IdentityService/GetCharacter"
	IdentityService_GetInventory_FullMethodName     = "/identity.v1.IdentityService/GetInventory"
	IdentityService_EquipItem_FullMethodName        = "/identity.v1.IdentityService/EquipItem"
	IdentityService_UnequipItem_FullMethodName      = "/identity.v1.IdentityService/UnequipItem"
	IdentityService_UseItem_FullMethodName          = "/identity.v1.IdentityService/UseItem"
	IdentityService_BuyFromShop_FullMethodName      = "/identity.v1.IdentityService/BuyFromShop"
	IdentityService_SellToShop_FullMethodName       = "/identity.v1.IdentityService/SellToShop"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService handles login authentication, character CRUD, warehouse,
// and inventory operations. The gateway forwards decoded kRO login
// packets here as structured RPCs.
//
// Login handshake reference: rathena/src/login/loginclif.cpp
// Inventory reference:      rathena/src/map/clif.cpp (CZ_USE_ITEM / CZ_REQ_EQUIP / ZC_ACK_REQ_EQUIP)
type IdentityServiceClient interface {
	// Authenticate processes a client login (CA_LOGIN* variants 0x64/0x1dd/0x1fa/0x27c/...).
	// Returns auth result + char-server list on success (AC_ACCEPT_LOGIN 0xac4).
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// GetCharacterList returns the character list for an authenticated account
	// (HC_ACCEPT_ENTER 0x6b). Called after the client connects to the char server.
	GetCharacterList(ctx context.Context, in *GetCharacterListRequest, opts ...grpc.CallOption) (*GetCharacterListResponse, error)
	// GetCharacter returns the full character detail (name, class, level,
	// HP, hair, equipment, sex) for a single character on an authenticated
	// account. The gateway calls this on CZ_ENTER to populate the entity
	// spawn packet (ZC_SPAWN_UNIT 0x09fe) with real character data.
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*GetCharacterResponse, error)
	// GetInventory returns every item the character owns. Backed by the
	// `inventory` table (rathena/sql-files/main.sql); consumed by the
	// gateway when building the inventory view on map enter and after
	// each successful item mutation.
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	// EquipItem moves an item from the inventory grid to an equipment slot
	// (CZ_REQ_EQUIP / ZC_ACK_REQ_EQUIP). The equip position is the rAthena
	// EQP_* bitmask (pc.h). Item ownership by the calling character is
	// enforced server-side.
	EquipItem(ctx context.Context, in *EquipItemRequest, opts ...grpc.CallOption) (*EquipItemResponse, error)
	// UnequipItem moves an equipped item back into the inventory grid
	// (equip bitmask cleared to 0).
	UnequipItem(ctx context.Context, in *UnequipItemRequest, opts ...grpc.CallOption) (*UnequipItemResponse, error)
	// UseItem decrements the stack count of an item by one. When the
	// remaining amount reaches zero the row is deleted. Consumables only;
	// equipment items are not stackable on rAthena's wire.
	UseItem(ctx context.Context, in *UseItemRequest, opts ...grpc.CallOption) (*UseItemResponse, error)
	// BuyFromShop commits one or more buy orders from an NPC shop for the
	// given character. The gateway computes the unit prices from its own
	// shop catalog (D-204); the server never trusts a client-supplied
	// price. Returns a BuyResult outcome + the post-transaction zeny
	// balance (0 on non-OK).
	BuyFromShop(ctx context.Context, in *BuyFromShopRequest, opts ...grpc.CallOption) (*BuyFromShopResponse, error)
	// SellToShop credits the character for one or more inventory items
	// sold to an NPC shop. The inv_id is the inventory row id (not a
	// wire slot). Returns a SellResult outcome + the post-transaction
	// zeny balance (0 on non-OK).
	SellToShop(ctx context.Context, in *SellToShopRequest, opts ...grpc.CallOption) (*SellToShopResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, IdentityService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetCharacterList(ctx context.Context, in *GetCharacterListRequest, opts ...grpc.CallOption) (*GetCharacterListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCharacterListResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetCharacterList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*GetCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCharacterResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) EquipItem(ctx context.Context, in *EquipItemRequest, opts ...grpc.CallOption) (*EquipItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EquipItemResponse)
	err := c.cc.Invoke(ctx, IdentityService_EquipItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UnequipItem(ctx context.Context, in *UnequipItemRequest, opts ...grpc.CallOption) (*UnequipItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnequipItemResponse)
	err := c.cc.Invoke(ctx, IdentityService_UnequipItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UseItem(ctx context.Context, in *UseItemRequest, opts ...grpc.CallOption) (*UseItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseItemResponse)
	err := c.cc.Invoke(ctx, IdentityService_UseItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) BuyFromShop(ctx context.Context, in *BuyFromShopRequest, opts ...grpc.CallOption) (*BuyFromShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyFromShopResponse)
	err := c.cc.Invoke(ctx, IdentityService_BuyFromShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SellToShop(ctx context.Context, in *SellToShopRequest, opts ...grpc.CallOption) (*SellToShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellToShopResponse)
	err := c.cc.Invoke(ctx, IdentityService_SellToShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService handles login authentication, character CRUD, warehouse,
// and inventory operations. The gateway forwards decoded kRO login
// packets here as structured RPCs.
//
// Login handshake reference: rathena/src/login/loginclif.cpp
// Inventory reference:      rathena/src/map/clif.cpp (CZ_USE_ITEM / CZ_REQ_EQUIP / ZC_ACK_REQ_EQUIP)
type IdentityServiceServer interface {
	// Authenticate processes a client login (CA_LOGIN* variants 0x64/0x1dd/0x1fa/0x27c/...).
	// Returns auth result + char-server list on success (AC_ACCEPT_LOGIN 0xac4).
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// GetCharacterList returns the character list for an authenticated account
	// (HC_ACCEPT_ENTER 0x6b). Called after the client connects to the char server.
	GetCharacterList(context.Context, *GetCharacterListRequest) (*GetCharacterListResponse, error)
	// GetCharacter returns the full character detail (name, class, level,
	// HP, hair, equipment, sex) for a single character on an authenticated
	// account. The gateway calls this on CZ_ENTER to populate the entity
	// spawn packet (ZC_SPAWN_UNIT 0x09fe) with real character data.
	GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterResponse, error)
	// GetInventory returns every item the character owns. Backed by the
	// `inventory` table (rathena/sql-files/main.sql); consumed by the
	// gateway when building the inventory view on map enter and after
	// each successful item mutation.
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	// EquipItem moves an item from the inventory grid to an equipment slot
	// (CZ_REQ_EQUIP / ZC_ACK_REQ_EQUIP). The equip position is the rAthena
	// EQP_* bitmask (pc.h). Item ownership by the calling character is
	// enforced server-side.
	EquipItem(context.Context, *EquipItemRequest) (*EquipItemResponse, error)
	// UnequipItem moves an equipped item back into the inventory grid
	// (equip bitmask cleared to 0).
	UnequipItem(context.Context, *UnequipItemRequest) (*UnequipItemResponse, error)
	// UseItem decrements the stack count of an item by one. When the
	// remaining amount reaches zero the row is deleted. Consumables only;
	// equipment items are not stackable on rAthena's wire.
	UseItem(context.Context, *UseItemRequest) (*UseItemResponse, error)
	// BuyFromShop commits one or more buy orders from an NPC shop for the
	// given character. The gateway computes the unit prices from its own
	// shop catalog (D-204); the server never trusts a client-supplied
	// price. Returns a BuyResult outcome + the post-transaction zeny
	// balance (0 on non-OK).
	BuyFromShop(context.Context, *BuyFromShopRequest) (*BuyFromShopResponse, error)
	// SellToShop credits the character for one or more inventory items
	// sold to an NPC shop. The inv_id is the inventory row id (not a
	// wire slot). Returns a SellResult outcome + the post-transaction
	// zeny balance (0 on non-OK).
	SellToShop(context.Context, *SellToShopRequest) (*SellToShopResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedIdentityServiceServer) GetCharacterList(context.Context, *GetCharacterListRequest) (*GetCharacterListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCharacterList not implemented")
}
func (UnimplementedIdentityServiceServer) GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCharacter not implemented")
}
func (UnimplementedIdentityServiceServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedIdentityServiceServer) EquipItem(context.Context, *EquipItemRequest) (*EquipItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EquipItem not implemented")
}
func (UnimplementedIdentityServiceServer) UnequipItem(context.Context, *UnequipItemRequest) (*UnequipItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnequipItem not implemented")
}
func (UnimplementedIdentityServiceServer) UseItem(context.Context, *UseItemRequest) (*UseItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UseItem not implemented")
}
func (UnimplementedIdentityServiceServer) BuyFromShop(context.Context, *BuyFromShopRequest) (*BuyFromShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuyFromShop not implemented")
}
func (UnimplementedIdentityServiceServer) SellToShop(context.Context, *SellToShopRequest) (*SellToShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SellToShop not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetCharacterList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetCharacterList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetCharacterList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetCharacterList(ctx, req.(*GetCharacterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_EquipItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).EquipItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_EquipItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).EquipItem(ctx, req.(*EquipItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UnequipItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnequipItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UnequipItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UnequipItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UnequipItem(ctx, req.(*UnequipItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UseItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UseItem(ctx, req.(*UseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_BuyFromShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyFromShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).BuyFromShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_BuyFromShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).BuyFromShop(ctx, req.(*BuyFromShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SellToShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellToShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SellToShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SellToShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SellToShop(ctx, req.(*SellToShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _IdentityService_Authenticate_Handler,
		},
		{
			MethodName: "GetCharacterList",
			Handler:    _IdentityService_GetCharacterList_Handler,
		},
		{
			MethodName: "GetCharacter",
			Handler:    _IdentityService_GetCharacter_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _IdentityService_GetInventory_Handler,
		},
		{
			MethodName: "EquipItem",
			Handler:    _IdentityService_EquipItem_Handler,
		},
		{
			MethodName: "UnequipItem",
			Handler:    _IdentityService_UnequipItem_Handler,
		},
		{
			MethodName: "UseItem",
			Handler:    _IdentityService_UseItem_Handler,
		},
		{
			MethodName: "BuyFromShop",
			Handler:    _IdentityService_BuyFromShop_Handler,
		},
		{
			MethodName: "SellToShop",
			Handler:    _IdentityService_SellToShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/v1/identity.proto",
}
