// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: identity/v1/identity.proto

package identityv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthMethod identifies which CA_LOGIN variant the client sent.
type AuthMethod int32

const (
	AuthMethod_AUTH_METHOD_UNSPECIFIED AuthMethod = 0
	AuthMethod_AUTH_METHOD_PASSWORD    AuthMethod = 1 // CA_LOGIN 0x0064 (plaintext password)
	AuthMethod_AUTH_METHOD_MD5         AuthMethod = 2 // CA_LOGIN2 0x01dd (MD5 password)
	AuthMethod_AUTH_METHOD_MD5_SALTED  AuthMethod = 3 // CA_LOGIN3/4 0x01fa/0x027c
	AuthMethod_AUTH_METHOD_PCBANG      AuthMethod = 4 // CA_LOGIN_PCBANG 0x0277
	AuthMethod_AUTH_METHOD_CHANNEL     AuthMethod = 5 // CA_LOGIN_CHANNEL 0x02b0
	AuthMethod_AUTH_METHOD_SSO         AuthMethod = 6 // CA_SSO_LOGIN_REQ 0x0825
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "AUTH_METHOD_UNSPECIFIED",
		1: "AUTH_METHOD_PASSWORD",
		2: "AUTH_METHOD_MD5",
		3: "AUTH_METHOD_MD5_SALTED",
		4: "AUTH_METHOD_PCBANG",
		5: "AUTH_METHOD_CHANNEL",
		6: "AUTH_METHOD_SSO",
	}
	AuthMethod_value = map[string]int32{
		"AUTH_METHOD_UNSPECIFIED": 0,
		"AUTH_METHOD_PASSWORD":    1,
		"AUTH_METHOD_MD5":         2,
		"AUTH_METHOD_MD5_SALTED":  3,
		"AUTH_METHOD_PCBANG":      4,
		"AUTH_METHOD_CHANNEL":     5,
		"AUTH_METHOD_SSO":         6,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[0]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type AuthResult int32

const (
	AuthResult_AUTH_RESULT_UNSPECIFIED       AuthResult = 0
	AuthResult_AUTH_RESULT_OK                AuthResult = 1
	AuthResult_AUTH_RESULT_REJECTED          AuthResult = 2 // AC_REFUSE_LOGIN — wrong credentials
	AuthResult_AUTH_RESULT_BANNED            AuthResult = 3
	AuthResult_AUTH_RESULT_ALREADY_LOGGED_IN AuthResult = 4
	AuthResult_AUTH_RESULT_SERVER_CLOSED     AuthResult = 5 // SC_NOTIFY_BAN
)

// Enum value maps for AuthResult.
var (
	AuthResult_name = map[int32]string{
		0: "AUTH_RESULT_UNSPECIFIED",
		1: "AUTH_RESULT_OK",
		2: "AUTH_RESULT_REJECTED",
		3: "AUTH_RESULT_BANNED",
		4: "AUTH_RESULT_ALREADY_LOGGED_IN",
		5: "AUTH_RESULT_SERVER_CLOSED",
	}
	AuthResult_value = map[string]int32{
		"AUTH_RESULT_UNSPECIFIED":       0,
		"AUTH_RESULT_OK":                1,
		"AUTH_RESULT_REJECTED":          2,
		"AUTH_RESULT_BANNED":            3,
		"AUTH_RESULT_ALREADY_LOGGED_IN": 4,
		"AUTH_RESULT_SERVER_CLOSED":     5,
	}
)

func (x AuthResult) Enum() *AuthResult {
	p := new(AuthResult)
	*p = x
	return p
}

func (x AuthResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthResult) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[1].Descriptor()
}

func (AuthResult) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[1]
}

func (x AuthResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthResult.Descriptor instead.
func (AuthResult) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

// BuyResult mirrors economy domain.BuyResult. UNSPECIFIED is reserved
// for "we forgot to set the result" and should never reach the wire.
type BuyResult int32

const (
	BuyResult_BUY_RESULT_UNSPECIFIED       BuyResult = 0
	BuyResult_BUY_RESULT_OK                BuyResult = 1
	BuyResult_BUY_RESULT_INSUFFICIENT_ZENY BuyResult = 2
	BuyResult_BUY_RESULT_LOCK_BUSY         BuyResult = 3
)

// Enum value maps for BuyResult.
var (
	BuyResult_name = map[int32]string{
		0: "BUY_RESULT_UNSPECIFIED",
		1: "BUY_RESULT_OK",
		2: "BUY_RESULT_INSUFFICIENT_ZENY",
		3: "BUY_RESULT_LOCK_BUSY",
	}
	BuyResult_value = map[string]int32{
		"BUY_RESULT_UNSPECIFIED":       0,
		"BUY_RESULT_OK":                1,
		"BUY_RESULT_INSUFFICIENT_ZENY": 2,
		"BUY_RESULT_LOCK_BUSY":         3,
	}
)

func (x BuyResult) Enum() *BuyResult {
	p := new(BuyResult)
	*p = x
	return p
}

func (x BuyResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuyResult) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[2].Descriptor()
}

func (BuyResult) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[2]
}

func (x BuyResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuyResult.Descriptor instead.
func (BuyResult) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

// SellResult mirrors economy domain.SellResult.
type SellResult int32

const (
	SellResult_SELL_RESULT_UNSPECIFIED  SellResult = 0
	SellResult_SELL_RESULT_OK           SellResult = 1
	SellResult_SELL_RESULT_ZENY_FULL    SellResult = 2
	SellResult_SELL_RESULT_INVALID_ITEM SellResult = 3
	SellResult_SELL_RESULT_LOCK_BUSY    SellResult = 4
)

// Enum value maps for SellResult.
var (
	SellResult_name = map[int32]string{
		0: "SELL_RESULT_UNSPECIFIED",
		1: "SELL_RESULT_OK",
		2: "SELL_RESULT_ZENY_FULL",
		3: "SELL_RESULT_INVALID_ITEM",
		4: "SELL_RESULT_LOCK_BUSY",
	}
	SellResult_value = map[string]int32{
		"SELL_RESULT_UNSPECIFIED":  0,
		"SELL_RESULT_OK":           1,
		"SELL_RESULT_ZENY_FULL":    2,
		"SELL_RESULT_INVALID_ITEM": 3,
		"SELL_RESULT_LOCK_BUSY":    4,
	}
)

func (x SellResult) Enum() *SellResult {
	p := new(SellResult)
	*p = x
	return p
}

func (x SellResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SellResult) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[3].Descriptor()
}

func (SellResult) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[3]
}

func (x SellResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SellResult.Descriptor instead.
func (SellResult) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

// StatResult mirrors the CZ_STATUS_CHANGE ack outcomes: how a stat allocation
// call succeeded or failed (rathena/src/map/clif.cpp:4283 ZC_STATUS_CHANGE_ACK).
type StatResult int32

const (
	StatResult_STAT_RESULT_UNSPECIFIED         StatResult = 0
	StatResult_STAT_RESULT_OK                  StatResult = 1
	StatResult_STAT_RESULT_INSUFFICIENT_POINTS StatResult = 2
	StatResult_STAT_RESULT_MAX_STAT            StatResult = 3
	StatResult_STAT_RESULT_INVALID_STAT        StatResult = 4
)

// Enum value maps for StatResult.
var (
	StatResult_name = map[int32]string{
		0: "STAT_RESULT_UNSPECIFIED",
		1: "STAT_RESULT_OK",
		2: "STAT_RESULT_INSUFFICIENT_POINTS",
		3: "STAT_RESULT_MAX_STAT",
		4: "STAT_RESULT_INVALID_STAT",
	}
	StatResult_value = map[string]int32{
		"STAT_RESULT_UNSPECIFIED":         0,
		"STAT_RESULT_OK":                  1,
		"STAT_RESULT_INSUFFICIENT_POINTS": 2,
		"STAT_RESULT_MAX_STAT":            3,
		"STAT_RESULT_INVALID_STAT":        4,
	}
)

func (x StatResult) Enum() *StatResult {
	p := new(StatResult)
	*p = x
	return p
}

func (x StatResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatResult) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[4].Descriptor()
}

func (StatResult) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[4]
}

func (x StatResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatResult.Descriptor instead.
func (StatResult) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                        // plaintext (AUTH_METHOD_PASSWORD) or MD5 digest
	ClientType    uint32                 `protobuf:"varint,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // kRO client type code
	Packetver     uint32                 `protobuf:"varint,4,opt,name=packetver,proto3" json:"packetver,omitempty"`                     // client PACKETVER date (e.g. 20130807)
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Method        AuthMethod             `protobuf:"varint,6,opt,name=method,proto3,enum=identity.v1.AuthMethod" json:"method,omitempty"`
	Md5Salt       []byte                 `protobuf:"bytes,7,opt,name=md5_salt,json=md5Salt,proto3" json:"md5_salt,omitempty"` // salt from CA_REQ_HASH/AC_ACK_HASH exchange (if applicable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *AuthenticateRequest) GetClientType() uint32 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *AuthenticateRequest) GetPacketver() uint32 {
	if x != nil {
		return x.Packetver
	}
	return 0
}

func (x *AuthenticateRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuthenticateRequest) GetMethod() AuthMethod {
	if x != nil {
		return x.Method
	}
	return AuthMethod_AUTH_METHOD_UNSPECIFIED
}

func (x *AuthenticateRequest) GetMd5Salt() []byte {
	if x != nil {
		return x.Md5Salt
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AuthResult             `protobuf:"varint,1,opt,name=result,proto3,enum=identity.v1.AuthResult" json:"result,omitempty"`
	ErrorCode     uint32                 `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // kRO-specific error code (0-15, 99-104)
	AccountId     uint32                 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LoginId1      uint64                 `protobuf:"fixed64,4,opt,name=login_id1,json=loginId1,proto3" json:"login_id1,omitempty"` // session token minted on success
	LoginId2      uint64                 `protobuf:"fixed64,5,opt,name=login_id2,json=loginId2,proto3" json:"login_id2,omitempty"`
	LastIp        string                 `protobuf:"bytes,6,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
	LastLogin     string                 `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	Sex           string                 `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"`     // "M", "F", or "S"
	Token         string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"` // web auth token (PACKETVER >= 20170315)
	CharServers   []*CharServerInfo      `protobuf:"bytes,10,rep,name=char_servers,json=charServers,proto3" json:"char_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetResult() AuthResult {
	if x != nil {
		return x.Result
	}
	return AuthResult_AUTH_RESULT_UNSPECIFIED
}

func (x *AuthenticateResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *AuthenticateResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AuthenticateResponse) GetLoginId1() uint64 {
	if x != nil {
		return x.LoginId1
	}
	return 0
}

func (x *AuthenticateResponse) GetLoginId2() uint64 {
	if x != nil {
		return x.LoginId2
	}
	return 0
}

func (x *AuthenticateResponse) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

func (x *AuthenticateResponse) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *AuthenticateResponse) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *AuthenticateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateResponse) GetCharServers() []*CharServerInfo {
	if x != nil {
		return x.CharServers
	}
	return nil
}

type CharServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Users         uint32                 `protobuf:"varint,4,opt,name=users,proto3" json:"users,omitempty"`
	ServerType    uint32                 `protobuf:"varint,5,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	NewDisplay    string                 `protobuf:"bytes,6,opt,name=new_display,json=newDisplay,proto3" json:"new_display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharServerInfo) Reset() {
	*x = CharServerInfo{}
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharServerInfo) ProtoMessage() {}

func (x *CharServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharServerInfo.ProtoReflect.Descriptor instead.
func (*CharServerInfo) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *CharServerInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CharServerInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CharServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharServerInfo) GetUsers() uint32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *CharServerInfo) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *CharServerInfo) GetNewDisplay() string {
	if x != nil {
		return x.NewDisplay
	}
	return ""
}

type GetCharacterListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LoginId1      uint64                 `protobuf:"fixed64,2,opt,name=login_id1,json=loginId1,proto3" json:"login_id1,omitempty"` // from AuthenticateResponse
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterListRequest) Reset() {
	*x = GetCharacterListRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterListRequest) ProtoMessage() {}

func (x *GetCharacterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterListRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterListRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterListRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetCharacterListRequest) GetLoginId1() uint64 {
	if x != nil {
		return x.LoginId1
	}
	return 0
}

func (x *GetCharacterListRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClassId       uint32                 `protobuf:"varint,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	BaseLevel     uint32                 `protobuf:"varint,5,opt,name=base_level,json=baseLevel,proto3" json:"base_level,omitempty"`
	JobLevel      uint32                 `protobuf:"varint,6,opt,name=job_level,json=jobLevel,proto3" json:"job_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterInfo) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *CharacterInfo) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CharacterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterInfo) GetClassId() uint32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *CharacterInfo) GetBaseLevel() uint32 {
	if x != nil {
		return x.BaseLevel
	}
	return 0
}

func (x *CharacterInfo) GetJobLevel() uint32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

type GetCharacterListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterInfo       `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	TotalSlots    uint32                 `protobuf:"varint,2,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	PremiumStart  uint32                 `protobuf:"varint,3,opt,name=premium_start,json=premiumStart,proto3" json:"premium_start,omitempty"`
	PremiumEnd    uint32                 `protobuf:"varint,4,opt,name=premium_end,json=premiumEnd,proto3" json:"premium_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterListResponse) Reset() {
	*x = GetCharacterListResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterListResponse) ProtoMessage() {}

func (x *GetCharacterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterListResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterListResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetCharacterListResponse) GetCharacters() []*CharacterInfo {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *GetCharacterListResponse) GetTotalSlots() uint32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *GetCharacterListResponse) GetPremiumStart() uint32 {
	if x != nil {
		return x.PremiumStart
	}
	return 0
}

func (x *GetCharacterListResponse) GetPremiumEnd() uint32 {
	if x != nil {
		return x.PremiumEnd
	}
	return 0
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetCharacterRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetCharacterRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

type CharacterDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClassId       uint32                 `protobuf:"varint,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	BaseLevel     uint32                 `protobuf:"varint,4,opt,name=base_level,json=baseLevel,proto3" json:"base_level,omitempty"`
	JobLevel      uint32                 `protobuf:"varint,5,opt,name=job_level,json=jobLevel,proto3" json:"job_level,omitempty"`
	Hp            uint32                 `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         uint32                 `protobuf:"varint,7,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Sp            uint32                 `protobuf:"varint,8,opt,name=sp,proto3" json:"sp,omitempty"`
	MaxSp         uint32                 `protobuf:"varint,9,opt,name=max_sp,json=maxSp,proto3" json:"max_sp,omitempty"`
	Hair          uint32                 `protobuf:"varint,10,opt,name=hair,proto3" json:"hair,omitempty"`
	HairColor     uint32                 `protobuf:"varint,11,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`
	ClothesColor  uint32                 `protobuf:"varint,12,opt,name=clothes_color,json=clothesColor,proto3" json:"clothes_color,omitempty"`
	Weapon        uint32                 `protobuf:"varint,13,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Shield        uint32                 `protobuf:"varint,14,opt,name=shield,proto3" json:"shield,omitempty"`
	HeadTop       uint32                 `protobuf:"varint,15,opt,name=head_top,json=headTop,proto3" json:"head_top,omitempty"`
	HeadMid       uint32                 `protobuf:"varint,16,opt,name=head_mid,json=headMid,proto3" json:"head_mid,omitempty"`
	HeadBottom    uint32                 `protobuf:"varint,17,opt,name=head_bottom,json=headBottom,proto3" json:"head_bottom,omitempty"`
	Robe          uint32                 `protobuf:"varint,18,opt,name=robe,proto3" json:"robe,omitempty"`
	Sex           uint32                 `protobuf:"varint,19,opt,name=sex,proto3" json:"sex,omitempty"`
	Str           uint32                 `protobuf:"varint,20,opt,name=str,proto3" json:"str,omitempty"`
	Agi           uint32                 `protobuf:"varint,21,opt,name=agi,proto3" json:"agi,omitempty"`
	Vit           uint32                 `protobuf:"varint,22,opt,name=vit,proto3" json:"vit,omitempty"`
	Int           uint32                 `protobuf:"varint,23,opt,name=int,proto3" json:"int,omitempty"`
	Dex           uint32                 `protobuf:"varint,24,opt,name=dex,proto3" json:"dex,omitempty"`
	Luk           uint32                 `protobuf:"varint,25,opt,name=luk,proto3" json:"luk,omitempty"`
	StatusPoint   uint32                 `protobuf:"varint,26,opt,name=status_point,json=statusPoint,proto3" json:"status_point,omitempty"`
	SkillPoint    uint32                 `protobuf:"varint,27,opt,name=skill_point,json=skillPoint,proto3" json:"skill_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterDetail) Reset() {
	*x = CharacterDetail{}
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterDetail) ProtoMessage() {}

func (x *CharacterDetail) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterDetail.ProtoReflect.Descriptor instead.
func (*CharacterDetail) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterDetail) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *CharacterDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterDetail) GetClassId() uint32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *CharacterDetail) GetBaseLevel() uint32 {
	if x != nil {
		return x.BaseLevel
	}
	return 0
}

func (x *CharacterDetail) GetJobLevel() uint32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

func (x *CharacterDetail) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CharacterDetail) GetMaxHp() uint32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *CharacterDetail) GetSp() uint32 {
	if x != nil {
		return x.Sp
	}
	return 0
}

func (x *CharacterDetail) GetMaxSp() uint32 {
	if x != nil {
		return x.MaxSp
	}
	return 0
}

func (x *CharacterDetail) GetHair() uint32 {
	if x != nil {
		return x.Hair
	}
	return 0
}

func (x *CharacterDetail) GetHairColor() uint32 {
	if x != nil {
		return x.HairColor
	}
	return 0
}

func (x *CharacterDetail) GetClothesColor() uint32 {
	if x != nil {
		return x.ClothesColor
	}
	return 0
}

func (x *CharacterDetail) GetWeapon() uint32 {
	if x != nil {
		return x.Weapon
	}
	return 0
}

func (x *CharacterDetail) GetShield() uint32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *CharacterDetail) GetHeadTop() uint32 {
	if x != nil {
		return x.HeadTop
	}
	return 0
}

func (x *CharacterDetail) GetHeadMid() uint32 {
	if x != nil {
		return x.HeadMid
	}
	return 0
}

func (x *CharacterDetail) GetHeadBottom() uint32 {
	if x != nil {
		return x.HeadBottom
	}
	return 0
}

func (x *CharacterDetail) GetRobe() uint32 {
	if x != nil {
		return x.Robe
	}
	return 0
}

func (x *CharacterDetail) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CharacterDetail) GetStr() uint32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *CharacterDetail) GetAgi() uint32 {
	if x != nil {
		return x.Agi
	}
	return 0
}

func (x *CharacterDetail) GetVit() uint32 {
	if x != nil {
		return x.Vit
	}
	return 0
}

func (x *CharacterDetail) GetInt() uint32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *CharacterDetail) GetDex() uint32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *CharacterDetail) GetLuk() uint32 {
	if x != nil {
		return x.Luk
	}
	return 0
}

func (x *CharacterDetail) GetStatusPoint() uint32 {
	if x != nil {
		return x.StatusPoint
	}
	return 0
}

func (x *CharacterDetail) GetSkillPoint() uint32 {
	if x != nil {
		return x.SkillPoint
	}
	return 0
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Character     *CharacterDetail       `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *GetCharacterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCharacterResponse) GetCharacter() *CharacterDetail {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *GetCharacterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetInventoryRequest asks for every inventory item belonging to (account_id, char_id).
// The account_id is a defensive cross-check; today the inventory is keyed
// only by char_id, but carrying account_id lets the service refuse a
// cross-account fetch before any DB round-trip.
type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *GetInventoryRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetInventoryRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

// InventoryItem is the wire-relevant subset of `inventory` (rathena
// main.sql). Cards, refine bless/curse, options, expire_time, favorite,
// bound, unique_id, equip_switch and enchantgrade are omitted for now
// — they can be added as separate proto fields without breaking the
// wire layout (they live at higher field numbers).
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               // `id` — primary key
	Nameid        uint32                 `protobuf:"varint,2,opt,name=nameid,proto3" json:"nameid,omitempty"`       // `nameid` — item_db.yml id
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`       // `amount` — stack count
	Equip         uint32                 `protobuf:"varint,4,opt,name=equip,proto3" json:"equip,omitempty"`         // `equip` — EQP_* bitmask; 0 = in grid
	Identify      uint32                 `protobuf:"varint,5,opt,name=identify,proto3" json:"identify,omitempty"`   // `identify` — 1 = identified
	Refine        uint32                 `protobuf:"varint,6,opt,name=refine,proto3" json:"refine,omitempty"`       // `refine` — +0..+10
	Attribute     uint32                 `protobuf:"varint,7,opt,name=attribute,proto3" json:"attribute,omitempty"` // `attribute` — broken / elemental flag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_identity_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *InventoryItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InventoryItem) GetNameid() uint32 {
	if x != nil {
		return x.Nameid
	}
	return 0
}

func (x *InventoryItem) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InventoryItem) GetEquip() uint32 {
	if x != nil {
		return x.Equip
	}
	return 0
}

func (x *InventoryItem) GetIdentify() uint32 {
	if x != nil {
		return x.Identify
	}
	return 0
}

func (x *InventoryItem) GetRefine() uint32 {
	if x != nil {
		return x.Refine
	}
	return 0
}

func (x *InventoryItem) GetAttribute() uint32 {
	if x != nil {
		return x.Attribute
	}
	return 0
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *GetInventoryResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type EquipItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EquipPosition uint32                 `protobuf:"varint,4,opt,name=equip_position,json=equipPosition,proto3" json:"equip_position,omitempty"` // EQP_* bitmask (pc.h)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItemRequest) Reset() {
	*x = EquipItemRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemRequest) ProtoMessage() {}

func (x *EquipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemRequest.ProtoReflect.Descriptor instead.
func (*EquipItemRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *EquipItemRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *EquipItemRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *EquipItemRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipItemRequest) GetEquipPosition() uint32 {
	if x != nil {
		return x.EquipPosition
	}
	return 0
}

type EquipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EquipPosition uint32                 `protobuf:"varint,3,opt,name=equip_position,json=equipPosition,proto3" json:"equip_position,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // populated when success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItemResponse) Reset() {
	*x = EquipItemResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemResponse) ProtoMessage() {}

func (x *EquipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemResponse.ProtoReflect.Descriptor instead.
func (*EquipItemResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *EquipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EquipItemResponse) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipItemResponse) GetEquipPosition() uint32 {
	if x != nil {
		return x.EquipPosition
	}
	return 0
}

func (x *EquipItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnequipItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemRequest) Reset() {
	*x = UnequipItemRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemRequest) ProtoMessage() {}

func (x *UnequipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemRequest.ProtoReflect.Descriptor instead.
func (*UnequipItemRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *UnequipItemRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UnequipItemRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *UnequipItemRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type UnequipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EquipPosition uint32                 `protobuf:"varint,3,opt,name=equip_position,json=equipPosition,proto3" json:"equip_position,omitempty"` // the EQP_* bitmask before the row was cleared
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemResponse) Reset() {
	*x = UnequipItemResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemResponse) ProtoMessage() {}

func (x *UnequipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemResponse.ProtoReflect.Descriptor instead.
func (*UnequipItemResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *UnequipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnequipItemResponse) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UnequipItemResponse) GetEquipPosition() uint32 {
	if x != nil {
		return x.EquipPosition
	}
	return 0
}

func (x *UnequipItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemRequest) Reset() {
	*x = UseItemRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRequest) ProtoMessage() {}

func (x *UseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRequest.ProtoReflect.Descriptor instead.
func (*UseItemRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *UseItemRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UseItemRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *UseItemRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type UseItemResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemId          uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	RemainingAmount uint32                 `protobuf:"varint,3,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"` // stack size after the use, 0 if row was deleted
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UseItemResponse) Reset() {
	*x = UseItemResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResponse) ProtoMessage() {}

func (x *UseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResponse.ProtoReflect.Descriptor instead.
func (*UseItemResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *UseItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseItemResponse) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseItemResponse) GetRemainingAmount() uint32 {
	if x != nil {
		return x.RemainingAmount
	}
	return 0
}

func (x *UseItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ShopOrder is a single line item in a buy transaction. UnitPrice is
// carried over the wire so the server has a stable receipt even if the
// gateway recomputes it; the server still validates against its own
// catalog (D-204) before committing.
type ShopOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UnitPrice     uint32                 `protobuf:"varint,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopOrder) Reset() {
	*x = ShopOrder{}
	mi := &file_identity_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopOrder) ProtoMessage() {}

func (x *ShopOrder) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopOrder.ProtoReflect.Descriptor instead.
func (*ShopOrder) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *ShopOrder) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopOrder) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ShopOrder) GetUnitPrice() uint32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

// SellLine is a single line item in a sell transaction. inv_id is the
// inventory row id (the `id` column of the `inventory` table), not a
// wire slot index.
type SellLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvId         uint32                 `protobuf:"varint,1,opt,name=inv_id,json=invId,proto3" json:"inv_id,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UnitPrice     uint32                 `protobuf:"varint,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellLine) Reset() {
	*x = SellLine{}
	mi := &file_identity_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellLine) ProtoMessage() {}

func (x *SellLine) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellLine.ProtoReflect.Descriptor instead.
func (*SellLine) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{19}
}

func (x *SellLine) GetInvId() uint32 {
	if x != nil {
		return x.InvId
	}
	return 0
}

func (x *SellLine) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SellLine) GetUnitPrice() uint32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type BuyFromShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // defensive cross-check (mirror GetInventoryRequest)
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Orders        []*ShopOrder           `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyFromShopRequest) Reset() {
	*x = BuyFromShopRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyFromShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyFromShopRequest) ProtoMessage() {}

func (x *BuyFromShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyFromShopRequest.ProtoReflect.Descriptor instead.
func (*BuyFromShopRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{20}
}

func (x *BuyFromShopRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *BuyFromShopRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *BuyFromShopRequest) GetOrders() []*ShopOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type BuyFromShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        BuyResult              `protobuf:"varint,1,opt,name=result,proto3,enum=identity.v1.BuyResult" json:"result,omitempty"`
	NewZeny       uint32                 `protobuf:"varint,2,opt,name=new_zeny,json=newZeny,proto3" json:"new_zeny,omitempty"` // post-tx balance (0 on non-OK); gateway emits ZC_*PAR_CHANGE
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                     // populated only on transport/internal failure paths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyFromShopResponse) Reset() {
	*x = BuyFromShopResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyFromShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyFromShopResponse) ProtoMessage() {}

func (x *BuyFromShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyFromShopResponse.ProtoReflect.Descriptor instead.
func (*BuyFromShopResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{21}
}

func (x *BuyFromShopResponse) GetResult() BuyResult {
	if x != nil {
		return x.Result
	}
	return BuyResult_BUY_RESULT_UNSPECIFIED
}

func (x *BuyFromShopResponse) GetNewZeny() uint32 {
	if x != nil {
		return x.NewZeny
	}
	return 0
}

func (x *BuyFromShopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SellToShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Sales         []*SellLine            `protobuf:"bytes,3,rep,name=sales,proto3" json:"sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellToShopRequest) Reset() {
	*x = SellToShopRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellToShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellToShopRequest) ProtoMessage() {}

func (x *SellToShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellToShopRequest.ProtoReflect.Descriptor instead.
func (*SellToShopRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{22}
}

func (x *SellToShopRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SellToShopRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *SellToShopRequest) GetSales() []*SellLine {
	if x != nil {
		return x.Sales
	}
	return nil
}

type SellToShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        SellResult             `protobuf:"varint,1,opt,name=result,proto3,enum=identity.v1.SellResult" json:"result,omitempty"`
	NewZeny       uint32                 `protobuf:"varint,2,opt,name=new_zeny,json=newZeny,proto3" json:"new_zeny,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellToShopResponse) Reset() {
	*x = SellToShopResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellToShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellToShopResponse) ProtoMessage() {}

func (x *SellToShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellToShopResponse.ProtoReflect.Descriptor instead.
func (*SellToShopResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{23}
}

func (x *SellToShopResponse) GetResult() SellResult {
	if x != nil {
		return x.Result
	}
	return SellResult_SELL_RESULT_UNSPECIFIED
}

func (x *SellToShopResponse) GetNewZeny() uint32 {
	if x != nil {
		return x.NewZeny
	}
	return 0
}

func (x *SellToShopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApplyLevelUpRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccountId           uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId              uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	FromBaseLevel       uint32                 `protobuf:"varint,3,opt,name=from_base_level,json=fromBaseLevel,proto3" json:"from_base_level,omitempty"`                   // expected current level (optimistic lock guard)
	ToBaseLevel         uint32                 `protobuf:"varint,4,opt,name=to_base_level,json=toBaseLevel,proto3" json:"to_base_level,omitempty"`                         // new level after the gain
	GrantedStatusPoints uint32                 `protobuf:"varint,5,opt,name=granted_status_points,json=grantedStatusPoints,proto3" json:"granted_status_points,omitempty"` // status points awarded by the level-up(s)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyLevelUpRequest) Reset() {
	*x = ApplyLevelUpRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyLevelUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyLevelUpRequest) ProtoMessage() {}

func (x *ApplyLevelUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyLevelUpRequest.ProtoReflect.Descriptor instead.
func (*ApplyLevelUpRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{24}
}

func (x *ApplyLevelUpRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ApplyLevelUpRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *ApplyLevelUpRequest) GetFromBaseLevel() uint32 {
	if x != nil {
		return x.FromBaseLevel
	}
	return 0
}

func (x *ApplyLevelUpRequest) GetToBaseLevel() uint32 {
	if x != nil {
		return x.ToBaseLevel
	}
	return 0
}

func (x *ApplyLevelUpRequest) GetGrantedStatusPoints() uint32 {
	if x != nil {
		return x.GrantedStatusPoints
	}
	return 0
}

type ApplyLevelUpResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBaseLevel   uint32                 `protobuf:"varint,2,opt,name=new_base_level,json=newBaseLevel,proto3" json:"new_base_level,omitempty"`       // actual current level after apply (re-read)
	NewStatusPoint uint32                 `protobuf:"varint,3,opt,name=new_status_point,json=newStatusPoint,proto3" json:"new_status_point,omitempty"` // actual status_point after apply (re-read)
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                            // populated on transport/internal failure
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyLevelUpResponse) Reset() {
	*x = ApplyLevelUpResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyLevelUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyLevelUpResponse) ProtoMessage() {}

func (x *ApplyLevelUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyLevelUpResponse.ProtoReflect.Descriptor instead.
func (*ApplyLevelUpResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{25}
}

func (x *ApplyLevelUpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyLevelUpResponse) GetNewBaseLevel() uint32 {
	if x != nil {
		return x.NewBaseLevel
	}
	return 0
}

func (x *ApplyLevelUpResponse) GetNewStatusPoint() uint32 {
	if x != nil {
		return x.NewStatusPoint
	}
	return 0
}

func (x *ApplyLevelUpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AllocateStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CharId        uint32                 `protobuf:"varint,2,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	StatId        uint32                 `protobuf:"varint,3,opt,name=stat_id,json=statId,proto3" json:"stat_id,omitempty"` // rAthena SP_STR..SP_LUK (13..18)
	Amount        uint32                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`               // steps to raise (usually 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateStatRequest) Reset() {
	*x = AllocateStatRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateStatRequest) ProtoMessage() {}

func (x *AllocateStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateStatRequest.ProtoReflect.Descriptor instead.
func (*AllocateStatRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{26}
}

func (x *AllocateStatRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AllocateStatRequest) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *AllocateStatRequest) GetStatId() uint32 {
	if x != nil {
		return x.StatId
	}
	return 0
}

func (x *AllocateStatRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AllocateStatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         StatResult             `protobuf:"varint,1,opt,name=result,proto3,enum=identity.v1.StatResult" json:"result,omitempty"`
	StatId         uint32                 `protobuf:"varint,2,opt,name=stat_id,json=statId,proto3" json:"stat_id,omitempty"`
	NewValue       uint32                 `protobuf:"varint,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`                     // stat value after allocation (0 on non-OK)
	NewStatusPoint uint32                 `protobuf:"varint,4,opt,name=new_status_point,json=newStatusPoint,proto3" json:"new_status_point,omitempty"` // remaining status_point after allocation
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                            // populated only on transport/internal failure
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllocateStatResponse) Reset() {
	*x = AllocateStatResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateStatResponse) ProtoMessage() {}

func (x *AllocateStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateStatResponse.ProtoReflect.Descriptor instead.
func (*AllocateStatResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{27}
}

func (x *AllocateStatResponse) GetResult() StatResult {
	if x != nil {
		return x.Result
	}
	return StatResult_STAT_RESULT_UNSPECIFIED
}

func (x *AllocateStatResponse) GetStatId() uint32 {
	if x != nil {
		return x.StatId
	}
	return 0
}

func (x *AllocateStatResponse) GetNewValue() uint32 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

func (x *AllocateStatResponse) GetNewStatusPoint() uint32 {
	if x != nil {
		return x.NewStatusPoint
	}
	return 0
}

func (x *AllocateStatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\videntity.v1\"\xf5\x01\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\x12\x1f\n" +
	"\vclient_type\x18\x03 \x01(\rR\n" +
	"clientType\x12\x1c\n" +
	"\tpacketver\x18\x04 \x01(\rR\tpacketver\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12/\n" +
	"\x06method\x18\x06 \x01(\x0e2\x17.identity.v1.AuthMethodR\x06method\x12\x19\n" +
	"\bmd5_salt\x18\a \x01(\fR\amd5Salt\"\xdf\x02\n" +
	"\x14AuthenticateResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x17.identity.v1.AuthResultR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\rR\terrorCode\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\rR\taccountId\x12\x1b\n" +
	"\tlogin_id1\x18\x04 \x01(\x06R\bloginId1\x12\x1b\n" +
	"\tlogin_id2\x18\x05 \x01(\x06R\bloginId2\x12\x17\n" +
	"\alast_ip\x18\x06 \x01(\tR\x06lastIp\x12\x1d\n" +
	"\n" +
	"last_login\x18\a \x01(\tR\tlastLogin\x12\x10\n" +
	"\x03sex\x18\b \x01(\tR\x03sex\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x12>\n" +
	"\fchar_servers\x18\n" +
	" \x03(\v2\x1b.identity.v1.CharServerInfoR\vcharServers\"\xa0\x01\n" +
	"\x0eCharServerInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05users\x18\x04 \x01(\rR\x05users\x12\x1f\n" +
	"\vserver_type\x18\x05 \x01(\rR\n" +
	"serverType\x12\x1f\n" +
	"\vnew_display\x18\x06 \x01(\tR\n" +
	"newDisplay\"g\n" +
	"\x17GetCharacterListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x1b\n" +
	"\tlogin_id1\x18\x02 \x01(\x06R\bloginId1\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\"\xa7\x01\n" +
	"\rCharacterInfo\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\rR\x04slot\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bclass_id\x18\x04 \x01(\rR\aclassId\x12\x1d\n" +
	"\n" +
	"base_level\x18\x05 \x01(\rR\tbaseLevel\x12\x1b\n" +
	"\tjob_level\x18\x06 \x01(\rR\bjobLevel\"\xbd\x01\n" +
	"\x18GetCharacterListResponse\x12:\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1a.identity.v1.CharacterInfoR\n" +
	"characters\x12\x1f\n" +
	"\vtotal_slots\x18\x02 \x01(\rR\n" +
	"totalSlots\x12#\n" +
	"\rpremium_start\x18\x03 \x01(\rR\fpremiumStart\x12\x1f\n" +
	"\vpremium_end\x18\x04 \x01(\rR\n" +
	"premiumEnd\"M\n" +
	"\x13GetCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\"\x98\x05\n" +
	"\x0fCharacterDetail\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\rR\aclassId\x12\x1d\n" +
	"\n" +
	"base_level\x18\x04 \x01(\rR\tbaseLevel\x12\x1b\n" +
	"\tjob_level\x18\x05 \x01(\rR\bjobLevel\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\rR\x02hp\x12\x15\n" +
	"\x06max_hp\x18\a \x01(\rR\x05maxHp\x12\x0e\n" +
	"\x02sp\x18\b \x01(\rR\x02sp\x12\x15\n" +
	"\x06max_sp\x18\t \x01(\rR\x05maxSp\x12\x12\n" +
	"\x04hair\x18\n" +
	" \x01(\rR\x04hair\x12\x1d\n" +
	"\n" +
	"hair_color\x18\v \x01(\rR\thairColor\x12#\n" +
	"\rclothes_color\x18\f \x01(\rR\fclothesColor\x12\x16\n" +
	"\x06weapon\x18\r \x01(\rR\x06weapon\x12\x16\n" +
	"\x06shield\x18\x0e \x01(\rR\x06shield\x12\x19\n" +
	"\bhead_top\x18\x0f \x01(\rR\aheadTop\x12\x19\n" +
	"\bhead_mid\x18\x10 \x01(\rR\aheadMid\x12\x1f\n" +
	"\vhead_bottom\x18\x11 \x01(\rR\n" +
	"headBottom\x12\x12\n" +
	"\x04robe\x18\x12 \x01(\rR\x04robe\x12\x10\n" +
	"\x03sex\x18\x13 \x01(\rR\x03sex\x12\x10\n" +
	"\x03str\x18\x14 \x01(\rR\x03str\x12\x10\n" +
	"\x03agi\x18\x15 \x01(\rR\x03agi\x12\x10\n" +
	"\x03vit\x18\x16 \x01(\rR\x03vit\x12\x10\n" +
	"\x03int\x18\x17 \x01(\rR\x03int\x12\x10\n" +
	"\x03dex\x18\x18 \x01(\rR\x03dex\x12\x10\n" +
	"\x03luk\x18\x19 \x01(\rR\x03luk\x12!\n" +
	"\fstatus_point\x18\x1a \x01(\rR\vstatusPoint\x12\x1f\n" +
	"\vskill_point\x18\x1b \x01(\rR\n" +
	"skillPoint\"\x82\x01\n" +
	"\x14GetCharacterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\tcharacter\x18\x02 \x01(\v2\x1c.identity.v1.CharacterDetailR\tcharacter\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x13GetInventoryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\"\xb7\x01\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06nameid\x18\x02 \x01(\rR\x06nameid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x14\n" +
	"\x05equip\x18\x04 \x01(\rR\x05equip\x12\x1a\n" +
	"\bidentify\x18\x05 \x01(\rR\bidentify\x12\x16\n" +
	"\x06refine\x18\x06 \x01(\rR\x06refine\x12\x1c\n" +
	"\tattribute\x18\a \x01(\rR\tattribute\"H\n" +
	"\x14GetInventoryResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.identity.v1.InventoryItemR\x05items\"\x8a\x01\n" +
	"\x10EquipItemRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\rR\x06itemId\x12%\n" +
	"\x0eequip_position\x18\x04 \x01(\rR\requipPosition\"\x83\x01\n" +
	"\x11EquipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12%\n" +
	"\x0eequip_position\x18\x03 \x01(\rR\requipPosition\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"e\n" +
	"\x12UnequipItemRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\rR\x06itemId\"\x85\x01\n" +
	"\x13UnequipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12%\n" +
	"\x0eequip_position\x18\x03 \x01(\rR\requipPosition\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"a\n" +
	"\x0eUseItemRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\rR\x06itemId\"\x85\x01\n" +
	"\x0fUseItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12)\n" +
	"\x10remaining_amount\x18\x03 \x01(\rR\x0fremainingAmount\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"[\n" +
	"\tShopOrder\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\rR\tunitPrice\"X\n" +
	"\bSellLine\x12\x15\n" +
	"\x06inv_id\x18\x01 \x01(\rR\x05invId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\rR\tunitPrice\"|\n" +
	"\x12BuyFromShopRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12.\n" +
	"\x06orders\x18\x03 \x03(\v2\x16.identity.v1.ShopOrderR\x06orders\"v\n" +
	"\x13BuyFromShopResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\x0e2\x16.identity.v1.BuyResultR\x06result\x12\x19\n" +
	"\bnew_zeny\x18\x02 \x01(\rR\anewZeny\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"x\n" +
	"\x11SellToShopRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12+\n" +
	"\x05sales\x18\x03 \x03(\v2\x15.identity.v1.SellLineR\x05sales\"v\n" +
	"\x12SellToShopResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x17.identity.v1.SellResultR\x06result\x12\x19\n" +
	"\bnew_zeny\x18\x02 \x01(\rR\anewZeny\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xcd\x01\n" +
	"\x13ApplyLevelUpRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12&\n" +
	"\x0ffrom_base_level\x18\x03 \x01(\rR\rfromBaseLevel\x12\"\n" +
	"\rto_base_level\x18\x04 \x01(\rR\vtoBaseLevel\x122\n" +
	"\x15granted_status_points\x18\x05 \x01(\rR\x13grantedStatusPoints\"\x96\x01\n" +
	"\x14ApplyLevelUpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0enew_base_level\x18\x02 \x01(\rR\fnewBaseLevel\x12(\n" +
	"\x10new_status_point\x18\x03 \x01(\rR\x0enewStatusPoint\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"~\n" +
	"\x13AllocateStatRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\achar_id\x18\x02 \x01(\rR\x06charId\x12\x17\n" +
	"\astat_id\x18\x03 \x01(\rR\x06statId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\rR\x06amount\"\xbd\x01\n" +
	"\x14AllocateStatResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x17.identity.v1.StatResultR\x06result\x12\x17\n" +
	"\astat_id\x18\x02 \x01(\rR\x06statId\x12\x1b\n" +
	"\tnew_value\x18\x03 \x01(\rR\bnewValue\x12(\n" +
	"\x10new_status_point\x18\x04 \x01(\rR\x0enewStatusPoint\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*\xba\x01\n" +
	"\n" +
	"AuthMethod\x12\x1b\n" +
	"\x17AUTH_METHOD_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUTH_METHOD_PASSWORD\x10\x01\x12\x13\n" +
	"\x0fAUTH_METHOD_MD5\x10\x02\x12\x1a\n" +
	"\x16AUTH_METHOD_MD5_SALTED\x10\x03\x12\x16\n" +
	"\x12AUTH_METHOD_PCBANG\x10\x04\x12\x17\n" +
	"\x13AUTH_METHOD_CHANNEL\x10\x05\x12\x13\n" +
	"\x0fAUTH_METHOD_SSO\x10\x06*\xb1\x01\n" +
	"\n" +
	"AuthResult\x12\x1b\n" +
	"\x17AUTH_RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUTH_RESULT_OK\x10\x01\x12\x18\n" +
	"\x14AUTH_RESULT_REJECTED\x10\x02\x12\x16\n" +
	"\x12AUTH_RESULT_BANNED\x10\x03\x12!\n" +
	"\x1dAUTH_RESULT_ALREADY_LOGGED_IN\x10\x04\x12\x1d\n" +
	"\x19AUTH_RESULT_SERVER_CLOSED\x10\x05*v\n" +
	"\tBuyResult\x12\x1a\n" +
	"\x16BUY_RESULT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rBUY_RESULT_OK\x10\x01\x12 \n" +
	"\x1cBUY_RESULT_INSUFFICIENT_ZENY\x10\x02\x12\x18\n" +
	"\x14BUY_RESULT_LOCK_BUSY\x10\x03*\x91\x01\n" +
	"\n" +
	"SellResult\x12\x1b\n" +
	"\x17SELL_RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSELL_RESULT_OK\x10\x01\x12\x19\n" +
	"\x15SELL_RESULT_ZENY_FULL\x10\x02\x12\x1c\n" +
	"\x18SELL_RESULT_INVALID_ITEM\x10\x03\x12\x19\n" +
	"\x15SELL_RESULT_LOCK_BUSY\x10\x04*\x9a\x01\n" +
	"\n" +
	"StatResult\x12\x1b\n" +
	"\x17STAT_RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTAT_RESULT_OK\x10\x01\x12#\n" +
	"\x1fSTAT_RESULT_INSUFFICIENT_POINTS\x10\x02\x12\x18\n" +
	"\x14STAT_RESULT_MAX_STAT\x10\x03\x12\x1c\n" +
	"\x18STAT_RESULT_INVALID_STAT\x10\x042\xa0\a\n" +
	"\x0fIdentityService\x12S\n" +
	"\fAuthenticate\x12 .identity.v1.AuthenticateRequest\x1a!.identity.v1.AuthenticateResponse\x12_\n" +
	"\x10GetCharacterList\x12$.identity.v1.GetCharacterListRequest\x1a%.identity.v1.GetCharacterListResponse\x12S\n" +
	"\fGetCharacter\x12 .identity.v1.GetCharacterRequest\x1a!.identity.v1.GetCharacterResponse\x12S\n" +
	"\fGetInventory\x12 .identity.v1.GetInventoryRequest\x1a!.identity.v1.GetInventoryResponse\x12J\n" +
	"\tEquipItem\x12\x1d.identity.v1.EquipItemRequest\x1a\x1e.identity.v1.EquipItemResponse\x12P\n" +
	"\vUnequipItem\x12\x1f.identity.v1.UnequipItemRequest\x1a .identity.v1.UnequipItemResponse\x12D\n" +
	"\aUseItem\x12\x1b.identity.v1.UseItemRequest\x1a\x1c.identity.v1.UseItemResponse\x12P\n" +
	"\vBuyFromShop\x12\x1f.identity.v1.BuyFromShopRequest\x1a .identity.v1.BuyFromShopResponse\x12M\n" +
	"\n" +
	"SellToShop\x12\x1e.identity.v1.SellToShopRequest\x1a\x1f.identity.v1.SellToShopResponse\x12S\n" +
	"\fApplyLevelUp\x12 .identity.v1.ApplyLevelUpRequest\x1a!.identity.v1.ApplyLevelUpResponse\x12S\n" +
	"\fAllocateStat\x12 .identity.v1.AllocateStatRequest\x1a!.identity.v1.AllocateStatResponseB:Z8github.com/bouroo/goAthena/api/pb/identity/v1;identityv1b\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_identity_v1_identity_proto_goTypes = []any{
	(AuthMethod)(0),                  // 0: identity.v1.AuthMethod
	(AuthResult)(0),                  // 1: identity.v1.AuthResult
	(BuyResult)(0),                   // 2: identity.v1.BuyResult
	(SellResult)(0),                  // 3: identity.v1.SellResult
	(StatResult)(0),                  // 4: identity.v1.StatResult
	(*AuthenticateRequest)(nil),      // 5: identity.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),     // 6: identity.v1.AuthenticateResponse
	(*CharServerInfo)(nil),           // 7: identity.v1.CharServerInfo
	(*GetCharacterListRequest)(nil),  // 8: identity.v1.GetCharacterListRequest
	(*CharacterInfo)(nil),            // 9: identity.v1.CharacterInfo
	(*GetCharacterListResponse)(nil), // 10: identity.v1.GetCharacterListResponse
	(*GetCharacterRequest)(nil),      // 11: identity.v1.GetCharacterRequest
	(*CharacterDetail)(nil),          // 12: identity.v1.CharacterDetail
	(*GetCharacterResponse)(nil),     // 13: identity.v1.GetCharacterResponse
	(*GetInventoryRequest)(nil),      // 14: identity.v1.GetInventoryRequest
	(*InventoryItem)(nil),            // 15: identity.v1.InventoryItem
	(*GetInventoryResponse)(nil),     // 16: identity.v1.GetInventoryResponse
	(*EquipItemRequest)(nil),         // 17: identity.v1.EquipItemRequest
	(*EquipItemResponse)(nil),        // 18: identity.v1.EquipItemResponse
	(*UnequipItemRequest)(nil),       // 19: identity.v1.UnequipItemRequest
	(*UnequipItemResponse)(nil),      // 20: identity.v1.UnequipItemResponse
	(*UseItemRequest)(nil),           // 21: identity.v1.UseItemRequest
	(*UseItemResponse)(nil),          // 22: identity.v1.UseItemResponse
	(*ShopOrder)(nil),                // 23: identity.v1.ShopOrder
	(*SellLine)(nil),                 // 24: identity.v1.SellLine
	(*BuyFromShopRequest)(nil),       // 25: identity.v1.BuyFromShopRequest
	(*BuyFromShopResponse)(nil),      // 26: identity.v1.BuyFromShopResponse
	(*SellToShopRequest)(nil),        // 27: identity.v1.SellToShopRequest
	(*SellToShopResponse)(nil),       // 28: identity.v1.SellToShopResponse
	(*ApplyLevelUpRequest)(nil),      // 29: identity.v1.ApplyLevelUpRequest
	(*ApplyLevelUpResponse)(nil),     // 30: identity.v1.ApplyLevelUpResponse
	(*AllocateStatRequest)(nil),      // 31: identity.v1.AllocateStatRequest
	(*AllocateStatResponse)(nil),     // 32: identity.v1.AllocateStatResponse
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	0,  // 0: identity.v1.AuthenticateRequest.method:type_name -> identity.v1.AuthMethod
	1,  // 1: identity.v1.AuthenticateResponse.result:type_name -> identity.v1.AuthResult
	7,  // 2: identity.v1.AuthenticateResponse.char_servers:type_name -> identity.v1.CharServerInfo
	9,  // 3: identity.v1.GetCharacterListResponse.characters:type_name -> identity.v1.CharacterInfo
	12, // 4: identity.v1.GetCharacterResponse.character:type_name -> identity.v1.CharacterDetail
	15, // 5: identity.v1.GetInventoryResponse.items:type_name -> identity.v1.InventoryItem
	23, // 6: identity.v1.BuyFromShopRequest.orders:type_name -> identity.v1.ShopOrder
	2,  // 7: identity.v1.BuyFromShopResponse.result:type_name -> identity.v1.BuyResult
	24, // 8: identity.v1.SellToShopRequest.sales:type_name -> identity.v1.SellLine
	3,  // 9: identity.v1.SellToShopResponse.result:type_name -> identity.v1.SellResult
	4,  // 10: identity.v1.AllocateStatResponse.result:type_name -> identity.v1.StatResult
	5,  // 11: identity.v1.IdentityService.Authenticate:input_type -> identity.v1.AuthenticateRequest
	8,  // 12: identity.v1.IdentityService.GetCharacterList:input_type -> identity.v1.GetCharacterListRequest
	11, // 13: identity.v1.IdentityService.GetCharacter:input_type -> identity.v1.GetCharacterRequest
	14, // 14: identity.v1.IdentityService.GetInventory:input_type -> identity.v1.GetInventoryRequest
	17, // 15: identity.v1.IdentityService.EquipItem:input_type -> identity.v1.EquipItemRequest
	19, // 16: identity.v1.IdentityService.UnequipItem:input_type -> identity.v1.UnequipItemRequest
	21, // 17: identity.v1.IdentityService.UseItem:input_type -> identity.v1.UseItemRequest
	25, // 18: identity.v1.IdentityService.BuyFromShop:input_type -> identity.v1.BuyFromShopRequest
	27, // 19: identity.v1.IdentityService.SellToShop:input_type -> identity.v1.SellToShopRequest
	29, // 20: identity.v1.IdentityService.ApplyLevelUp:input_type -> identity.v1.ApplyLevelUpRequest
	31, // 21: identity.v1.IdentityService.AllocateStat:input_type -> identity.v1.AllocateStatRequest
	6,  // 22: identity.v1.IdentityService.Authenticate:output_type -> identity.v1.AuthenticateResponse
	10, // 23: identity.v1.IdentityService.GetCharacterList:output_type -> identity.v1.GetCharacterListResponse
	13, // 24: identity.v1.IdentityService.GetCharacter:output_type -> identity.v1.GetCharacterResponse
	16, // 25: identity.v1.IdentityService.GetInventory:output_type -> identity.v1.GetInventoryResponse
	18, // 26: identity.v1.IdentityService.EquipItem:output_type -> identity.v1.EquipItemResponse
	20, // 27: identity.v1.IdentityService.UnequipItem:output_type -> identity.v1.UnequipItemResponse
	22, // 28: identity.v1.IdentityService.UseItem:output_type -> identity.v1.UseItemResponse
	26, // 29: identity.v1.IdentityService.BuyFromShop:output_type -> identity.v1.BuyFromShopResponse
	28, // 30: identity.v1.IdentityService.SellToShop:output_type -> identity.v1.SellToShopResponse
	30, // 31: identity.v1.IdentityService.ApplyLevelUp:output_type -> identity.v1.ApplyLevelUpResponse
	32, // 32: identity.v1.IdentityService.AllocateStat:output_type -> identity.v1.AllocateStatResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
