// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: identity/v1/identity.proto

package identityv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthMethod identifies which CA_LOGIN variant the client sent.
type AuthMethod int32

const (
	AuthMethod_AUTH_METHOD_UNSPECIFIED AuthMethod = 0
	AuthMethod_AUTH_METHOD_PASSWORD    AuthMethod = 1 // CA_LOGIN 0x0064 (plaintext password)
	AuthMethod_AUTH_METHOD_MD5         AuthMethod = 2 // CA_LOGIN2 0x01dd (MD5 password)
	AuthMethod_AUTH_METHOD_MD5_SALTED  AuthMethod = 3 // CA_LOGIN3/4 0x01fa/0x027c
	AuthMethod_AUTH_METHOD_PCBANG      AuthMethod = 4 // CA_LOGIN_PCBANG 0x0277
	AuthMethod_AUTH_METHOD_CHANNEL     AuthMethod = 5 // CA_LOGIN_CHANNEL 0x02b0
	AuthMethod_AUTH_METHOD_SSO         AuthMethod = 6 // CA_SSO_LOGIN_REQ 0x0825
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "AUTH_METHOD_UNSPECIFIED",
		1: "AUTH_METHOD_PASSWORD",
		2: "AUTH_METHOD_MD5",
		3: "AUTH_METHOD_MD5_SALTED",
		4: "AUTH_METHOD_PCBANG",
		5: "AUTH_METHOD_CHANNEL",
		6: "AUTH_METHOD_SSO",
	}
	AuthMethod_value = map[string]int32{
		"AUTH_METHOD_UNSPECIFIED": 0,
		"AUTH_METHOD_PASSWORD":    1,
		"AUTH_METHOD_MD5":         2,
		"AUTH_METHOD_MD5_SALTED":  3,
		"AUTH_METHOD_PCBANG":      4,
		"AUTH_METHOD_CHANNEL":     5,
		"AUTH_METHOD_SSO":         6,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[0]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type AuthResult int32

const (
	AuthResult_AUTH_RESULT_UNSPECIFIED       AuthResult = 0
	AuthResult_AUTH_RESULT_OK                AuthResult = 1
	AuthResult_AUTH_RESULT_REJECTED          AuthResult = 2 // AC_REFUSE_LOGIN — wrong credentials
	AuthResult_AUTH_RESULT_BANNED            AuthResult = 3
	AuthResult_AUTH_RESULT_ALREADY_LOGGED_IN AuthResult = 4
	AuthResult_AUTH_RESULT_SERVER_CLOSED     AuthResult = 5 // SC_NOTIFY_BAN
)

// Enum value maps for AuthResult.
var (
	AuthResult_name = map[int32]string{
		0: "AUTH_RESULT_UNSPECIFIED",
		1: "AUTH_RESULT_OK",
		2: "AUTH_RESULT_REJECTED",
		3: "AUTH_RESULT_BANNED",
		4: "AUTH_RESULT_ALREADY_LOGGED_IN",
		5: "AUTH_RESULT_SERVER_CLOSED",
	}
	AuthResult_value = map[string]int32{
		"AUTH_RESULT_UNSPECIFIED":       0,
		"AUTH_RESULT_OK":                1,
		"AUTH_RESULT_REJECTED":          2,
		"AUTH_RESULT_BANNED":            3,
		"AUTH_RESULT_ALREADY_LOGGED_IN": 4,
		"AUTH_RESULT_SERVER_CLOSED":     5,
	}
)

func (x AuthResult) Enum() *AuthResult {
	p := new(AuthResult)
	*p = x
	return p
}

func (x AuthResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthResult) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[1].Descriptor()
}

func (AuthResult) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[1]
}

func (x AuthResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthResult.Descriptor instead.
func (AuthResult) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                        // plaintext (AUTH_METHOD_PASSWORD) or MD5 digest
	ClientType    uint32                 `protobuf:"varint,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // kRO client type code
	Packetver     uint32                 `protobuf:"varint,4,opt,name=packetver,proto3" json:"packetver,omitempty"`                     // client PACKETVER date (e.g. 20130807)
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Method        AuthMethod             `protobuf:"varint,6,opt,name=method,proto3,enum=identity.v1.AuthMethod" json:"method,omitempty"`
	Md5Salt       []byte                 `protobuf:"bytes,7,opt,name=md5_salt,json=md5Salt,proto3" json:"md5_salt,omitempty"` // salt from CA_REQ_HASH/AC_ACK_HASH exchange (if applicable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *AuthenticateRequest) GetClientType() uint32 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *AuthenticateRequest) GetPacketver() uint32 {
	if x != nil {
		return x.Packetver
	}
	return 0
}

func (x *AuthenticateRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuthenticateRequest) GetMethod() AuthMethod {
	if x != nil {
		return x.Method
	}
	return AuthMethod_AUTH_METHOD_UNSPECIFIED
}

func (x *AuthenticateRequest) GetMd5Salt() []byte {
	if x != nil {
		return x.Md5Salt
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AuthResult             `protobuf:"varint,1,opt,name=result,proto3,enum=identity.v1.AuthResult" json:"result,omitempty"`
	ErrorCode     uint32                 `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // kRO-specific error code (0-15, 99-104)
	AccountId     uint32                 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LoginId1      uint64                 `protobuf:"fixed64,4,opt,name=login_id1,json=loginId1,proto3" json:"login_id1,omitempty"` // session token minted on success
	LoginId2      uint64                 `protobuf:"fixed64,5,opt,name=login_id2,json=loginId2,proto3" json:"login_id2,omitempty"`
	LastIp        string                 `protobuf:"bytes,6,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
	LastLogin     string                 `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	Sex           string                 `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"`     // "M", "F", or "S"
	Token         string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"` // web auth token (PACKETVER >= 20170315)
	CharServers   []*CharServerInfo      `protobuf:"bytes,10,rep,name=char_servers,json=charServers,proto3" json:"char_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetResult() AuthResult {
	if x != nil {
		return x.Result
	}
	return AuthResult_AUTH_RESULT_UNSPECIFIED
}

func (x *AuthenticateResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *AuthenticateResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AuthenticateResponse) GetLoginId1() uint64 {
	if x != nil {
		return x.LoginId1
	}
	return 0
}

func (x *AuthenticateResponse) GetLoginId2() uint64 {
	if x != nil {
		return x.LoginId2
	}
	return 0
}

func (x *AuthenticateResponse) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

func (x *AuthenticateResponse) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *AuthenticateResponse) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *AuthenticateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateResponse) GetCharServers() []*CharServerInfo {
	if x != nil {
		return x.CharServers
	}
	return nil
}

type CharServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Users         uint32                 `protobuf:"varint,4,opt,name=users,proto3" json:"users,omitempty"`
	ServerType    uint32                 `protobuf:"varint,5,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	NewDisplay    string                 `protobuf:"bytes,6,opt,name=new_display,json=newDisplay,proto3" json:"new_display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharServerInfo) Reset() {
	*x = CharServerInfo{}
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharServerInfo) ProtoMessage() {}

func (x *CharServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharServerInfo.ProtoReflect.Descriptor instead.
func (*CharServerInfo) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *CharServerInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CharServerInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CharServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharServerInfo) GetUsers() uint32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *CharServerInfo) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *CharServerInfo) GetNewDisplay() string {
	if x != nil {
		return x.NewDisplay
	}
	return ""
}

type GetCharacterListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LoginId1      uint64                 `protobuf:"fixed64,2,opt,name=login_id1,json=loginId1,proto3" json:"login_id1,omitempty"` // from AuthenticateResponse
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterListRequest) Reset() {
	*x = GetCharacterListRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterListRequest) ProtoMessage() {}

func (x *GetCharacterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterListRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterListRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterListRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetCharacterListRequest) GetLoginId1() uint64 {
	if x != nil {
		return x.LoginId1
	}
	return 0
}

func (x *GetCharacterListRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClassId       uint32                 `protobuf:"varint,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	BaseLevel     uint32                 `protobuf:"varint,5,opt,name=base_level,json=baseLevel,proto3" json:"base_level,omitempty"`
	JobLevel      uint32                 `protobuf:"varint,6,opt,name=job_level,json=jobLevel,proto3" json:"job_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterInfo) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *CharacterInfo) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CharacterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterInfo) GetClassId() uint32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *CharacterInfo) GetBaseLevel() uint32 {
	if x != nil {
		return x.BaseLevel
	}
	return 0
}

func (x *CharacterInfo) GetJobLevel() uint32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

type GetCharacterListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterInfo       `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	TotalSlots    uint32                 `protobuf:"varint,2,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	PremiumStart  uint32                 `protobuf:"varint,3,opt,name=premium_start,json=premiumStart,proto3" json:"premium_start,omitempty"`
	PremiumEnd    uint32                 `protobuf:"varint,4,opt,name=premium_end,json=premiumEnd,proto3" json:"premium_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterListResponse) Reset() {
	*x = GetCharacterListResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterListResponse) ProtoMessage() {}

func (x *GetCharacterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterListResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterListResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetCharacterListResponse) GetCharacters() []*CharacterInfo {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *GetCharacterListResponse) GetTotalSlots() uint32 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *GetCharacterListResponse) GetPremiumStart() uint32 {
	if x != nil {
		return x.PremiumStart
	}
	return 0
}

func (x *GetCharacterListResponse) GetPremiumEnd() uint32 {
	if x != nil {
		return x.PremiumEnd
	}
	return 0
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\videntity.v1\"\xf5\x01\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\x12\x1f\n" +
	"\vclient_type\x18\x03 \x01(\rR\n" +
	"clientType\x12\x1c\n" +
	"\tpacketver\x18\x04 \x01(\rR\tpacketver\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12/\n" +
	"\x06method\x18\x06 \x01(\x0e2\x17.identity.v1.AuthMethodR\x06method\x12\x19\n" +
	"\bmd5_salt\x18\a \x01(\fR\amd5Salt\"\xdf\x02\n" +
	"\x14AuthenticateResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x17.identity.v1.AuthResultR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\rR\terrorCode\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\rR\taccountId\x12\x1b\n" +
	"\tlogin_id1\x18\x04 \x01(\x06R\bloginId1\x12\x1b\n" +
	"\tlogin_id2\x18\x05 \x01(\x06R\bloginId2\x12\x17\n" +
	"\alast_ip\x18\x06 \x01(\tR\x06lastIp\x12\x1d\n" +
	"\n" +
	"last_login\x18\a \x01(\tR\tlastLogin\x12\x10\n" +
	"\x03sex\x18\b \x01(\tR\x03sex\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x12>\n" +
	"\fchar_servers\x18\n" +
	" \x03(\v2\x1b.identity.v1.CharServerInfoR\vcharServers\"\xa0\x01\n" +
	"\x0eCharServerInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05users\x18\x04 \x01(\rR\x05users\x12\x1f\n" +
	"\vserver_type\x18\x05 \x01(\rR\n" +
	"serverType\x12\x1f\n" +
	"\vnew_display\x18\x06 \x01(\tR\n" +
	"newDisplay\"g\n" +
	"\x17GetCharacterListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x1b\n" +
	"\tlogin_id1\x18\x02 \x01(\x06R\bloginId1\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\"\xa7\x01\n" +
	"\rCharacterInfo\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\rR\x04slot\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bclass_id\x18\x04 \x01(\rR\aclassId\x12\x1d\n" +
	"\n" +
	"base_level\x18\x05 \x01(\rR\tbaseLevel\x12\x1b\n" +
	"\tjob_level\x18\x06 \x01(\rR\bjobLevel\"\xbd\x01\n" +
	"\x18GetCharacterListResponse\x12:\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1a.identity.v1.CharacterInfoR\n" +
	"characters\x12\x1f\n" +
	"\vtotal_slots\x18\x02 \x01(\rR\n" +
	"totalSlots\x12#\n" +
	"\rpremium_start\x18\x03 \x01(\rR\fpremiumStart\x12\x1f\n" +
	"\vpremium_end\x18\x04 \x01(\rR\n" +
	"premiumEnd*\xba\x01\n" +
	"\n" +
	"AuthMethod\x12\x1b\n" +
	"\x17AUTH_METHOD_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUTH_METHOD_PASSWORD\x10\x01\x12\x13\n" +
	"\x0fAUTH_METHOD_MD5\x10\x02\x12\x1a\n" +
	"\x16AUTH_METHOD_MD5_SALTED\x10\x03\x12\x16\n" +
	"\x12AUTH_METHOD_PCBANG\x10\x04\x12\x17\n" +
	"\x13AUTH_METHOD_CHANNEL\x10\x05\x12\x13\n" +
	"\x0fAUTH_METHOD_SSO\x10\x06*\xb1\x01\n" +
	"\n" +
	"AuthResult\x12\x1b\n" +
	"\x17AUTH_RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUTH_RESULT_OK\x10\x01\x12\x18\n" +
	"\x14AUTH_RESULT_REJECTED\x10\x02\x12\x16\n" +
	"\x12AUTH_RESULT_BANNED\x10\x03\x12!\n" +
	"\x1dAUTH_RESULT_ALREADY_LOGGED_IN\x10\x04\x12\x1d\n" +
	"\x19AUTH_RESULT_SERVER_CLOSED\x10\x052\xc7\x01\n" +
	"\x0fIdentityService\x12S\n" +
	"\fAuthenticate\x12 .identity.v1.AuthenticateRequest\x1a!.identity.v1.AuthenticateResponse\x12_\n" +
	"\x10GetCharacterList\x12$.identity.v1.GetCharacterListRequest\x1a%.identity.v1.GetCharacterListResponseB:Z8github.com/bouroo/goAthena/api/pb/identity/v1;identityv1b\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_identity_v1_identity_proto_goTypes = []any{
	(AuthMethod)(0),                  // 0: identity.v1.AuthMethod
	(AuthResult)(0),                  // 1: identity.v1.AuthResult
	(*AuthenticateRequest)(nil),      // 2: identity.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),     // 3: identity.v1.AuthenticateResponse
	(*CharServerInfo)(nil),           // 4: identity.v1.CharServerInfo
	(*GetCharacterListRequest)(nil),  // 5: identity.v1.GetCharacterListRequest
	(*CharacterInfo)(nil),            // 6: identity.v1.CharacterInfo
	(*GetCharacterListResponse)(nil), // 7: identity.v1.GetCharacterListResponse
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: identity.v1.AuthenticateRequest.method:type_name -> identity.v1.AuthMethod
	1, // 1: identity.v1.AuthenticateResponse.result:type_name -> identity.v1.AuthResult
	4, // 2: identity.v1.AuthenticateResponse.char_servers:type_name -> identity.v1.CharServerInfo
	6, // 3: identity.v1.GetCharacterListResponse.characters:type_name -> identity.v1.CharacterInfo
	2, // 4: identity.v1.IdentityService.Authenticate:input_type -> identity.v1.AuthenticateRequest
	5, // 5: identity.v1.IdentityService.GetCharacterList:input_type -> identity.v1.GetCharacterListRequest
	3, // 6: identity.v1.IdentityService.Authenticate:output_type -> identity.v1.AuthenticateResponse
	7, // 7: identity.v1.IdentityService.GetCharacterList:output_type -> identity.v1.GetCharacterListResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
