// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/storage/domain (interfaces: StorageService)
//
// Generated by this command:
//
//	mockgen -destination=mock/storage_service_mock.go -package=domainmock . StorageService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
	isgomock struct{}
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// CloseStorage mocks base method.
func (m *MockStorageService) CloseStorage(ctx context.Context, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseStorage", ctx, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseStorage indicates an expected call of CloseStorage.
func (mr *MockStorageServiceMockRecorder) CloseStorage(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseStorage", reflect.TypeOf((*MockStorageService)(nil).CloseStorage), ctx, charID)
}

// DepositItem mocks base method.
func (m *MockStorageService) DepositItem(ctx context.Context, charID uint32, inventoryItemID uint64, amount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepositItem", ctx, charID, inventoryItemID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DepositItem indicates an expected call of DepositItem.
func (mr *MockStorageServiceMockRecorder) DepositItem(ctx, charID, inventoryItemID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepositItem", reflect.TypeOf((*MockStorageService)(nil).DepositItem), ctx, charID, inventoryItemID, amount)
}

// OpenStorage mocks base method.
func (m *MockStorageService) OpenStorage(ctx context.Context, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenStorage", ctx, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenStorage indicates an expected call of OpenStorage.
func (mr *MockStorageServiceMockRecorder) OpenStorage(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenStorage", reflect.TypeOf((*MockStorageService)(nil).OpenStorage), ctx, charID)
}

// WithdrawItem mocks base method.
func (m *MockStorageService) WithdrawItem(ctx context.Context, charID uint32, storageItemID uint64, amount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawItem", ctx, charID, storageItemID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawItem indicates an expected call of WithdrawItem.
func (mr *MockStorageServiceMockRecorder) WithdrawItem(ctx, charID, storageItemID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawItem", reflect.TypeOf((*MockStorageService)(nil).WithdrawItem), ctx, charID, storageItemID, amount)
}
