// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/storage/domain (interfaces: StorageRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/storage_repository_mock.go -package=domainmock . StorageRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/storage/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepository is a mock of StorageRepository interface.
type MockStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockStorageRepositoryMockRecorder is the mock recorder for MockStorageRepository.
type MockStorageRepositoryMockRecorder struct {
	mock *MockStorageRepository
}

// NewMockStorageRepository creates a new mock instance.
func NewMockStorageRepository(ctrl *gomock.Controller) *MockStorageRepository {
	mock := &MockStorageRepository{ctrl: ctrl}
	mock.recorder = &MockStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepository) EXPECT() *MockStorageRepositoryMockRecorder {
	return m.recorder
}

// CountStorageItems mocks base method.
func (m *MockStorageRepository) CountStorageItems(ctx context.Context, accountID uint32) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountStorageItems", ctx, accountID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountStorageItems indicates an expected call of CountStorageItems.
func (mr *MockStorageRepositoryMockRecorder) CountStorageItems(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountStorageItems", reflect.TypeOf((*MockStorageRepository)(nil).CountStorageItems), ctx, accountID)
}

// CreateStorageItem mocks base method.
func (m *MockStorageRepository) CreateStorageItem(ctx context.Context, item domain.StorageItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStorageItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStorageItem indicates an expected call of CreateStorageItem.
func (mr *MockStorageRepositoryMockRecorder) CreateStorageItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStorageItem", reflect.TypeOf((*MockStorageRepository)(nil).CreateStorageItem), ctx, item)
}

// DeleteStorageItem mocks base method.
func (m *MockStorageRepository) DeleteStorageItem(ctx context.Context, itemID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStorageItem", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStorageItem indicates an expected call of DeleteStorageItem.
func (mr *MockStorageRepositoryMockRecorder) DeleteStorageItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStorageItem", reflect.TypeOf((*MockStorageRepository)(nil).DeleteStorageItem), ctx, itemID)
}

// GetStorageItem mocks base method.
func (m *MockStorageRepository) GetStorageItem(ctx context.Context, itemID uint64) (domain.StorageItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageItem", ctx, itemID)
	ret0, _ := ret[0].(domain.StorageItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageItem indicates an expected call of GetStorageItem.
func (mr *MockStorageRepositoryMockRecorder) GetStorageItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageItem", reflect.TypeOf((*MockStorageRepository)(nil).GetStorageItem), ctx, itemID)
}

// ListStorageByAccount mocks base method.
func (m *MockStorageRepository) ListStorageByAccount(ctx context.Context, accountID uint32) ([]domain.StorageItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStorageByAccount", ctx, accountID)
	ret0, _ := ret[0].([]domain.StorageItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStorageByAccount indicates an expected call of ListStorageByAccount.
func (mr *MockStorageRepositoryMockRecorder) ListStorageByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStorageByAccount", reflect.TypeOf((*MockStorageRepository)(nil).ListStorageByAccount), ctx, accountID)
}

// UpdateStorageItem mocks base method.
func (m *MockStorageRepository) UpdateStorageItem(ctx context.Context, item domain.StorageItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStorageItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStorageItem indicates an expected call of UpdateStorageItem.
func (mr *MockStorageRepositoryMockRecorder) UpdateStorageItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStorageItem", reflect.TypeOf((*MockStorageRepository)(nil).UpdateStorageItem), ctx, item)
}
