// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/economy/domain (interfaces: ShopService)
//
// Generated by this command:
//
//	mockgen -destination=mock/shop_service_mock.go -package=domainmock . ShopService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/bouroo/goAthena/internal/features/economy/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockShopService is a mock of ShopService interface.
type MockShopService struct {
	ctrl     *gomock.Controller
	recorder *MockShopServiceMockRecorder
	isgomock struct{}
}

// MockShopServiceMockRecorder is the mock recorder for MockShopService.
type MockShopServiceMockRecorder struct {
	mock *MockShopService
}

// NewMockShopService creates a new mock instance.
func NewMockShopService(ctrl *gomock.Controller) *MockShopService {
	mock := &MockShopService{ctrl: ctrl}
	mock.recorder = &MockShopServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopService) EXPECT() *MockShopServiceMockRecorder {
	return m.recorder
}

// BuyFromShop mocks base method.
func (m *MockShopService) BuyFromShop(ctx context.Context, charID uint32, orders []domain.ShopOrder) (uint32, domain.BuyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyFromShop", ctx, charID, orders)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(domain.BuyResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuyFromShop indicates an expected call of BuyFromShop.
func (mr *MockShopServiceMockRecorder) BuyFromShop(ctx, charID, orders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyFromShop", reflect.TypeOf((*MockShopService)(nil).BuyFromShop), ctx, charID, orders)
}

// SellToShop mocks base method.
func (m *MockShopService) SellToShop(ctx context.Context, charID uint32, sales []domain.SellLine) (uint32, domain.SellResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SellToShop", ctx, charID, sales)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(domain.SellResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SellToShop indicates an expected call of SellToShop.
func (mr *MockShopServiceMockRecorder) SellToShop(ctx, charID, sales any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SellToShop", reflect.TypeOf((*MockShopService)(nil).SellToShop), ctx, charID, sales)
}
