apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goathena-prod

namePrefix: prod-

resources:
  - ../../base

configMapGenerator:
  - name: goathena-config
    behavior: merge
    literals:
      - DB_SSLMODE=verify-full

patches:
  - path: patches/deployment-patch.yaml