// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bouroo/goAthena/internal/features/registry/domain (interfaces: Registry)
//
// Generated by this command:
//
//	mockgen -destination=mock/registry_mock.go -package=domainmock . Registry
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/bouroo/goAthena/internal/features/registry/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// AcquireZoneLock mocks base method.
func (m *MockRegistry) AcquireZoneLock(ctx context.Context, charID uint32, zoneID string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireZoneLock", ctx, charID, zoneID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcquireZoneLock indicates an expected call of AcquireZoneLock.
func (mr *MockRegistryMockRecorder) AcquireZoneLock(ctx, charID, zoneID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireZoneLock", reflect.TypeOf((*MockRegistry)(nil).AcquireZoneLock), ctx, charID, zoneID, ttl)
}

// GetCharacterLocation mocks base method.
func (m *MockRegistry) GetCharacterLocation(ctx context.Context, charID uint32) (*domain.CharacterLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterLocation", ctx, charID)
	ret0, _ := ret[0].(*domain.CharacterLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterLocation indicates an expected call of GetCharacterLocation.
func (mr *MockRegistryMockRecorder) GetCharacterLocation(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterLocation", reflect.TypeOf((*MockRegistry)(nil).GetCharacterLocation), ctx, charID)
}

// ListCharactersOnZone mocks base method.
func (m *MockRegistry) ListCharactersOnZone(ctx context.Context, zoneID string) ([]domain.CharacterLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCharactersOnZone", ctx, zoneID)
	ret0, _ := ret[0].([]domain.CharacterLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCharactersOnZone indicates an expected call of ListCharactersOnZone.
func (mr *MockRegistryMockRecorder) ListCharactersOnZone(ctx, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCharactersOnZone", reflect.TypeOf((*MockRegistry)(nil).ListCharactersOnZone), ctx, zoneID)
}

// RegisterCharacter mocks base method.
func (m *MockRegistry) RegisterCharacter(ctx context.Context, loc domain.CharacterLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCharacter", ctx, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCharacter indicates an expected call of RegisterCharacter.
func (mr *MockRegistryMockRecorder) RegisterCharacter(ctx, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCharacter", reflect.TypeOf((*MockRegistry)(nil).RegisterCharacter), ctx, loc)
}

// ReleaseZoneLock mocks base method.
func (m *MockRegistry) ReleaseZoneLock(ctx context.Context, charID uint32, zoneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseZoneLock", ctx, charID, zoneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseZoneLock indicates an expected call of ReleaseZoneLock.
func (mr *MockRegistryMockRecorder) ReleaseZoneLock(ctx, charID, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseZoneLock", reflect.TypeOf((*MockRegistry)(nil).ReleaseZoneLock), ctx, charID, zoneID)
}

// UnregisterCharacter mocks base method.
func (m *MockRegistry) UnregisterCharacter(ctx context.Context, charID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterCharacter", ctx, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterCharacter indicates an expected call of UnregisterCharacter.
func (mr *MockRegistryMockRecorder) UnregisterCharacter(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterCharacter", reflect.TypeOf((*MockRegistry)(nil).UnregisterCharacter), ctx, charID)
}
