apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goathena
resources:
  - gameserver-template.yaml
  - fleet.yaml
  - fleet-autoscaler.yaml
commonLabels:
  app.kubernetes.io/name: goathena
  app.kubernetes.io/part-of: goathena
